# Logits Preprocessing and Data Engineering

In [ ]:
def default_params(): 
    return {
        'current_model': 'M1', 
        'quantization': 'none', #['none',"int4", "int8", "float32", "float16"]
        'dataset': {
            'path': '/workspaces/CodeSmells/semeru-datasets/code_smells/transformation',
            'transformation': 'curated',
            'content_column': 'code',
            'sampling_size': 500,
        },
        'logging_path': '/workspaces/CodeSmells/datax/code_smells/logs', 
        'output_path' : '/workspaces/CodeSmells/datax/code_smells/logits',
        'callbacks_path' : '/workspaces/CodeSmells/datax/code_smells/callbacks',
        'cache_dir': '/workspaces/CodeSmells/datax/hugging_face_cache',
        'causal_models': {
            'M1' : 'codellama/CodeLlama-7b-hf', #https://huggingface.co/codellama/CodeLlama-7b-hf, 
        },
    }
params = default_params()

#### Imports

In [2]:
import pandas as pd
import os
import time
import numpy as np
import torch
import gc

In [3]:
import seaborn as sns
from scipy import stats
from statistics import NormalDist
import matplotlib.pyplot as plt

In [4]:
from transformers import CodeLlamaTokenizer, LlamaForCausalLM
from datasets import load_dataset

In [5]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [6]:
# Define log file path
log_file = f"{params['logging_path']}/{params['current_model']}/{params['dataset']['transformation']}"
create_folder(log_file)
log_file += '/data_en.txt'

# Create the log file if it doesn't exist
if not os.path.exists(log_file):
    with open(log_file, 'w'): 
        pass  # Create an empty log file

In [7]:
import logging
logging.basicConfig(filename=log_file, format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

#### Dataset

In [8]:
print(f"{params['dataset']['path']}/{params['dataset']['transformation']}_{params['dataset']['sampling_size']}.json")

/workspaces/CodeSmells/semeru-datasets/code_smells/extraction/curated_500.json

In [10]:
df_dataset = pd.read_json(f"{params['dataset']['path']}/{params['dataset']['transformation']}_{params['dataset']['sampling_size']}.json", )

In [11]:
df_dataset

,id,commit_id,repo,path,file_name,fun_name,commit_message,code,url,language,...,n_ast_nodes,n_identifiers,s_msg_id,s_line,s_column,s_end_line,s_end_column,s_code,category,input_lenght
0,256261,a59bca366174d9c692fa19750c24d65f47660ef7,haystack,haystack/modeling/training/base.py,base.py,_get_state_dict,Apply black formatting (#2115)\n\n* Testing bl...,def _get_state_dict(self):\n \n ...,https://github.com/deepset-ai/haystack.git,Python,...,193,20,W0311,2,0,2,22,state_dict = {,Warning,296
1,305801,6f564e4f514b56bce281ec7e82703cfbff87b417,core,homeassistant/components/ring/binary_sensor.py,binary_sensor.py,async_added_to_hass,Improve entity type hints [r] (#77874),async def async_added_to_hass(self) -> None:\n...,https://github.com/home-assistant/core.git,Python,...,63,6,W0311,4,0,4,37,self._dings_update_callback(),Warning,73
2,70649,5fe901e5d86ed02dbbb63039a897582951266afd,wagtail,wagtail/admin/tests/pages/test_edit_page.py,test_edit_page.py,test_new_comment,Fix commenting thread notifications being sent...,def test_new_comment(self):\n post_data...,https://github.com/wagtail/wagtail.git,Python,...,565,37,C0301,33,0,33,125,self.assertEqual(mail.outbox[0].subjec...,Convention,666
3,151753,bdfedb5fcb02b88c600ef25c88bbb5d939b8bd0a,freqtrade,freqtrade/freqai/RL/BaseReinforcementLearningM...,BaseReinforcementLearningModel.py,__init__,Improve typehints / reduce warnings from mypy,"def __init__(self, **kwargs) -> None:\n ...",https://github.com/freqtrade/freqtrade.git,Python,...,411,38,W0311,13,0,13,44,import_str = 'stable_baselines3',Warning,494
4,3868,2282a4ae0221b1fb88e16eca8bc14a166998d2d2,airbyte,airbyte-integrations/connectors/source-hubspot...,streams.py,state,🎉 Source Hubspot: Migrate to CDK (#10177)\n\n*...,"def state(self, value):\n state_value =...",https://github.com/airbytehq/airbyte.git,Python,...,99,14,W0311,7,0,7,61,"self._start_date = max(self._state, se...",Warning,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702546,43471,09f38ad3f6872bae5059a1de226362eb358c4a7a,airflow,tests/providers/microsoft/azure/operators/test...,test_asb.py,test_send_message_queue,Implement Azure Service Bus Queue Operators (#...,"def test_send_message_queue(self, mock_get_con...",https://github.com/apache/airflow.git,Python,...,132,21,C2801,10,12,13,24,mock.call()\n .__enter__()\n ...,Convention,193
1704801,196984,4a6d5d342e1d0111130d4b31708535b862bfacd0,sympy,sympy/printing/repr.py,repr.py,_print_Permutation,Update the deprecation for Permutation.print_c...,"def _print_Permutation(self, expr):\n f...",https://github.com/sympy/sympy.git,Python,...,388,30,C2801,20,16,20,53,Cycle(expr)(expr.size - 1).__repr__(),Convention,441
1705975,105,0b8a53bd313abdf484a9d1e3fbd6aad13c0ec857,PySyft,packages/syft/tests/syft/core/tensor/passthrou...,passthrough_test.py,test__rshift__,adding tests,def test__rshift__() -> None:\n data_a = np...,https://github.com/OpenMined/PySyft.git,Python,...,183,17,C2801,7,15,7,44,tensor_a.__rshift__(tensor_b),Convention,204
1717859,117464,9ce5a21dd6359fd7e8ebf78051ce9e97bd195ec9,mindsdb,tests/unit/executor_test_base.py,executor_test_base.py,set_executor,ML handler supbrocess (#3377)\n\n* log -> logg...,"def set_executor(self, to_mock_model_controlle...",https://github.com/mindsdb/mindsdb.git,Python,...,422,53,C2801,49,27,49,51,config_patch.__enter__(),Convention,610
1724032,2754,6227dbb522db10c70f5fbe39d20e75cfdb0a449f,PySyft,packages/syft/src/syft/oblv/model.py,model.py,initiate_connection,Removed unused params and updated proxy connec...,def initiate_connection(self):\n check_...,https://github.com/OpenMined/PySyft.git,Python,...,469,39,C2801,20,19,20,63,"d.__contains__(""Error: Invalid PCR Values"")",Convention,539

#### Model Loading

In [38]:
def instantiate_llm(model_name:str, cache_dir:str):
     '''Instantiate AutoModelForCausalLM'''
     tokenizer = CodeLlamaTokenizer.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoTokenizer - " + model_name)
     model = None
     if params['quantization'] == 'int4':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_4bit=True)
     elif params['quantization'] == 'int8':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_8bit=True)
     elif params['quantization'] == 'float32':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float32)
     elif params['quantization'] == 'float16':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float16)
     else: 
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoModelForCausalLM - " + model_name)

     return tokenizer, model

In [39]:
tokenizer, model = instantiate_llm(params['causal_models'][params['current_model']], params['cache_dir'])

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [40]:
model.config

LlamaConfig {
  "_name_or_path": "codellama/CodeLlama-7b-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 16384,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 1000000,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32016
}

#### preprocess dataset

In [56]:
df_dataset['input_ids'] = df_dataset[params['dataset']['content_column']].map(lambda code: tokenizer.encode(code, add_special_tokens=False))
df_dataset['input_lenght'] = df_dataset['input_ids'].map(lambda input_ids: len(input_ids))

#### Softmax Normalization and Data Engineering

In [57]:
def topk_tuple( logit_vocab_tensor, largest, tokenizer_fn):
    "Run topk for a token"
    topk = logit_vocab_tensor.topk( k=1 , largest=largest ) #TODO K number of elements can be extended
    return ( tokenizer.convert_tokens_to_string([tokenizer_fn.decode(topk.indices)]), topk.values.item())

def min_max_logits( logit_vocab_sample_tensor, tokenizer_fn ):
    "Compute min_max for a sample"
    max_cases = []
    min_cases = []
    for logit_vocab_tensor in logit_vocab_sample_tensor:
        max_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = True, tokenizer_fn = tokenizer_fn) ) #TST Max Logit
        min_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = False, tokenizer_fn = tokenizer_fn) ) #TST Min Logit
    return max_cases, min_cases

def actual_logit( 
                 logit_vocab_sample_tensor, 
                 tokenized_prompt, 
                 tokenizer_fn,
                 ):
    "Compute actual logits for a sample"
    actual_logits_prompt = []
    for token_pos, id_token in enumerate( tokenized_prompt[1:] ): #Eliminate the first token prediction since we do not use it
        actual_logits_prompt.append(
            (   tokenizer.convert_tokens_to_string([tokenizer_fn.decode( int(id_token))]), #retrieving the name of the token with the id
                logit_vocab_sample_tensor[token_pos][int(id_token)].item()) #retrieving the logit given the position in the sequence and the position in the vocab
            )
    return actual_logits_prompt

In [58]:
soft = torch.nn.Softmax( dim = 0 ) #Flattening normalization

In [59]:
callbacks_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
out = np.load(f"{callbacks_dir}/logits_tensor[0]_batch[0].npy")

print(out.shape) #<sample,tokens,voc_tokens>
out = out[0]

(1, 296, 32016)

In [60]:
max_case,min_case = min_max_logits(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out], ####### 
    tokenizer_fn= tokenizer
    )
print(max_case)
assert len(max_case) == len(min_case)

[('<PRE>', 0.7492886185646057), ('module', 0.47944238781929016), ('get', 0.12872232496738434), ('_', 0.8901668787002563), ('data', 0.010642001405358315), ('_', 0.462878942489624), ('dict', 0.09639009833335876), ('(', 0.7244718670845032), ('model', 0.20590771734714508), ('):', 0.513270914554596), ('\n', 0.9693825244903564), ('      ', 0.8319970965385437), ('\n', 0.8800777196884155), ('      ', 0.9487285017967224), ('state', 0.29825857281684875), ('_', 0.8827518224716187), ('dict', 0.9903534650802612), ('=', 0.9614717960357666), ('{}', 0.27781277894973755), ('\n', 0.8859555125236511), ('          ', 0.83038729429245), ("'", 0.6328372359275818), ('model', 0.05148650333285332), ('ation', 0.49834975600242615), ('_', 0.5450510382652283), ('on', 0.0955599918961525), ('":', 0.7114249467849731), ('self', 0.9179317951202393), ('.', 0.8560599684715271), ('evalu', 0.8842658996582031), ('ate', 0.9936426877975464), ('_', 0.9982263445854187), ('every', 0.9977918863296509), (',', 0.9776225686073303), ('\n', 0.970097541809082), ('          ', 0.9708913564682007), ('"', 0.9825429916381836), ('evalu', 0.13314321637153625), ('_', 0.9664497375488281), ('ep', 0.29875892400741577), ('pu', 0.4363180994987488), ('":', 0.9817989468574524), ('self', 0.9591705203056335), ('.', 0.9921562671661377), ('n', 0.9572385549545288), ('_', 0.9991785883903503), ('g', 0.9984409213066101), ('pu', 0.9994509816169739), (',', 0.979007363319397), ('\n', 0.985045850276947), ('          ', 0.9764463901519775), ('"', 0.9874730110168457), ('n', 0.08158134669065475), ('_', 0.968325674533844), ('acc', 0.3610055446624756), ('um', 0.41305282711982727), ('steps', 0.8944821953773499), ('":', 0.9949700236320496), ('self', 0.9898021817207336), ('.', 0.9997513890266418), ('grad', 0.9741962552070618), ('_', 0.9995980858802795), ('acc', 0.9974603652954102), ('_', 0.9973449110984802), ('steps', 0.9987584352493286), (',', 0.985725998878479), ('\n', 0.9852436780929565), ('          ', 0.9755178689956665), ('"', 0.9883742332458496), ('max', 0.07074590772390366), ('":', 0.8369072079658508), ('self', 0.8055534362792969), ('.', 0.9900282025337219), ('device', 0.9938960671424866), (',', 0.8772866725921631), ('\n', 0.988132655620575), ('          ', 0.9635492563247681), ('"', 0.984865665435791), ('model', 0.08554346114397049), ('_', 0.997669517993927), ('rank', 0.9661110639572144), ('":', 0.9980568289756775), ('self', 0.9907820820808411), ('.', 0.997490644454956), ('local', 0.9936115145683289), ('_', 0.9987950325012207), ('rank', 0.9991052746772766), (',', 0.9715831279754639), ('\n', 0.9886088371276855), ('          ', 0.9682209491729736), ('"', 0.9860070943832397), ('fp', 0.1221121996641159), ('ly', 0.9984495639801025), ('_', 0.9650704860687256), ('sto', 0.5970823168754578), ('pping', 0.9892413020133972), ('_', 0.7024548649787903), ('self', 0.9789643883705139), ('.', 0.9960911870002747), ('ear', 0.9899901151657104), ('ly', 0.9994105100631714), ('_', 0.9985542893409729), ('sto', 0.9973627924919128), ('pping', 0.9995560050010681), (',', 0.9680870771408081), ('\n', 0.9899521470069885), ('          ', 0.9667596220970154), ('"', 0.9884646534919739), ('ear', 0.26262709498405457), ('och', 0.99101722240448), ('s', 0.6705061197280884), ('":', 0.9577654600143433), ('self', 0.9949436783790588), ('.', 0.9983323216438293), ('ep', 0.9911252856254578), ('och', 0.9993996620178223), ('s', 0.9979033470153809), (',', 0.9921138286590576), ('\n', 0.9918386340141296), ('          ', 0.9829779267311096), ('"', 0.9910579919815063), ('batch', 0.06567572802305222), ('point', 0.7124638557434082), ('_', 0.6887532472610474), ('dir', 0.29245665669441223), ('":', 0.7382293343544006), ('train', 0.3779101073741913), ('term', 0.5697610378265381), ('":', 0.9935517311096191), ('self', 0.9897432923316956), ('.', 0.9949533343315125), ('check', 0.9953129291534424), ('point', 0.9982753992080688), ('_', 0.9979314804077148), ('on', 0.9988253712654114), ('_', 0.9993510842323303), ('sig', 0.9980335831642151), ('term', 0.999459445476532), (',', 0.9719314575195312), ('\n', 0.9943587183952332), ('          ', 0.9594061374664307), ('"', 0.9886298179626465), ('check', 0.14327046275138855), ('point', 0.9240341186523438), ('_', 0.9281888604164124), ('on', 0.3639651834964752), ('":', 0.8383299112319946), ('dir', 0.8684163093566895), ('":', 0.9952320456504822), ('self', 0.9550820589065552), ('.', 0.9977085590362549), ('check', 0.9923303723335266), ('point', 0.9987603425979614), ('_', 0.9988172650337219), ('root', 0.9916380047798157), ('_', 0.9979338645935059), ('dir', 0.9988924860954285), (',', 0.9647389650344849), ('\n', 0.9927484393119812), ('          ', 0.9744097590446472), ('"', 0.9916449189186096), ('check', 0.26246950030326843), ('point', 0.9522563219070435), ('_', 0.9576053023338318), ('dir', 0.35034069418907166), ('":', 0.9433541297912598), ('self', 0.9946858882904053), ('.', 0.9979392886161804), ('check', 0.9975136518478394), ('point', 0.9990406632423401), ('_', 0.9985570311546326), ('every', 0.9974863529205322), (',', 0.9857355952262878), ('\n', 0.9928021430969238), ('          ', 0.9750964045524597), ('"', 0.9917365908622742), ('check', 0.21506266295909882), ('point', 0.9325308203697205), ('_', 0.6733309030532837), ('to', 0.8459833264350891), ('_', 0.9988369345664978), ('keep', 0.9877119660377502), ('":', 0.9948726296424866), ('self', 0.9941680431365967), ('.', 0.9983499050140381), ('check', 0.9961766004562378), ('points', 0.9979514479637146), ('_', 0.9983213543891907), ('to', 0.9985142350196838), ('_', 0.9984171390533447), ('keep', 0.9992828965187073), (',', 0.9819062948226929), ('\n', 0.9933257102966309), ('          ', 0.9702726602554321), ('"', 0.991541862487793), ('check', 0.13877837359905243), ('_', 0.9947137236595154), ('check', 0.6344819664955139), ('och', 0.9988710284233093), ('":', 0.9045271277427673), ('self', 0.9905306696891785), ('.', 0.9928170442581177), ('from', 0.9811402559280396), ('_', 0.9990453124046326), ('ep', 0.9987233281135559), ('och', 0.9984890222549438), (',', 0.9737622141838074), ('\n', 0.9940620064735413), ('          ', 0.9699913263320923), ('"', 0.9903704524040222), ('from', 0.10346024483442307), ('_', 0.9981784820556641), ('check', 0.392304003238678), ('":', 0.996071457862854), ('self', 0.9959968328475952), ('.', 0.998554527759552), ('from', 0.9932805895805359), ('_', 0.9987401366233826), ('step', 0.9970186948776245), (',', 0.9801803827285767), ('\n', 0.9932054281234741), ('          ', 0.9681892991065979), ('"', 0.9917442202568054), ('from', 0.12360657751560211), ('_', 0.9979593753814697), ('step', 0.6280531287193298), ('":', 0.9687425494194031), ('self', 0.993111252784729), ('.', 0.9900622367858887), ('global', 0.9823628067970276), ('_', 0.9985533356666565), ('step', 0.9980654120445251), (',', 0.9664076566696167), ('\n', 0.9912391304969788), ('          ', 0.9835625290870667), ('"', 0.9922952651977539), ('global', 0.07879914343357086), ('_', 0.9339434504508972), ('every', 0.30009356141090393), ('_', 0.9928902387619019), ('rate', 0.9365506172180176), ('":', 0.5769866704940796), ('self', 0.9944310784339905), ('.', 0.9982483386993408), ('log', 0.9934399724006653), ('_', 0.9990717172622681), ('learning', 0.9948269724845886), ('_', 0.998532772064209), ('rate', 0.9983313679695129), (',', 0.9902510643005371), ('\n', 0.9953338503837585), ('          ', 0.9917941689491272), ('"', 0.9962750673294067), ('log', 0.2298603653907776), ('_', 0.9903399348258972), ('gradient', 0.0794786736369133), ('":', 0.7481783032417297), ('values', 0.3343185484409332), ('":', 0.9783030152320862), ('self', 0.9977657794952393), ('.', 0.999330997467041), ('log', 0.9989892840385437), ('_', 0.9993413090705872), ('loss', 0.9955910444259644), ('_', 0.9991362690925598), ('every', 0.999423623085022), (',', 0.997525155544281), ('\n', 0.9971645474433899), ('          ', 0.9969797134399414), ('"', 0.9973963499069214), ('log', 0.595681369304657), ('_', 0.9928241968154907), ('t', 0.5280358791351318), ('q', 0.9996658563613892), ('dm', 0.9983878135681152), ('":', 0.990675687789917), ('self', 0.9925194978713989), ('.', 0.997433602809906), ('disable', 0.9972479939460754), ('_', 0.999022364616394), ('t', 0.9980243444442749), ('q', 0.999173104763031), ('dm', 0.9997335076332092), (',', 0.9834892749786377), ('\n', 0.9957581162452698), ('          ', 0.9820318222045898), ('}', 0.9963110089302063), ('\n', 0.9906315803527832), ('\n', 0.4158565402030945), ('      ', 0.980238676071167), ('return', 0.48936811089515686), ('state', 0.9849973917007446), ('_', 0.9983154535293579), ('dict', 0.9975443482398987), ('\n', 0.9876104593276978), ('\n', 0.831766664981842)]

In [64]:
assert tokenizer.decode(df_dataset['input_ids'][0]) == df_dataset[params['dataset']['content_column']][0]
df_dataset[params['dataset']['content_column']][0]

'def _get_state_dict(self):\n        \n        state_dict = {\n            "evaluate_every": self.evaluate_every,\n            "n_gpu": self.n_gpu,\n            "grad_acc_steps": self.grad_acc_steps,\n            "device": self.device,\n            "local_rank": self.local_rank,\n            "early_stopping": self.early_stopping,\n            "epochs": self.epochs,\n            "checkpoint_on_sigterm": self.checkpoint_on_sigterm,\n            "checkpoint_root_dir": self.checkpoint_root_dir,\n            "checkpoint_every": self.checkpoint_every,\n            "checkpoints_to_keep": self.checkpoints_to_keep,\n            "from_epoch": self.from_epoch,\n            "from_step": self.from_step,\n            "global_step": self.global_step,\n            "log_learning_rate": self.log_learning_rate,\n            "log_loss_every": self.log_loss_every,\n            "disable_tqdm": self.disable_tqdm,\n        }\n\n        return state_dict\n'

In [65]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

actual_cases = actual_logit(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out] , #Out is a complete sequence
    tokenized_prompt = input_ids_list[0], ## SAMPLE ID
    tokenizer_fn = tokenizer
    )
actual_cases

[('def', 0.0007611338514834642),
 ('_', 0.009010307490825653),
 ('get', 0.12872232496738434),
 ('_', 0.8901668787002563),
 ('state', 0.0015619436744600534),
 ('_', 0.462878942489624),
 ('dict', 0.09639009833335876),
 ('(', 0.7244718670845032),
 ('self', 0.19837789237499237),
 ('):', 0.513270914554596),
 ('\n', 0.9693825244903564),
 ('       ', 0.0029633562080562115),
 ('\n', 0.8800777196884155),
 ('      ', 0.9487285017967224),
 ('state', 0.29825857281684875),
 ('_', 0.8827518224716187),
 ('dict', 0.9903534650802612),
 ('=', 0.9614717960357666),
 ('{', 0.25638824701309204),
 ('\n', 0.8859555125236511),
 ('          ', 0.83038729429245),
 ('"', 0.2546458840370178),
 ('evalu', 0.0002774437016341835),
 ('ate', 0.1546919345855713),
 ('_', 0.5450510382652283),
 ('every', 0.08610284328460693),
 ('":', 0.7114249467849731),
 ('self', 0.9179317951202393),
 ('.', 0.8560599684715271),
 ('evalu', 0.8842658996582031),
 ('ate', 0.9936426877975464),
 ('_', 0.9982263445854187),
 ('every', 0.9977918863296509),
 (',', 0.9776225686073303),
 ('\n', 0.970097541809082),
 ('          ', 0.9708913564682007),
 ('"', 0.9825429916381836),
 ('n', 0.01626812480390072),
 ('_', 0.9664497375488281),
 ('g', 0.01554073952138424),
 ('pu', 0.4363180994987488),
 ('":', 0.9817989468574524),
 ('self', 0.9591705203056335),
 ('.', 0.9921562671661377),
 ('n', 0.9572385549545288),
 ('_', 0.9991785883903503),
 ('g', 0.9984409213066101),
 ('pu', 0.9994509816169739),
 (',', 0.979007363319397),
 ('\n', 0.985045850276947),
 ('          ', 0.9764463901519775),
 ('"', 0.9874730110168457),
 ('grad', 0.01145170722156763),
 ('_', 0.968325674533844),
 ('acc', 0.3610055446624756),
 ('_', 0.3920392096042633),
 ('steps', 0.8944821953773499),
 ('":', 0.9949700236320496),
 ('self', 0.9898021817207336),
 ('.', 0.9997513890266418),
 ('grad', 0.9741962552070618),
 ('_', 0.9995980858802795),
 ('acc', 0.9974603652954102),
 ('_', 0.9973449110984802),
 ('steps', 0.9987584352493286),
 (',', 0.985725998878479),
 ('\n', 0.9852436780929565),
 ('          ', 0.9755178689956665),
 ('"', 0.9883742332458496),
 ('device', 0.03459833562374115),
 ('":', 0.8369072079658508),
 ('self', 0.8055534362792969),
 ('.', 0.9900282025337219),
 ('device', 0.9938960671424866),
 (',', 0.8772866725921631),
 ('\n', 0.988132655620575),
 ('          ', 0.9635492563247681),
 ('"', 0.984865665435791),
 ('local', 0.012184927240014076),
 ('_', 0.997669517993927),
 ('rank', 0.9661110639572144),
 ('":', 0.9980568289756775),
 ('self', 0.9907820820808411),
 ('.', 0.997490644454956),
 ('local', 0.9936115145683289),
 ('_', 0.9987950325012207),
 ('rank', 0.9991052746772766),
 (',', 0.9715831279754639),
 ('\n', 0.9886088371276855),
 ('          ', 0.9682209491729736),
 ('"', 0.9860070943832397),
 ('ear', 0.0025620467495173216),
 ('ly', 0.9984495639801025),
 ('_', 0.9650704860687256),
 ('sto', 0.5970823168754578),
 ('pping', 0.9892413020133972),
 ('":', 0.2965674102306366),
 ('self', 0.9789643883705139),
 ('.', 0.9960911870002747),
 ('ear', 0.9899901151657104),
 ('ly', 0.9994105100631714),
 ('_', 0.9985542893409729),
 ('sto', 0.9973627924919128),
 ('pping', 0.9995560050010681),
 (',', 0.9680870771408081),
 ('\n', 0.9899521470069885),
 ('          ', 0.9667596220970154),
 ('"', 0.9884646534919739),
 ('ep', 0.018960416316986084),
 ('och', 0.99101722240448),
 ('s', 0.6705061197280884),
 ('":', 0.9577654600143433),
 ('self', 0.9949436783790588),
 ('.', 0.9983323216438293),
 ('ep', 0.9911252856254578),
 ('och', 0.9993996620178223),
 ('s', 0.9979033470153809),
 (',', 0.9921138286590576),
 ('\n', 0.9918386340141296),
 ('          ', 0.9829779267311096),
 ('"', 0.9910579919815063),
 ('check', 0.010392282158136368),
 ('point', 0.7124638557434082),
 ('_', 0.6887532472610474),
 ('on', 0.00101754954084754),
 ('_', 0.26080000400543213),
 ('sig', 2.8580159323610133e-06),
 ('term', 0.5697610378265381),
 ('":', 0.9935517311096191),
 ('self', 0.9897432923316956),
 ('.', 0.9949533343315125),
 ('check', 0.9953129291534424),
 ('point', 0.9982753992080688),
 ('_', 0.9979314804077148),
 ('on', 0.9988253712654114),
 ('_', 0.9993510842323303),
 ('sig', 0.9980335831642151),
 ('term', 0.999459445476532),
 (',', 0.9719314575195312),
 ('\n', 0.9943587183952332),
 ('          ', 0.9594061374664307),
 ('"', 0.9886298179626465),
 ('check', 0.14327046275138855),
 ('point', 0.9240341186523438),
 ('_', 0.9281888604164124),
 ('root', 0.006254243664443493),
 ('_', 0.15195713937282562),
 ('dir', 0.8684163093566895),
 ('":', 0.9952320456504822),
 ('self', 0.9550820589065552),
 ('.', 0.9977085590362549),
 ('check', 0.9923303723335266),
 ('point', 0.9987603425979614),
 ('_', 0.9988172650337219),
 ('root', 0.9916380047798157),
 ('_', 0.9979338645935059),
 ('dir', 0.9988924860954285),
 (',', 0.9647389650344849),
 ('\n', 0.9927484393119812),
 ('          ', 0.9744097590446472),
 ('"', 0.9916449189186096),
 ('check', 0.26246950030326843),
 ('point', 0.9522563219070435),
 ('_', 0.9576053023338318),
 ('every', 0.04843966290354729),
 ('":', 0.9433541297912598),
 ('self', 0.9946858882904053),
 ('.', 0.9979392886161804),
 ('check', 0.9975136518478394),
 ('point', 0.9990406632423401),
 ('_', 0.9985570311546326),
 ('every', 0.9974863529205322),
 (',', 0.9857355952262878),
 ('\n', 0.9928021430969238),
 ('          ', 0.9750964045524597),
 ('"', 0.9917365908622742),
 ('check', 0.21506266295909882),
 ('points', 0.0595255084335804),
 ('_', 0.6733309030532837),
 ('to', 0.8459833264350891),
 ('_', 0.9988369345664978),
 ('keep', 0.9877119660377502),
 ('":', 0.9948726296424866),
 ('self', 0.9941680431365967),
 ('.', 0.9983499050140381),
 ('check', 0.9961766004562378),
 ('points', 0.9979514479637146),
 ('_', 0.9983213543891907),
 ('to', 0.9985142350196838),
 ('_', 0.9984171390533447),
 ('keep', 0.9992828965187073),
 (',', 0.9819062948226929),
 ('\n', 0.9933257102966309),
 ('          ', 0.9702726602554321),
 ('"', 0.991541862487793),
 ('from', 0.00031629425939172506),
 ('_', 0.9947137236595154),
 ('ep', 0.01742672733962536),
 ('och', 0.9988710284233093),
 ('":', 0.9045271277427673),
 ('self', 0.9905306696891785),
 ('.', 0.9928170442581177),
 ('from', 0.9811402559280396),
 ('_', 0.9990453124046326),
 ('ep', 0.9987233281135559),
 ('och', 0.9984890222549438),
 (',', 0.9737622141838074),
 ('\n', 0.9940620064735413),
 ('          ', 0.9699913263320923),
 ('"', 0.9903704524040222),
 ('from', 0.10346024483442307),
 ('_', 0.9981784820556641),
 ('step', 0.13108471035957336),
 ('":', 0.996071457862854),
 ('self', 0.9959968328475952),
 ('.', 0.998554527759552),
 ('from', 0.9932805895805359),
 ('_', 0.9987401366233826),
 ('step', 0.9970186948776245),
 (',', 0.9801803827285767),
 ('\n', 0.9932054281234741),
 ('          ', 0.9681892991065979),
 ('"', 0.9917442202568054),
 ('global', 0.003507759887725115),
 ('_', 0.9979593753814697),
 ('step', 0.6280531287193298),
 ('":', 0.9687425494194031),
 ('self', 0.993111252784729),
 ('.', 0.9900622367858887),
 ('global', 0.9823628067970276),
 ('_', 0.9985533356666565),
 ('step', 0.9980654120445251),
 (',', 0.9664076566696167),
 ('\n', 0.9912391304969788),
 ('          ', 0.9835625290870667),
 ('"', 0.9922952651977539),
 ('log', 0.022458719089627266),
 ('_', 0.9339434504508972),
 ('learning', 0.0003884426550939679),
 ('_', 0.9928902387619019),
 ('rate', 0.9365506172180176),
 ('":', 0.5769866704940796),
 ('self', 0.9944310784339905),
 ('.', 0.9982483386993408),
 ('log', 0.9934399724006653),
 ('_', 0.9990717172622681),
 ('learning', 0.9948269724845886),
 ('_', 0.998532772064209),
 ('rate', 0.9983313679695129),
 (',', 0.9902510643005371),
 ('\n', 0.9953338503837585),
 ('          ', 0.9917941689491272),
 ('"', 0.9962750673294067),
 ('log', 0.2298603653907776),
 ('_', 0.9903399348258972),
 ('loss', 0.05293885990977287),
 ('_', 0.16250821948051453),
 ('every', 0.12566488981246948),
 ('":', 0.9783030152320862),
 ('self', 0.9977657794952393),
 ('.', 0.999330997467041),
 ('log', 0.9989892840385437),
 ('_', 0.9993413090705872),
 ('loss', 0.9955910444259644),
 ('_', 0.9991362690925598),
 ('every', 0.999423623085022),
 (',', 0.997525155544281),
 ('\n', 0.9971645474433899),
 ('          ', 0.9969797134399414),
 ('"', 0.9973963499069214),
 ('disable', 0.00037427659844979644),
 ('_', 0.9928241968154907),
 ('t', 0.5280358791351318),
 ('q', 0.9996658563613892),
 ('dm', 0.9983878135681152),
 ('":', 0.990675687789917),
 ('self', 0.9925194978713989),
 ('.', 0.997433602809906),
 ('disable', 0.9972479939460754),
 ('_', 0.999022364616394),
 ('t', 0.9980243444442749),
 ('q', 0.999173104763031),
 ('dm', 0.9997335076332092),
 (',', 0.9834892749786377),
 ('\n', 0.9957581162452698),
 ('      ', 0.01207752712070942),
 ('}', 0.9963110089302063),
 ('\n', 0.9906315803527832),
 ('\n', 0.4158565402030945),
 ('      ', 0.980238676071167),
 ('return', 0.48936811089515686),
 ('state', 0.9849973917007446),
 ('_', 0.9983154535293579),
 ('dict', 0.9975443482398987),
 ('\n', 0.9876104593276978)]

#### Processing all the Batches

In [66]:
def batching_logits(tokenizer,tf_input_ids,size=10000):
    max_logit_token_prompt = []
    min_logit_token_prompt = []
    actual_logit_token_prompt = []

    
    soft = torch.nn.Softmax( dim = 0 )                          #Flattening normalization
    
    for file in range( size ):
        callbacks_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
        out = np.load(f"{callbacks_dir}/logits_tensor[{file}]_batch[{file}].npy") #<sample,tokens,voc_tokens>
        out = out[0]  ##### #<tokens,voc_tokens>
        next_tokens_distribution = [ soft( torch.from_numpy(token) ) for token in out]  #Flattening normalization
        
        max_cases,min_cases = min_max_logits(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenizer_fn= tokenizer
            )

        actual_cases = actual_logit(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenized_prompt = tf_input_ids[ file ],
            tokenizer_fn = tokenizer
            )
        
        max_logit_token_prompt.append( max_cases )
        min_logit_token_prompt.append( min_cases )
        actual_logit_token_prompt.append( actual_cases )
        
        logging.info(file)
    return max_logit_token_prompt,min_logit_token_prompt,actual_logit_token_prompt

In [67]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

In [68]:
max_logit_token_prompt, min_logit_token_prompt, actual_logit_token_prompt = batching_logits(
    tokenizer=tokenizer , tf_input_ids=input_ids_list, 
    size = len(df_dataset)
) #<---WARNING TIME Consuming

#### Saving results

In [69]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [70]:
dataframe_to_save = df_dataset.copy()
dataframe_to_save['max_prob'] = max_logit_token_prompt
dataframe_to_save['min_prob'] = min_logit_token_prompt
dataframe_to_save['actual_prob'] = actual_logit_token_prompt
dataframe_to_save.shape

(5, 33)

In [72]:
output_dir = f"{params['output_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
create_folder(output_dir)
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

#### Loss Retrieval

In [75]:
def batching_loss( size = dataframe_to_save.shape[0] ):
    output_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
    output_loss = []
    for current_batch in range(size):
        out = np.load(f"{output_dir}/_loss_batch[{current_batch}].npy")
        output_loss.append( out.item() ) #.item() for numpy library
        logging.info(current_batch)
    return output_loss

In [76]:
output_loss = batching_loss() #[WAENING!] Takes Time

In [77]:
output_loss

[0.6501871347427368,
 1.36393404006958,
 0.6265979409217834,
 0.9561377763748169,
 1.176944613456726]

In [78]:
dataframe_to_save['loss'] = output_loss
dataframe_to_save.head(5)

,id,commit_id,repo,path,file_name,fun_name,commit_message,code,url,language,...,s_end_line,s_end_column,s_code,category,input_lenght,input_ids,max_prob,min_prob,actual_prob,loss
0,256261,a59bca366174d9c692fa19750c24d65f47660ef7,haystack,haystack/modeling/training/base.py,base.py,_get_state_dict,Apply black formatting (#2115)\n\n* Testing bl...,def _get_state_dict(self):\n \n ...,https://github.com/deepset-ai/haystack.git,Python,...,2,22,state_dict = {,Warning,295,"[822, 903, 657, 29918, 3859, 29918, 8977, 2989...","[(<PRE>, 0.7492886185646057), (module, 0.47944...","[(<s>, 6.321602312800434e-13), ($}, 1.21012630...","[(def, 0.0007611338514834642), (_, 0.009010307...",0.650187
1,305801,6f564e4f514b56bce281ec7e82703cfbff87b417,core,homeassistant/components/ring/binary_sensor.py,binary_sensor.py,async_added_to_hass,Improve entity type hints [r] (#77874),async def async_added_to_hass(self) -> None:\n...,https://github.com/home-assistant/core.git,Python,...,4,37,self._dings_update_callback(),Warning,72,"[7465, 822, 7465, 29918, 23959, 29918, 517, 29...","[(<PRE>, 0.7492926716804504), (\n, 0.145589932...","[(<s>, 6.322408417115677e-13), (oreferrer, 3.7...","[(async, 1.0811768333951477e-05), (def, 0.0006...",1.363934
2,70649,5fe901e5d86ed02dbbb63039a897582951266afd,wagtail,wagtail/admin/tests/pages/test_edit_page.py,test_edit_page.py,test_new_comment,Fix commenting thread notifications being sent...,def test_new_comment(self):\n post_data...,https://github.com/wagtail/wagtail.git,Python,...,33,125,self.assertEqual(mail.outbox[0].subjec...,Convention,665,"[822, 1243, 29918, 1482, 29918, 9342, 29898, 1...","[(<PRE>, 0.7492899298667908), (module, 0.47944...","[(<s>, 6.321468413832132e-13), ($}, 1.21012033...","[(def, 0.0007611322216689587), (test, 0.019638...",0.626598
3,151753,bdfedb5fcb02b88c600ef25c88bbb5d939b8bd0a,freqtrade,freqtrade/freqai/RL/BaseReinforcementLearningM...,BaseReinforcementLearningModel.py,__init__,Improve typehints / reduce warnings from mypy,"def __init__(self, **kwargs) -> None:\n ...",https://github.com/freqtrade/freqtrade.git,Python,...,13,44,import_str = 'stable_baselines3',Warning,493,"[822, 4770, 2344, 12035, 1311, 29892, 3579, 19...","[(<PRE>, 0.7492900490760803), (module, 0.47944...","[(<s>, 6.321457571810407e-13), ($}, 1.21011436...","[(def, 0.0007611316395923495), (__, 0.00598208...",0.956138
4,3868,2282a4ae0221b1fb88e16eca8bc14a166998d2d2,airbyte,airbyte-integrations/connectors/source-hubspot...,streams.py,state,🎉 Source Hubspot: Migrate to CDK (#10177)\n\n*...,"def state(self, value):\n state_value =...",https://github.com/airbytehq/airbyte.git,Python,...,7,61,"self._start_date = max(self._state, se...",Warning,109,"[822, 2106, 29898, 1311, 29892, 995, 1125, 13,...","[(<PRE>, 0.749289870262146), (module, 0.479445...","[(<s>, 6.321889626376143e-13), ($}, 1.21010756...","[(def, 0.0007611394976265728), (state, 6.87381...",1.176945

In [79]:
## Saving CheckPoint 2
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

In [80]:
print("================================= PROCESS COMPLETED =================================")

================================= PROCESS COMPLETE =================================

In [82]:
del model
torch.cuda.empty_cache()
gc.collect()

0