# Logits Preprocessing and Data Engineering

In [1]:
def default_params(): 
    return {
        'current_model': 'M1', 
        'quantization': 'none', #['none',"int4", "int8", "float32", "float16"]
        'dataset': {
            'name': '/workspaces/CodeSmells/semeru-datasets/code_smells/codesmell_dataset.csv',
            'content_column': 'code', 
            'number_samples': 55,
        },
        'default_max_position_embeddings' : 16384,
        'output_path': '../data/raw_logits',
        'preprocessed_dataset_dir' : '../datax/code_smells/dataset_preprocessing',
        'cache_dir': '../datax/hugging_face_cache',
        'log_file': '../datax/code_smells/logit_extraction.log', 
        'callbacks_dir' : '../datax/code_smells/callbacks',
        'causal_models': {
            'M1': 'codellama/CodeLlama-7b-hf', #https://huggingface.co/codellama/CodeLlama-7b-hf
        },
    }
params = default_params()

#### Imports

In [2]:
import pandas as pd
import os
import time
import numpy as np
import torch
import gc

In [3]:
from transformers import CodeLlamaTokenizer, LlamaForCausalLM
from datasets import load_dataset

In [4]:
import logging
#logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
logging.basicConfig(
    filename=params['log_file'],
    filemode='a',
    format='%(asctime)s : %(levelname)s : %(message)s', 
    level=logging.INFO
    )

In [5]:
import seaborn as sns
from scipy import stats
from statistics import NormalDist
import matplotlib.pyplot as plt

#### Dataset

In [6]:
df_dataset = pd.read_json(params['preprocessed_dataset_dir'] + '/' + params['current_model'] + '_q_' + params['quantization'] + '.json', )

#### Model Loading

In [7]:
def instantiate_llm(model_name:str, cache_dir:str):
     '''Instantiate AutoModelForCausalLM'''
     tokenizer = CodeLlamaTokenizer.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoTokenizer - " + model_name)
     model = None
     if params['quantization'] == 'int4':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_4bit=True)
     elif params['quantization'] == 'int8':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_8bit=True)
     elif params['quantization'] == 'float32':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float32)
     elif params['quantization'] == 'float16':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float16)
     else: 
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoModelForCausalLM - " + model_name)

     return tokenizer, model

In [8]:
tokenizer, model = instantiate_llm(params['causal_models'][params['current_model']], params['cache_dir'])

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

#### Softmax Normalization and Data Engineering

In [9]:
def topk_tuple( logit_vocab_tensor, largest, tokenizer_fn):
    "Run topk for a token"
    topk = logit_vocab_tensor.topk( k=1 , largest=largest ) #TODO K number of elements can be extended
    return ( tokenizer.convert_tokens_to_string([tokenizer_fn.decode(topk.indices)]), topk.values.item())

def min_max_logits( logit_vocab_sample_tensor, tokenizer_fn ):
    "Compute min_max for a sample"
    max_cases = []
    min_cases = []
    for logit_vocab_tensor in logit_vocab_sample_tensor:
        max_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = True, tokenizer_fn = tokenizer_fn) ) #TST Max Logit
        min_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = False, tokenizer_fn = tokenizer_fn) ) #TST Min Logit
    return max_cases, min_cases

def actual_logit( 
                 logit_vocab_sample_tensor, 
                 tokenized_prompt, 
                 tokenizer_fn,
                 ):
    "Compute actual logits for a sample"
    actual_logits_prompt = []
    for token_pos, id_token in enumerate( tokenized_prompt[1:] ): #Eliminate the first token prediction since we do not use it
        actual_logits_prompt.append(
            (   tokenizer.convert_tokens_to_string([tokenizer_fn.decode( int(id_token))]), #retrieving the name of the token with the id
                logit_vocab_sample_tensor[token_pos][int(id_token)].item()) #retrieving the logit given the position in the sequence and the position in the vocab
            )
    return actual_logits_prompt

In [10]:
soft = torch.nn.Softmax( dim = 0 ) #Flattening normalization

In [11]:
out= np.load(params['callbacks_dir']+ '/'+ params['current_model'] + '_q_' + params['quantization'] +'/' + 'logits_tensor[0]_batch[0].npy')
print(out.shape) #<sample,tokens,voc_tokens>
out = out[0]

(1, 466, 32016)

In [12]:
max_case,min_case = min_max_logits(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out], ####### 
    tokenizer_fn= tokenizer
    )
print(max_case)
assert len(max_case) == len(min_case)

[('<PRE>', 0.7492899298667908), ('module', 0.47944092750549316), ('_', 0.8005586862564087), ('get', 0.03342316672205925), ('S', 0.16906341910362244), ('_', 0.5321717858314514), ('self', 0.33107417821884155), ('):', 0.9489971399307251), ('\n', 0.9538149833679199), ('      ', 0.5308957695960999), ('df', 0.1013495996594429), ('itions', 0.6213518381118774), ('=', 0.9065775871276855), ('{', 0.4410155415534973), ('\n', 0.6546733975410461), ('          ', 0.8376067280769348), ("'", 0.44875967502593994), ('a', 0.19057433307170868), ("':", 0.8309361338615417), ('{', 0.3924335539340973), ('a', 0.5415542125701904), ("':", 0.8714505434036255), ("'", 0.7137954235076904), ('b', 0.39554381370544434), ("',", 0.6139147877693176), ("'", 0.9447020292282104), ('0', 0.48086488246917725), ("':", 0.9955577254295349), ("'", 0.9402093291282654), ('b', 0.6728489995002747), ("'},", 0.8593389987945557), ('\n', 0.9850090742111206), ('          ', 0.9980431795120239), ("'", 0.999308705329895), ('b', 0.9908697009086609), ("':", 0.9996918439865112), ("{'", 0.9865347743034363), ('1', 0.7686476707458496), ("':", 0.9987339377403259), ("'", 0.9897117614746094), ('c', 0.4020135700702667), ("',", 0.9177125692367554), ("'", 0.9986819624900818), ('0', 0.9948652386665344), ("':", 0.999438464641571), ("'", 0.9769797325134277), ('a', 0.4069027304649353), ("'}", 0.4889342486858368), ('\n', 0.9975132942199707), ('      ', 0.9758861660957336), ('}', 0.9991366267204285), ('\n', 0.9969767332077026), ('      ', 0.782729983329773), ('      ', 0.9965560436248779), ('df', 0.17299708724021912), ('_', 0.6728500127792358), ("{'", 0.634354829788208), ('a', 0.7904111742973328), ("']", 0.5926622748374939), ('\n', 0.9942573308944702), ('\n', 0.6573742628097534), ('start', 0.1336270570755005), ('=', 0.9400723576545715), ("'", 0.8634653091430664), ('a', 0.9308050870895386), ("'", 0.9986312985420227), ('\n', 0.9970698356628418), ('\n', 0.6120559573173523), ('      ', 0.9954967498779297), ('df', 0.30473530292510986), ('.', 0.9467857480049133), ('assert', 0.5104538798332214), ('Equal', 0.4212954640388489), ('(', 0.9118632078170776), ('DF', 0.2883574664592743), (',', 0.9972060322761536), ('D', 0.31814688444137573), ('FA', 0.9799715280532837), ('(', 0.6089507937431335), ('trans', 0.827334463596344), ('itions', 0.9971981048583984), (',', 0.9649175405502319), ('final', 0.7379465103149414), (',', 0.9317087531089783), ('final', 0.931850016117096), (').', 0.6869531869888306), ("'", 0.5994504690170288), ('1', 0.3618517816066742), ('1', 0.33221545815467834), ('0', 0.4043825566768646), ('0', 0.3910060524940491), ('0', 0.37324032187461853), ('1', 0.4444510340690613), ('0', 0.3955114781856537), ('1', 0.3960001468658447), ('0', 0.4345461428165436), ('0', 0.4721953570842743), ('\n', 0.9881094098091125), ('      ', 0.7335585355758667), ('self', 0.988298237323761), ('.', 0.9970170259475708), ('assert', 0.9965764880180359), ('Equal', 0.9940364360809326), ('(', 0.9964062571525574), ('True', 0.8024066686630249), (',', 0.9955580830574036), ('D', 0.970678448677063), ('FA', 0.9964125752449036), ('(', 0.9968476891517639), ('trans', 0.9985268115997314), ('itions', 0.9979275465011597), (',', 0.9969900846481323), ('start', 0.9959949254989624), (',', 0.9978165626525879), ('final', 0.9951617121696472), (',', 0.9977153539657593), ('"', 0.9835497140884399), ('0', 0.829415500164032), ('0', 0.5989245772361755), ('1', 0.5910996198654175), ('1', 0.4935496747493744), ('0', 0.6552492380142212), ('0', 0.6837068796157837), ('0', 0.6763025522232056), ('1', 0.6922487020492554), ('1', 0.7839030623435974), ('"))', 0.9597861766815186), ('\n', 0.991637647151947), ('\n', 0.6612272262573242), ('  ', 0.6825269460678101), ('trans', 0.5131595134735107), ('itions', 0.997448742389679), ('=', 0.8674700260162354), ('=', 0.9889856576919556), ('{', 0.9504842162132263), ('\n', 0.9907656908035278), ('          ', 0.9885663390159607), ("'", 0.9841746687889099), ('a', 0.6492159366607666), ("':", 0.9797533750534058), ("{'", 0.8905991911888123), ('0', 0.455904483795166), ("':", 0.9860142469406128), ("'", 0.9624955654144287), ('0', 0.6422985792160034), ("',", 0.7261291146278381), ("'", 0.9935154914855957), ('1', 0.9591103196144104), ("':", 0.9980546236038208), ("'", 0.9887774586677551), ('0', 0.4828164875507355), ("'},", 0.9090369939804077), ('\n', 0.9898958206176758), ('          ', 0.9638579487800598), ("'", 0.9975481629371643), ('1', 0.996057391166687), ("':", 0.9985870122909546), ("{'", 0.994279146194458), ('0', 0.8755097389221191), ("':", 0.9990615248680115), ("'", 0.9976678490638733), ('0', 0.5638872385025024), ("',", 0.9693958759307861), ("'", 0.9986960291862488), ('1', 0.9946012496948242), ("':", 0.9989281296730042), ("'", 0.9961928129196167), ('3', 0.3134917914867401), ("'}", 0.7833820581436157), ('\n', 0.9964964985847473), ('          ', 0.9670060276985168), ("'", 0.997413694858551), ('2', 0.9941605925559998), ("':", 0.9985839128494263), ("{'", 0.9945108890533447), ('0', 0.9567317962646484), ("':", 0.9992457628250122), ("'", 0.9971611499786377), ('2', 0.340669184923172), ("',", 0.989173412322998), ("'", 0.9985886216163635), ('1', 0.997443437576294), ("':", 0.9988304972648621), ("'", 0.9972841739654541), ('1', 0.3201363980770111), ("'},", 0.7767444849014282), ('\n', 0.9985685348510742), ('          ', 0.9937554597854614), ("'", 0.9986263513565063), ('3', 0.9979543685913086), ("':", 0.9988771080970764), ("{'", 0.9948028326034546), ('0', 0.9804394841194153), ("':", 0.9993048906326294), ("'", 0.997821569442749), ('3', 0.440542995929718), ("',", 0.9898444414138794), ("'", 0.9988656044006348), ('1', 0.9982807636260986), ("':", 0.9989249110221863), ("'", 0.9965435862541199), ('3', 0.3859196603298187), ("'}", 0.7983767986297607), ('\n', 0.9973828196525574), ('      ', 0.9878236055374146), ('}', 0.9986386895179749), ('\n', 0.9964128136634827), ('\n', 0.7229099273681641), ('      ', 0.9962157607078552), ('final', 0.7691442370414734), ('1', 0.8778563141822815), ('=', 0.9964614510536194), ("['", 0.9612401127815247), ('3', 0.3855903744697571), ("',", 0.6726680397987366), ("'", 0.9965760111808777), ('1', 0.4993697702884674), ("',", 0.7028592228889465), ("'", 0.9977273344993591), ('2', 0.8792529702186584), ("',", 0.8199272155761719), ('\n', 0.9961583018302917), ('      ', 0.9419355988502502), ('start', 0.9757535457611084), ('1', 0.990761935710907), ('=', 0.9971923232078552), ("'", 0.9876540303230286), ('0', 0.8394575715065002), ("'", 0.9972629547119141), ('\n', 0.9968001842498779), ('\n', 0.8325604796409607), ('      ', 0.9938242435455322), ('self', 0.9559267163276672), ('.', 0.9994844198226929), ('assert', 0.9975912570953369), ('Equal', 0.9840749502182007), ('(', 0.9902475476264954), ('True', 0.5616714358329773), (',', 0.9979234933853149), ('D', 0.9904149770736694), ('FA', 0.9976351261138916), ('(', 0.9952613711357117), ('trans', 0.9972606897354126), ('itions', 0.9976040720939636), ('1', 0.9724055528640747), (',', 0.9978506565093994), ('start', 0.9960208535194397), ('1', 0.9938592314720154), (',', 0.9982556700706482), ('final', 0.996644914150238), ('1', 0.9966014623641968), (',', 0.994579553604126), ('"', 0.9349019527435303), ('0', 0.5953476428985596), ('1', 0.5135584473609924), ('0', 0.5873537063598633), ('1', 0.4932345747947693), ('1', 0.8042774200439453), ('1', 0.8350639939308167), ('1', 0.8372786641120911), ('0', 0.9313323497772217), ('\n', 0.9949647188186646), ('      ', 0.9654303789138794), ('self', 0.9954782128334045), ('.', 0.9997474551200867), ('assert', 0.9971566200256348), ('Equal', 0.9948785305023193), ('(', 0.9973524808883667), ('True', 0.6921426653862), (',', 0.9973854422569275), ('D', 0.9956455826759338), ('FA', 0.9978967905044556), ('(', 0.9967300891876221), ('trans', 0.9978023171424866), ('itions', 0.9971877932548523), ('1', 0.9948223829269409), (',', 0.9981726408004761), ('start', 0.9960981607437134), ('1', 0.9963598847389221), (',', 0.998803973197937), ('final', 0.9968505501747131), ('1', 0.997832715511322), (',', 0.998740017414093), ('"', 0.988772451877594), ('0', 0.6317123770713806), ('1', 0.4860789179801941), ('0', 0.48328566551208496), ('1', 0.6346986889839172), ('0', 0.5808196663856506), ('1', 0.7706953287124634), ('0', 0.6988344192504883), ('"))', 0.7043588161468506), ('"))', 0.4422456920146942), ('\n', 0.9942939877510071), ('\n', 0.755898118019104), ('      ', 0.5064148306846619), ('trans', 0.8532665967941284), ('itions', 0.997761607170105), ('2', 0.9548784494400024), ('=', 0.9978400468826294), ('{', 0.9789849519729614), ('\n', 0.9977647066116333), ('          ', 0.9937189817428589), ("'", 0.9903712868690491), ('0', 0.5771999359130859), ("':", 0.9894100427627563), ("{'", 0.9704127907752991), ('0', 0.8655458092689514), ("':", 0.99281245470047), ("'", 0.9874141812324524), ('0', 0.45381593704223633), ("',", 0.8854804635047913), ("'", 0.9961385130882263), ('b', 0.9088866114616394), ("':", 0.9995600581169128), ("'", 0.9962945580482483), ('1', 0.5623552203178406), ("'},", 0.7169288992881775), ('\n', 0.9971972703933716), ('          ', 0.9957013726234436), ("'", 0.9994939565658569), ('1', 0.9974763989448547), ("':", 0.9995304346084595), ("{'", 0.9969197511672974), ('a', 0.9289076328277588), ("':", 0.9993472695350647), ("'", 0.998512327671051), ('1', 0.38579055666923523), ("',", 0.9907681345939636), ("'", 0.9991303086280823), ('b', 0.9877969622612), ("':", 0.999290943145752), ("'", 0.998229444026947), ('2', 0.42460325360298157), ("'},", 0.8352376818656921), ('\n', 0.9990298748016357), ('          ', 0.9932004809379578), ("'", 0.9992358684539795), ('2', 0.9971791505813599), ("':", 0.9993317723274231), ("{'", 0.9976783394813538), ('a', 0.9462295770645142), ("':", 0.9993288516998291), ("'", 0.9986647367477417), ('0', 0.5721011161804199), ("',", 0.9837369322776794), ("'", 0.9993417859077454), ('b', 0.9894406199455261), ("':", 0.9994199275970459), ("'", 0.9983622431755066), ('2', 0.5480111241340637), ("'}", 0.7102598547935486), ('\n', 0.9986542463302612), ('          ', 0.9833200573921204), ("'", 0.9990131855010986), ('3', 0.9979446530342102), ("':", 0.9990887641906738), ("{'", 0.9925876259803772), ('a', 0.957513153553009), ("':", 0.9992792010307312), ("'", 0.997249186038971), ('3', 0.7134254574775696), ("',", 0.9813041687011719), ("'", 0.9992865920066833), ('b', 0.9977929592132568), ("':", 0.999100923538208), ("'", 0.9973885416984558), ('3', 0.7860889434814453), ("'}", 0.8926544785499573), ('\n', 0.9983353018760681), ('      ', 0.9944604635238647), ('}', 0.9983286261558533), ('\n', 0.9974616765975952), ('\n', 0.9500263333320618), ('      ', 0.9973219037055969), ('final', 0.9819837808609009), ('2', 0.9963482022285461), ('=', 0.997820258140564), ("['", 0.9841518402099609), ('0', 0.7131825685501099), ("']", 0.959583044052124), ('\n', 0.9969108700752258), ('      ', 0.9929721355438232), ('start', 0.9970927238464355), ('2', 0.9970910549163818), ('=', 0.9975317716598511), ("'", 0.994709849357605), ('0', 0.845046877861023), ("'", 0.997868537902832), ('\n', 0.9968507885932922), ('\n', 0.9792710542678833), ('      ', 0.9960736036300659), ('self', 0.9876763820648193), ('.', 0.9972482323646545), ('assert', 0.9967206120491028), ('Equal', 0.989465594291687), ('(', 0.996446430683136), ('False', 0.77249675989151), (',', 0.9970122575759888), ('D', 0.9946343898773193), ('FA', 0.9970346689224243), ('(', 0.9979931116104126), ('trans', 0.997776210308075), ('itions', 0.9976845979690552), ('2', 0.9919066429138184), (',', 0.9977607727050781), ('start', 0.9965788722038269), ('2', 0.99513840675354), (',', 0.9983319640159607), ('final', 0.9964459538459778), ('2', 0.9979656934738159), (',', 0.997742772102356), ('"', 0.9748172760009766), ('ab', 0.23858721554279327), ('ab', 0.423786461353302), ('bb', 0.5955151319503784), ('"))', 0.4260299503803253), ('\n', 0.9957835674285889), ('      ', 0.9889163970947266), ('self', 0.9958136677742004), ('.', 0.9976010918617249), ('assert', 0.9965083003044128), ('Equal', 0.9942728877067566), ('(', 0.9974400997161865), ('True', 0.8447256684303284), (',', 0.9971175193786621), ('D', 0.9964203834533691), ('FA', 0.9986488223075867), ('(', 0.9972723126411438), ('trans', 0.9978653788566589), ('itions', 0.9976517558097839), ('2', 0.9967250227928162), (',', 0.99859219789505), ('start', 0.9967009425163269), ('2', 0.9977612495422363), (',', 0.9989437460899353), ('final', 0.9972225427627563), ('2', 0.9988067150115967), (',', 0.9990479350090027), ('"', 0.9940396547317505), ('aa', 0.2437099665403366), ('a', 0.3372744023799896), ('ab', 0.30413421988487244), ('"))', 0.7916713953018188), ('\n', 0.9934982061386108), ('\n', 0.9198480844497681), ('      ', 0.5078859329223633), ('if', 0.5001726746559143), ('__', 0.9638641476631165), ('name', 0.9452470541000366), ('__', 0.9485392570495605), ('==', 0.9439427852630615), ("'", 0.7703123688697815), ('__', 0.9455325603485107), ('main', 0.946887731552124), ('__', 0.8715723752975464), ("':", 0.9373918175697327), ('\n', 0.9064872860908508), ('  ', 0.9057313799858093), ('un', 0.6552088260650635), ('ittest', 0.8557302355766296), ('.', 0.8011214137077332), ('main', 0.9379386305809021), ('()', 0.8429301977157593), ('\n', 0.8921448588371277), ('</s>', 0.5720373392105103)]

In [13]:
assert tokenizer.decode(df_dataset['input_ids'][0]) == df_dataset[params['dataset']['content_column']][0]
df_dataset[params['dataset']['content_column']][0]

2024-09-29 15:00:42.720878: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-29 15:00:42.735281: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-29 15:00:42.739705: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-29 15:00:42.750624: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

'def test_DFA(self):\n        transitions = {\n            \'a\': {\'1\': \'a\', \'0\': \'b\'},\n            \'b\': {\'1\': \'b\', \'0\': \'a\'}\n        }\n\n        final = [\'a\']\n        start = \'a\'\n\n        self.assertEqual(False, DFA(transitions, start, final, "000111100"))\n        self.assertEqual(True, DFA(transitions, start, final, "111000011"))\n\n        transitions1 = {\n            \'0\': {\'0\': \'1\', \'1\': \'0\'},\n            \'1\': {\'0\': \'2\', \'1\': \'0\'},\n            \'2\': {\'0\': \'2\', \'1\': \'3\'},\n            \'3\': {\'0\': \'3\', \'1\': \'3\'}\n        }\n\n        final1 = [\'0\', \'1\', \'2\']\n        start1 = \'0\'\n\n        self.assertEqual(False, DFA(transitions1, start1, final1, "0001111"))\n        self.assertEqual(True, DFA(transitions1, start1, final1, "01010101"))\n\n        transitions2 = {\n            \'0\': {\'a\': \'0\', \'b\': \'1\'},\n            \'1\': {\'a\': \'0\', \'b\': \'2\'},\n            \'2\': {\'a\': \'3\', \'b\': \'2\'},\n            \'3\': {\'a\': \'3\', \'b\': \'3\'}\n        }\n\n        final2 = [\'3\']\n        start2 = \'0\'\n\n        self.assertEqual(False, DFA(transitions2, start2, final2, "aaabbb"))\n        self.assertEqual(True, DFA(transitions2, start2, final2, "baabba"))\n\n\nif __name__ == \'__main__\':\n    unittest.main()\n'

In [14]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

actual_cases = actual_logit(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out] , #Out is a complete sequence
    tokenized_prompt = input_ids_list[0], ## SAMPLE ID
    tokenizer_fn = tokenizer
    )
actual_cases

[('def', 0.0007611322216689587),
 ('test', 0.019638599827885628),
 ('_', 0.8005586862564087),
 ('DF', 8.983312909549568e-06),
 ('A', 0.11648616939783096),
 ('(', 0.09526648372411728),
 ('self', 0.33107417821884155),
 ('):', 0.9489971399307251),
 ('\n', 0.9538149833679199),
 ('      ', 0.5308957695960999),
 ('trans', 0.002045711735263467),
 ('itions', 0.6213518381118774),
 ('=', 0.9065775871276855),
 ('{', 0.4410155415534973),
 ('\n', 0.6546733975410461),
 ('          ', 0.8376067280769348),
 ("'", 0.44875967502593994),
 ('a', 0.19057433307170868),
 ("':", 0.8309361338615417),
 ("{'", 0.3205947279930115),
 ('1', 0.014439268968999386),
 ("':", 0.8714505434036255),
 ("'", 0.7137954235076904),
 ('a', 0.20106470584869385),
 ("',", 0.6139147877693176),
 ("'", 0.9447020292282104),
 ('0', 0.48086488246917725),
 ("':", 0.9955577254295349),
 ("'", 0.9402093291282654),
 ('b', 0.6728489995002747),
 ("'},", 0.8593389987945557),
 ('\n', 0.9850090742111206),
 ('          ', 0.9980431795120239),
 ("'", 0.999308705329895),
 ('b', 0.9908697009086609),
 ("':", 0.9996918439865112),
 ("{'", 0.9865347743034363),
 ('1', 0.7686476707458496),
 ("':", 0.9987339377403259),
 ("'", 0.9897117614746094),
 ('b', 0.25749289989471436),
 ("',", 0.9177125692367554),
 ("'", 0.9986819624900818),
 ('0', 0.9948652386665344),
 ("':", 0.999438464641571),
 ("'", 0.9769797325134277),
 ('a', 0.4069027304649353),
 ("'}", 0.4889342486858368),
 ('\n', 0.9975132942199707),
 ('      ', 0.9758861660957336),
 ('}', 0.9991366267204285),
 ('\n', 0.9969767332077026),
 ('\n', 0.2064535766839981),
 ('      ', 0.9965560436248779),
 ('final', 0.016733339056372643),
 ('=', 0.12155484408140182),
 ("['", 0.19067469239234924),
 ('a', 0.7904111742973328),
 ("']", 0.5926622748374939),
 ('\n', 0.9942573308944702),
 ('      ', 0.3350073993206024),
 ('start', 0.1336270570755005),
 ('=', 0.9400723576545715),
 ("'", 0.8634653091430664),
 ('a', 0.9308050870895386),
 ("'", 0.9986312985420227),
 ('\n', 0.9970698356628418),
 ('\n', 0.6120559573173523),
 ('      ', 0.9954967498779297),
 ('self', 0.090509794652462),
 ('.', 0.9467857480049133),
 ('assert', 0.5104538798332214),
 ('Equal', 0.4212954640388489),
 ('(', 0.9118632078170776),
 ('False', 0.002872644690796733),
 (',', 0.9972060322761536),
 ('D', 0.31814688444137573),
 ('FA', 0.9799715280532837),
 ('(', 0.6089507937431335),
 ('trans', 0.827334463596344),
 ('itions', 0.9971981048583984),
 (',', 0.9649175405502319),
 ('start', 0.22938217222690582),
 (',', 0.9317087531089783),
 ('final', 0.931850016117096),
 (',', 0.1329803168773651),
 ('"', 0.044326309114694595),
 ('0', 0.3343713879585266),
 ('0', 0.24635004997253418),
 ('0', 0.4043825566768646),
 ('1', 0.2506016194820404),
 ('1', 0.29187098145484924),
 ('1', 0.4444510340690613),
 ('1', 0.2717384994029999),
 ('0', 0.35851728916168213),
 ('0', 0.4345461428165436),
 ('"))', 0.08152888715267181),
 ('\n', 0.9881094098091125),
 ('      ', 0.7335585355758667),
 ('self', 0.988298237323761),
 ('.', 0.9970170259475708),
 ('assert', 0.9965764880180359),
 ('Equal', 0.9940364360809326),
 ('(', 0.9964062571525574),
 ('True', 0.8024066686630249),
 (',', 0.9955580830574036),
 ('D', 0.970678448677063),
 ('FA', 0.9964125752449036),
 ('(', 0.9968476891517639),
 ('trans', 0.9985268115997314),
 ('itions', 0.9979275465011597),
 (',', 0.9969900846481323),
 ('start', 0.9959949254989624),
 (',', 0.9978165626525879),
 ('final', 0.9951617121696472),
 (',', 0.9977153539657593),
 ('"', 0.9835497140884399),
 ('1', 0.165755957365036),
 ('1', 0.3675902187824249),
 ('1', 0.5910996198654175),
 ('0', 0.4798378050327301),
 ('0', 0.6552492380142212),
 ('0', 0.6837068796157837),
 ('0', 0.6763025522232056),
 ('1', 0.6922487020492554),
 ('1', 0.7839030623435974),
 ('"))', 0.9597861766815186),
 ('\n', 0.991637647151947),
 ('\n', 0.6612272262573242),
 ('      ', 0.08081462234258652),
 ('trans', 0.5131595134735107),
 ('itions', 0.997448742389679),
 ('1', 0.008336316794157028),
 ('=', 0.9889856576919556),
 ('{', 0.9504842162132263),
 ('\n', 0.9907656908035278),
 ('          ', 0.9885663390159607),
 ("'", 0.9841746687889099),
 ('0', 0.09895268827676773),
 ("':", 0.9797533750534058),
 ("{'", 0.8905991911888123),
 ('0', 0.455904483795166),
 ("':", 0.9860142469406128),
 ("'", 0.9624955654144287),
 ('1', 0.15535445511341095),
 ("',", 0.7261291146278381),
 ("'", 0.9935154914855957),
 ('1', 0.9591103196144104),
 ("':", 0.9980546236038208),
 ("'", 0.9887774586677551),
 ('0', 0.4828164875507355),
 ("'},", 0.9090369939804077),
 ('\n', 0.9898958206176758),
 ('          ', 0.9638579487800598),
 ("'", 0.9975481629371643),
 ('1', 0.996057391166687),
 ("':", 0.9985870122909546),
 ("{'", 0.994279146194458),
 ('0', 0.8755097389221191),
 ("':", 0.9990615248680115),
 ("'", 0.9976678490638733),
 ('2', 0.007998579181730747),
 ("',", 0.9693958759307861),
 ("'", 0.9986960291862488),
 ('1', 0.9946012496948242),
 ("':", 0.9989281296730042),
 ("'", 0.9961928129196167),
 ('0', 0.2871302366256714),
 ("'},", 0.19249117374420166),
 ('\n', 0.9964964985847473),
 ('          ', 0.9670060276985168),
 ("'", 0.997413694858551),
 ('2', 0.9941605925559998),
 ("':", 0.9985839128494263),
 ("{'", 0.9945108890533447),
 ('0', 0.9567317962646484),
 ("':", 0.9992457628250122),
 ("'", 0.9971611499786377),
 ('2', 0.340669184923172),
 ("',", 0.989173412322998),
 ("'", 0.9985886216163635),
 ('1', 0.997443437576294),
 ("':", 0.9988304972648621),
 ("'", 0.9972841739654541),
 ('3', 0.1332540661096573),
 ("'},", 0.7767444849014282),
 ('\n', 0.9985685348510742),
 ('          ', 0.9937554597854614),
 ("'", 0.9986263513565063),
 ('3', 0.9979543685913086),
 ("':", 0.9988771080970764),
 ("{'", 0.9948028326034546),
 ('0', 0.9804394841194153),
 ("':", 0.9993048906326294),
 ("'", 0.997821569442749),
 ('3', 0.440542995929718),
 ("',", 0.9898444414138794),
 ("'", 0.9988656044006348),
 ('1', 0.9982807636260986),
 ("':", 0.9989249110221863),
 ("'", 0.9965435862541199),
 ('3', 0.3859196603298187),
 ("'}", 0.7983767986297607),
 ('\n', 0.9973828196525574),
 ('      ', 0.9878236055374146),
 ('}', 0.9986386895179749),
 ('\n', 0.9964128136634827),
 ('\n', 0.7229099273681641),
 ('      ', 0.9962157607078552),
 ('final', 0.7691442370414734),
 ('1', 0.8778563141822815),
 ('=', 0.9964614510536194),
 ("['", 0.9612401127815247),
 ('0', 0.18482664227485657),
 ("',", 0.6726680397987366),
 ("'", 0.9965760111808777),
 ('1', 0.4993697702884674),
 ("',", 0.7028592228889465),
 ("'", 0.9977273344993591),
 ('2', 0.8792529702186584),
 ("']", 0.1772131621837616),
 ('\n', 0.9961583018302917),
 ('      ', 0.9419355988502502),
 ('start', 0.9757535457611084),
 ('1', 0.990761935710907),
 ('=', 0.9971923232078552),
 ("'", 0.9876540303230286),
 ('0', 0.8394575715065002),
 ("'", 0.9972629547119141),
 ('\n', 0.9968001842498779),
 ('\n', 0.8325604796409607),
 ('      ', 0.9938242435455322),
 ('self', 0.9559267163276672),
 ('.', 0.9994844198226929),
 ('assert', 0.9975912570953369),
 ('Equal', 0.9840749502182007),
 ('(', 0.9902475476264954),
 ('False', 0.41897886991500854),
 (',', 0.9979234933853149),
 ('D', 0.9904149770736694),
 ('FA', 0.9976351261138916),
 ('(', 0.9952613711357117),
 ('trans', 0.9972606897354126),
 ('itions', 0.9976040720939636),
 ('1', 0.9724055528640747),
 (',', 0.9978506565093994),
 ('start', 0.9960208535194397),
 ('1', 0.9938592314720154),
 (',', 0.9982556700706482),
 ('final', 0.996644914150238),
 ('1', 0.9966014623641968),
 (',', 0.994579553604126),
 ('"', 0.9349019527435303),
 ('0', 0.5953476428985596),
 ('0', 0.41317009925842285),
 ('0', 0.5873537063598633),
 ('1', 0.4932345747947693),
 ('1', 0.8042774200439453),
 ('1', 0.8350639939308167),
 ('1', 0.8372786641120911),
 ('"))', 0.01270454004406929),
 ('\n', 0.9949647188186646),
 ('      ', 0.9654303789138794),
 ('self', 0.9954782128334045),
 ('.', 0.9997474551200867),
 ('assert', 0.9971566200256348),
 ('Equal', 0.9948785305023193),
 ('(', 0.9973524808883667),
 ('True', 0.6921426653862),
 (',', 0.9973854422569275),
 ('D', 0.9956455826759338),
 ('FA', 0.9978967905044556),
 ('(', 0.9967300891876221),
 ('trans', 0.9978023171424866),
 ('itions', 0.9971877932548523),
 ('1', 0.9948223829269409),
 (',', 0.9981726408004761),
 ('start', 0.9960981607437134),
 ('1', 0.9963598847389221),
 (',', 0.998803973197937),
 ('final', 0.9968505501747131),
 ('1', 0.997832715511322),
 (',', 0.998740017414093),
 ('"', 0.988772451877594),
 ('0', 0.6317123770713806),
 ('1', 0.4860789179801941),
 ('0', 0.48328566551208496),
 ('1', 0.6346986889839172),
 ('0', 0.5808196663856506),
 ('1', 0.7706953287124634),
 ('0', 0.6988344192504883),
 ('1', 0.24115823209285736),
 ('"))', 0.4422456920146942),
 ('\n', 0.9942939877510071),
 ('\n', 0.755898118019104),
 ('      ', 0.5064148306846619),
 ('trans', 0.8532665967941284),
 ('itions', 0.997761607170105),
 ('2', 0.9548784494400024),
 ('=', 0.9978400468826294),
 ('{', 0.9789849519729614),
 ('\n', 0.9977647066116333),
 ('          ', 0.9937189817428589),
 ("'", 0.9903712868690491),
 ('0', 0.5771999359130859),
 ("':", 0.9894100427627563),
 ("{'", 0.9704127907752991),
 ('a', 0.015751240774989128),
 ("':", 0.99281245470047),
 ("'", 0.9874141812324524),
 ('0', 0.45381593704223633),
 ("',", 0.8854804635047913),
 ("'", 0.9961385130882263),
 ('b', 0.9088866114616394),
 ("':", 0.9995600581169128),
 ("'", 0.9962945580482483),
 ('1', 0.5623552203178406),
 ("'},", 0.7169288992881775),
 ('\n', 0.9971972703933716),
 ('          ', 0.9957013726234436),
 ("'", 0.9994939565658569),
 ('1', 0.9974763989448547),
 ("':", 0.9995304346084595),
 ("{'", 0.9969197511672974),
 ('a', 0.9289076328277588),
 ("':", 0.9993472695350647),
 ("'", 0.998512327671051),
 ('0', 0.2902860939502716),
 ("',", 0.9907681345939636),
 ("'", 0.9991303086280823),
 ('b', 0.9877969622612),
 ("':", 0.999290943145752),
 ("'", 0.998229444026947),
 ('2', 0.42460325360298157),
 ("'},", 0.8352376818656921),
 ('\n', 0.9990298748016357),
 ('          ', 0.9932004809379578),
 ("'", 0.9992358684539795),
 ('2', 0.9971791505813599),
 ("':", 0.9993317723274231),
 ("{'", 0.9976783394813538),
 ('a', 0.9462295770645142),
 ("':", 0.9993288516998291),
 ("'", 0.9986647367477417),
 ('3', 0.10655885189771652),
 ("',", 0.9837369322776794),
 ("'", 0.9993417859077454),
 ('b', 0.9894406199455261),
 ("':", 0.9994199275970459),
 ("'", 0.9983622431755066),
 ('2', 0.5480111241340637),
 ("'},", 0.28061479330062866),
 ('\n', 0.9986542463302612),
 ('          ', 0.9833200573921204),
 ("'", 0.9990131855010986),
 ('3', 0.9979446530342102),
 ("':", 0.9990887641906738),
 ("{'", 0.9925876259803772),
 ('a', 0.957513153553009),
 ("':", 0.9992792010307312),
 ("'", 0.997249186038971),
 ('3', 0.7134254574775696),
 ("',", 0.9813041687011719),
 ("'", 0.9992865920066833),
 ('b', 0.9977929592132568),
 ("':", 0.999100923538208),
 ("'", 0.9973885416984558),
 ('3', 0.7860889434814453),
 ("'}", 0.8926544785499573),
 ('\n', 0.9983353018760681),
 ('      ', 0.9944604635238647),
 ('}', 0.9983286261558533),
 ('\n', 0.9974616765975952),
 ('\n', 0.9500263333320618),
 ('      ', 0.9973219037055969),
 ('final', 0.9819837808609009),
 ('2', 0.9963482022285461),
 ('=', 0.997820258140564),
 ("['", 0.9841518402099609),
 ('3', 0.16422748565673828),
 ("']", 0.959583044052124),
 ('\n', 0.9969108700752258),
 ('      ', 0.9929721355438232),
 ('start', 0.9970927238464355),
 ('2', 0.9970910549163818),
 ('=', 0.9975317716598511),
 ("'", 0.994709849357605),
 ('0', 0.845046877861023),
 ("'", 0.997868537902832),
 ('\n', 0.9968507885932922),
 ('\n', 0.9792710542678833),
 ('      ', 0.9960736036300659),
 ('self', 0.9876763820648193),
 ('.', 0.9972482323646545),
 ('assert', 0.9967206120491028),
 ('Equal', 0.989465594291687),
 ('(', 0.996446430683136),
 ('False', 0.77249675989151),
 (',', 0.9970122575759888),
 ('D', 0.9946343898773193),
 ('FA', 0.9970346689224243),
 ('(', 0.9979931116104126),
 ('trans', 0.997776210308075),
 ('itions', 0.9976845979690552),
 ('2', 0.9919066429138184),
 (',', 0.9977607727050781),
 ('start', 0.9965788722038269),
 ('2', 0.99513840675354),
 (',', 0.9983319640159607),
 ('final', 0.9964459538459778),
 ('2', 0.9979656934738159),
 (',', 0.997742772102356),
 ('"', 0.9748172760009766),
 ('aa', 0.06130050867795944),
 ('ab', 0.423786461353302),
 ('bb', 0.5955151319503784),
 ('"))', 0.4260299503803253),
 ('\n', 0.9957835674285889),
 ('      ', 0.9889163970947266),
 ('self', 0.9958136677742004),
 ('.', 0.9976010918617249),
 ('assert', 0.9965083003044128),
 ('Equal', 0.9942728877067566),
 ('(', 0.9974400997161865),
 ('True', 0.8447256684303284),
 (',', 0.9971175193786621),
 ('D', 0.9964203834533691),
 ('FA', 0.9986488223075867),
 ('(', 0.9972723126411438),
 ('trans', 0.9978653788566589),
 ('itions', 0.9976517558097839),
 ('2', 0.9967250227928162),
 (',', 0.99859219789505),
 ('start', 0.9967009425163269),
 ('2', 0.9977612495422363),
 (',', 0.9989437460899353),
 ('final', 0.9972225427627563),
 ('2', 0.9988067150115967),
 (',', 0.9990479350090027),
 ('"', 0.9940396547317505),
 ('ba', 0.07277359068393707),
 ('ab', 0.31170183420181274),
 ('ba', 0.29654377698898315),
 ('"))', 0.7916713953018188),
 ('\n', 0.9934982061386108),
 ('\n', 0.9198480844497681),
 ('\n', 0.16914401948451996),
 ('if', 0.5001726746559143),
 ('__', 0.9638641476631165),
 ('name', 0.9452470541000366),
 ('__', 0.9485392570495605),
 ('==', 0.9439427852630615),
 ("'", 0.7703123688697815),
 ('__', 0.9455325603485107),
 ('main', 0.946887731552124),
 ('__', 0.8715723752975464),
 ("':", 0.9373918175697327),
 ('\n', 0.9064872860908508),
 ('  ', 0.9057313799858093),
 ('un', 0.6552088260650635),
 ('ittest', 0.8557302355766296),
 ('.', 0.8011214137077332),
 ('main', 0.9379386305809021),
 ('()', 0.8429301977157593),
 ('\n', 0.8921448588371277)]

#### Processing all the Batches

In [15]:
def batching_logits(tokenizer,tf_input_ids,size=10000):
    max_logit_token_prompt = []
    min_logit_token_prompt = []
    actual_logit_token_prompt = []

    
    soft = torch.nn.Softmax( dim = 0 )                          #Flattening normalization
    
    for file in range( size ):
        out = np.load(params['callbacks_dir']+ '/'+ params['current_model'] + '_q_' + params['quantization'] +'/'+ f'logits_tensor[{file}]_batch[{file}].npy') #<sample,tokens,voc_tokens>
        out = out[0]  ##### #<tokens,voc_tokens>
        next_tokens_distribution = [ soft( torch.from_numpy(token) ) for token in out]  #Flattening normalization
        
        max_cases,min_cases = min_max_logits(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenizer_fn= tokenizer
            )

        actual_cases = actual_logit(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenized_prompt = tf_input_ids[ file ],
            tokenizer_fn = tokenizer
            )
        
        max_logit_token_prompt.append( max_cases )
        min_logit_token_prompt.append( min_cases )
        actual_logit_token_prompt.append( actual_cases )
        
        logging.info(file)
    return max_logit_token_prompt,min_logit_token_prompt,actual_logit_token_prompt

In [16]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

In [17]:
max_logit_token_prompt, min_logit_token_prompt, actual_logit_token_prompt = batching_logits(
    tokenizer=tokenizer , tf_input_ids=input_ids_list, 
    size = params['dataset']['number_samples']
) #<---WARNING TIME Consuming

#### Saving results

In [18]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [19]:
dataframe_to_save = df_dataset.copy()
dataframe_to_save['max_prob'] = max_logit_token_prompt
dataframe_to_save['min_prob'] = min_logit_token_prompt
dataframe_to_save['actual_prob'] = actual_logit_token_prompt
dataframe_to_save.shape

(55, 30)

In [20]:
dataframe_to_save.head(5)

,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,repo,...,vocab_size,nloc,token_counts,n_identifiers,repository,year,input_ids,max_prob,min_prob,actual_prob
0,C0103,1,0,1,12,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,64,29,264,16,algorithms,outputs-22,"[822, 1243, 29918, 4037, 29909, 29898, 1311, 1...","[(<PRE>, 0.7492899298667908), (module, 0.47944...","[(<s>, 6.321468413832132e-13), ($}, 1.21012033...","[(def, 0.0007611322216689587), (test, 0.019638..."
1,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386..."
2,C0103,3,8,3,9,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386..."
3,C0103,4,8,4,9,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386..."
4,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,30,11,117,11,algorithms,outputs-22,"[822, 1243, 29918, 13092, 29918, 2378, 29918, ...","[(<PRE>, 0.749289333820343), (module, 0.479442...","[(<s>, 6.322174771547506e-13), ($}, 1.21012075...","[(def, 0.0007611389737576246), (test, 0.019638..."

In [21]:
create_folder(params['output_path'] + '/' + params['current_model'] + '_q_' + params['quantization'])
dataframe_to_save.to_csv( params['output_path'] + '/' + params['current_model'] + '_q_' + params['quantization'] + '/' + 'raw_logits.csv')

#### Loss Retrieval

In [22]:
def batching_loss( size = dataframe_to_save.shape[0] ):
    output_loss = []
    for current_batch in range(size):
        out = np.load(params['callbacks_dir']+ '/'+ params['current_model'] +  '_q_' + params['quantization'] +'/' + f'_loss_batch[{current_batch}].npy') 
        output_loss.append( out.item() ) #.item() for numpy library
        logging.info(current_batch)
    return output_loss

In [23]:
output_loss = batching_loss() #[WAENING!] Takes Time

In [24]:
output_loss

[0.4024338722229004,
 0.571848452091217,
 0.571848452091217,
 0.571848452091217,
 0.7669380307197571,
 0.7669380307197571,
 0.7669380307197571,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.7339152693748474,
 0.20522019267082214,
 1.5347800254821777,
 1.3996508121490479,
 1.4757285118103027,
 0.720551609992981,
 0.994199812412262,
 1.055303692817688,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 1.188644289970398,
 1.0981333255767822,
 1.589848518371582,
 1.826017141342163,
 1.826017141342163,
 1.5603570938110352,
 1.5603570938110352,
 2.572435140609741,
 0.8118057250976562,
 0.8118057250976562,
 0.2825244069099426,
 0.2825244069099426,
 0.9048572778701782,
 0.6807515621185303,
 0.740659236907959,
 1.1595052480697632,
 1.2384271621704102,
 1.2384271621704102,
 0.5861526131629944,
 0.5861526131629944,
 0.5861526131629944,
 0.8695902228355408,
 0.8695902228355408,
 0.8695902228355408]

In [25]:
dataframe_to_save['loss'] = output_loss
dataframe_to_save.head(5)

,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,repo,...,nloc,token_counts,n_identifiers,repository,year,input_ids,max_prob,min_prob,actual_prob,loss
0,C0103,1,0,1,12,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,29,264,16,algorithms,outputs-22,"[822, 1243, 29918, 4037, 29909, 29898, 1311, 1...","[(<PRE>, 0.7492899298667908), (module, 0.47944...","[(<s>, 6.321468413832132e-13), ($}, 1.21012033...","[(def, 0.0007611322216689587), (test, 0.019638...",0.402434
1,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386...",0.571848
2,C0103,3,8,3,9,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386...",0.571848
3,C0103,4,8,4,9,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386...",0.571848
4,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,117,11,algorithms,outputs-22,"[822, 1243, 29918, 13092, 29918, 2378, 29918, ...","[(<PRE>, 0.749289333820343), (module, 0.479442...","[(<s>, 6.322174771547506e-13), ($}, 1.21012075...","[(def, 0.0007611389737576246), (test, 0.019638...",0.766938

In [26]:
## Saving CheckPoint 2
dataframe_to_save.to_csv( params['output_path'] + '/' + params['current_model'] + '_q_' + params['quantization'] + '/' + 'raw_logits.csv')

In [27]:
torch.cuda.empty_cache()
gc.collect()

37