# Logits Preprocessing and Data Engineering

In [1]:
def default_params(): 
    return {
        'current_model': 'M2', 
        'quantization': 'none', #['none',"int4", "int8", "float32", "float16"]
        'dataset': {
            'name': '/workspaces/CodeSmells/semeru-datasets/code_smells/codesmell_dataset.csv',
            'content_column': 'code',
        },
        'default_max_position_embeddings' : 16384,
        'output_path': '../data/raw_logits',
        'preprocessed_dataset_dir' : '../datax/code_smells/dataset_preprocessing',
        'cache_dir': '../datax/hugging_face_cache',
        'log_file': '../datax/code_smells/logit_extraction.log', 
        'callbacks_dir' : '../datax/code_smells/callbacks',
        'causal_models': {
            'M2': 'mistralai/Mistral-7B-v0.3', #https://huggingface.co/codellama/CodeLlama-13b-hf
        },
    }
params = default_params()

#### Imports

In [2]:
import pandas as pd
import os
import time
import numpy as np
import torch
import gc

In [3]:
from transformers import AutoTokenizer, MistralForCausalLM 
from datasets import load_dataset

In [4]:
import logging
#logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
logging.basicConfig(
    filename=params['log_file'],
    filemode='a',
    format='%(asctime)s : %(levelname)s : %(message)s', 
    level=logging.INFO
    )

In [5]:
import seaborn as sns
from scipy import stats
from statistics import NormalDist
import matplotlib.pyplot as plt

#### Dataset

In [17]:
df_dataset = pd.read_json(params['preprocessed_dataset_dir'] + '/' + params['current_model'] + '_q_' + params['quantization'] + '.json', )

In [ ]:
df_dataset.reset_index(drop=True, inplace=True)

#### Model Loading

In [6]:
def instantiate_llm(model_name:str, cache_dir:str):
     '''Instantiate AutoModelForCausalLM'''
     tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded LlamaTokenizer - " + model_name)
     model = None
     match params['quantization']:
               case 'int4':
                    model = MistralForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_4bit=True)
               case 'int8':
                    model = MistralForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_8bit=True)
               case 'float32':
                    model = MistralForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float32)
               case 'float16':
                    model = MistralForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float16)
               case _: 
                    model = MistralForCausalLM.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded MistralForCausalLM - " + model_name)

     return tokenizer, model

In [7]:
tokenizer, model = instantiate_llm(params['causal_models'][params['current_model']], params['cache_dir'])

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

#### Softmax Normalization and Data Engineering

In [8]:
def topk_tuple( logit_vocab_tensor, largest, tokenizer_fn):
    "Run topk for a token"
    topk = logit_vocab_tensor.topk( k=1 , largest=largest ) #TODO K number of elements can be extended
    return ( tokenizer.convert_tokens_to_string([tokenizer_fn.decode(topk.indices)]), topk.values.item())

def min_max_logits( logit_vocab_sample_tensor, tokenizer_fn ):
    "Compute min_max for a sample"
    max_cases = []
    min_cases = []
    for logit_vocab_tensor in logit_vocab_sample_tensor:
        max_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = True, tokenizer_fn = tokenizer_fn) ) #TST Max Logit
        min_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = False, tokenizer_fn = tokenizer_fn) ) #TST Min Logit
    return max_cases, min_cases

def actual_logit( 
                 logit_vocab_sample_tensor, 
                 tokenized_prompt, 
                 tokenizer_fn,
                 ):
    "Compute actual logits for a sample"
    actual_logits_prompt = []
    for token_pos, id_token in enumerate( tokenized_prompt[1:] ): #Eliminate the first token prediction since we do not use it
        actual_logits_prompt.append(
            (   tokenizer.convert_tokens_to_string([tokenizer_fn.decode( int(id_token))]), #retrieving the name of the token with the id
                logit_vocab_sample_tensor[token_pos][int(id_token)].item()) #retrieving the logit given the position in the sequence and the position in the vocab
            )
    return actual_logits_prompt

In [9]:
soft = torch.nn.Softmax( dim = 0 ) #Flattening normalization

In [18]:
out= np.load(params['callbacks_dir']+ '/'+ params['current_model'] + '_q_' + params['quantization'] +'/' + 'logits_tensor[0]_batch[0].npy')
print(out.shape) #<sample,tokens,voc_tokens>
out = out[0]

(1, 457, 32768)

In [19]:
max_case,min_case = min_max_logits(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out], ####### 
    tokenizer_fn= tokenizer
    )
print(max_case)
assert len(max_case) == len(min_case)

[('#', 0.2665287256240845), ('solution', 0.058843858540058136), ('_', 0.7111697196960449), ('get', 0.037967000156641006), ('_', 0.028935091570019722), ('_', 0.43795230984687805), ('self', 0.142356738448143), ('):', 0.7956698536872864), ('\n', 0.9903011322021484), (' ', 0.564018726348877), ('"""', 0.16692335903644562), ('=', 0.8424184322357178), ('{', 0.3088832497596741), ('\n', 0.7759588360786438), ('         ', 0.8008356690406799), ("'", 0.332145094871521), ('a', 0.2342398315668106), ("':", 0.9017483592033386), ("{'", 0.3621208071708679), ('a', 0.7407320141792297), ("':", 0.8090277314186096), ("'", 0.6437082290649414), ('1', 0.26039478182792664), ("',", 0.7275657057762146), ("'", 0.9586458802223206), ('2', 0.6101283431053162), ("':", 0.996057391166687), ("'", 0.9527722597122192), ('b', 0.6182431578636169), ("'},", 0.8787501454353333), ('\n', 0.9783669114112854), ('         ', 0.9917137622833252), ("'", 0.9982050657272339), ('b', 0.9849040508270264), ("':", 0.9993496537208557), ("{'", 0.9859283566474915), ('1', 0.8342114090919495), ("':", 0.9994694590568542), ("'", 0.9913591146469116), ('b', 0.4031481444835663), ("',", 0.9744338989257812), ("'", 0.9992467164993286), ('0', 0.9972277283668518), ("':", 0.9993991851806641), ("'", 0.9865380525588989), ('c', 0.34684303402900696), ("'},", 0.655296802520752), ('\n', 0.9977586269378662), ('     ', 0.9680642485618591), ('}', 0.997857391834259), ('\n', 0.9981277585029602), ('     ', 0.7158758044242859), ('     ', 0.973686933517456), ('d', 0.16795353591442108), ('_', 0.8206825852394104), ("{'", 0.5453217625617981), ('a', 0.5682030916213989), ("',", 0.5764328241348267), ('\n', 0.9797280430793762), ('\n', 0.5832593441009521), ('start', 0.17488427460193634), ('=', 0.8738885521888733), ("'", 0.8851250410079956), ('a', 0.9446073174476624), ("'", 0.998727023601532), ('\n', 0.9946613907814026), ('\n', 0.6561527848243713), ('     ', 0.9772368669509888), ('d', 0.2537725865840912), ('.', 0.9834739565849304), ('assertEqual', 0.4533636271953583), ('(', 0.919384241104126), ('self', 0.3565860390663147), (',', 0.9968687891960144), ('self', 0.5537281036376953), ('FA', 0.9827203750610352), ('(', 0.6894293427467346), ('trans', 0.7233177423477173), ('itions', 0.9997740387916565), (',', 0.9773522019386292), ('final', 0.7670024633407593), (',', 0.963057816028595), ('final', 0.964323878288269), ('))', 0.41387230157852173), ("'", 0.4294830858707428), ('1', 0.4943767189979553), ('1', 0.4985133111476898), ('1', 0.4331073760986328), ('1', 0.33394691348075867), ('1', 0.3867165744304657), ('0', 0.3926854133605957), ('0', 0.35377880930900574), ('1', 0.35923054814338684), ('1', 0.3756698966026306), ('0', 0.372475802898407), ('\n', 0.7402434945106506), ('\n', 0.5398252606391907), ('self', 0.9463321566581726), ('.', 0.999923586845398), ('assertEqual', 0.9923081398010254), ('(', 0.9934677481651306), ('True', 0.7299107313156128), (',', 0.9969683289527893), ('D', 0.9745734930038452), ('FA', 0.9998252987861633), ('(', 0.9978380799293518), ('trans', 0.998248815536499), ('itions', 0.9999830722808838), (',', 0.999855637550354), ('start', 0.995385468006134), (',', 0.9998063445091248), ('final', 0.9986746311187744), (',', 0.9980573058128357), ('"', 0.9934554696083069), ('1', 0.5589944124221802), ('1', 0.6052656769752502), ('1', 0.6971897482872009), ('1', 0.6005953550338745), ('0', 0.7350143194198608), ('0', 0.4018915295600891), ('0', 0.5647594928741455), ('1', 0.5884052515029907), ('1', 0.8227081298828125), ('"))', 0.903008222579956), ('\n', 0.6423302292823792), ('     ', 0.5958430767059326), ('\n', 0.33916065096855164), ('transitions', 0.30426251888275146), ('=', 0.8463290333747864), ('=', 0.9884184002876282), ('{', 0.9494293332099915), ('\n', 0.9943808913230896), ('         ', 0.9753065705299377), ("'", 0.9719103574752808), ('a', 0.7444783449172974), ("':", 0.9822317957878113), ("{'", 0.7888122200965881), ('1', 0.5555793642997742), ("':", 0.9884136319160461), ("'", 0.9700012803077698), ('0', 0.5115693211555481), ("',", 0.6202284693717957), ("'", 0.9884694218635559), ('1', 0.9772676825523376), ("':", 0.998090922832489), ("'", 0.9800103306770325), ('0', 0.545506477355957), ("'},", 0.7868120670318604), ('\n', 0.9947299957275391), ('         ', 0.9774352312088013), ("'", 0.9990290403366089), ('1', 0.9961087107658386), ("':", 0.9993680119514465), ("{'", 0.9910356998443604), ('0', 0.8169069886207581), ("':", 0.9998235106468201), ("'", 0.9979217648506165), ('0', 0.6394438147544861), ("',", 0.9885722398757935), ("'", 0.9995174407958984), ('1', 0.9959957599639893), ("':", 0.9996737241744995), ("'", 0.9953658580780029), ('0', 0.2945958375930786), ("'}", 0.7220730185508728), ('\n', 0.9995805621147156), ('         ', 0.7507445216178894), ("'", 0.9955295920372009), ('2', 0.9928144812583923), ("':", 0.9994248151779175), ("{'", 0.9935333728790283), ('0', 0.9579411149024963), ("':", 0.9997245669364929), ("'", 0.9908989667892456), ('0', 0.27779334783554077), ("',", 0.9905335903167725), ("'", 0.9997044205665588), ('1', 0.9980837106704712), ("':", 0.9997767806053162), ("'", 0.9962595701217651), ('0', 0.38113686442375183), ("'},", 0.6666712760925293), ('\n', 0.9997475743293762), ('         ', 0.9602823853492737), ("'", 0.998836100101471), ('3', 0.9982097148895264), ("':", 0.999711811542511), ("{'", 0.9965382814407349), ('0', 0.9859376549720764), ("':", 0.9997407793998718), ("'", 0.9941300749778748), ('3', 0.3987932503223419), ("',", 0.9935994148254395), ("'", 0.9996402263641357), ('1', 0.9988571405410767), ("':", 0.9998384714126587), ("'", 0.9969496130943298), ('3', 0.43607938289642334), ("'}", 0.6757993102073669), ('\n', 0.9992454051971436), ('     ', 0.9856991171836853), ('}', 0.9998966455459595), ('\n', 0.9981671571731567), ('\n', 0.7941375970840454), ('     ', 0.9923465251922607), ('final', 0.7350393533706665), ('1', 0.8897825479507446), ('=', 0.9964898228645325), ("['", 0.9343020915985107), ('3', 0.3510397970676422), ("',", 0.6771765947341919), ("'", 0.997955322265625), ('1', 0.5705971717834473), ("',", 0.7805072069168091), ("'", 0.999104917049408), ('2', 0.7705345749855042), ("',", 0.8642817735671997), ('\n', 0.9967460632324219), ('     ', 0.9803066849708557), ('start', 0.978981077671051), ('1', 0.8538398742675781), ('=', 0.9979320764541626), ("'", 0.9881267547607422), ('0', 0.7881767153739929), ("'", 0.9986605644226074), ('\n', 0.9973993301391602), ('\n', 0.8715314865112305), ('     ', 0.9920124411582947), ('self', 0.9766848087310791), ('.', 0.999963641166687), ('assertEqual', 0.9844717383384705), ('(', 0.9963111281394958), ('False', 0.5505354404449463), (',', 0.9997938275337219), ('D', 0.9948059916496277), ('FA', 0.9997816681861877), ('(', 0.9874366521835327), ('trans', 0.9987637996673584), ('itions', 0.9999700784683228), ('1', 0.9656367301940918), (',', 0.999788224697113), ('start', 0.9974892139434814), ('1', 0.9911307096481323), (',', 0.9997645020484924), ('final', 0.9992699027061462), ('1', 0.9924973249435425), (',', 0.9976308345794678), ('"', 0.9562894105911255), ('0', 0.5340562462806702), ('0', 0.5790250301361084), ('0', 0.6153525114059448), ('1', 0.5995969176292419), ('1', 0.8613893389701843), ('1', 0.909350574016571), ('1', 0.9263013005256653), ('0', 0.9346288442611694), ('\n', 0.8739234805107117), ('     ', 0.9466267824172974), ('self', 0.9953371286392212), ('.', 0.9995846152305603), ('assertEqual', 0.9975436329841614), ('(', 0.9994598031044006), ('True', 0.7680222392082214), (',', 0.9996286630630493), ('D', 0.9969812035560608), ('FA', 0.999943733215332), ('(', 0.9998181462287903), ('trans', 0.9993056058883667), ('itions', 0.9999829530715942), ('1', 0.9929510354995728), (',', 0.9999537467956543), ('start', 0.9988719820976257), ('1', 0.9971135854721069), (',', 0.9999452829360962), ('final', 0.9996974468231201), ('1', 0.998051643371582), (',', 0.9991270899772644), ('"', 0.9958303570747375), ('1', 0.6097120642662048), ('0', 0.5599424242973328), ('0', 0.4336391091346741), ('1', 0.48386242985725403), ('0', 0.49813351035118103), ('1', 0.5882635116577148), ('0', 0.6400107145309448), ('1', 0.4913864731788635), ('0', 0.4474727213382721), ('\n', 0.6595420241355896), ('\n', 0.6834882497787476), ('     ', 0.6427462697029114), ('transitions', 0.8202254176139832), ('2', 0.9639526605606079), ('=', 0.9973164200782776), ('{', 0.975792407989502), ('\n', 0.9978961944580078), ('         ', 0.9811534881591797), ("'", 0.9732767343521118), ('0', 0.6062263250350952), ("':", 0.9876686930656433), ("{'", 0.9701467752456665), ('0', 0.8640525937080383), ("':", 0.9833078384399414), ("'", 0.9658005237579346), ('0', 0.36828985810279846), ("',", 0.8782898783683777), ("'", 0.992893397808075), ('b', 0.887968122959137), ("':", 0.9989307522773743), ("'", 0.9942300319671631), ('1', 0.42383256554603577), ("'},", 0.682108461856842), ('\n', 0.9982325434684753), ('         ', 0.9961611032485962), ("'", 0.9993367791175842), ('1', 0.988770604133606), ("':", 0.9995430707931519), ("{'", 0.9960119724273682), ('a', 0.9294162392616272), ("':", 0.9998655319213867), ("'", 0.9988001585006714), ('1', 0.49896812438964844), ("',", 0.9921196699142456), ("'", 0.9997455477714539), ('b', 0.997666597366333), ("':", 0.9998025298118591), ("'", 0.9989134073257446), ('1', 0.5573443174362183), ("'},", 0.7127736806869507), ('\n', 0.9997690320014954), ('         ', 0.9594940543174744), ("'", 0.9983130693435669), ('2', 0.9378260374069214), ("':", 0.9997795224189758), ("{'", 0.9965687990188599), ('a', 0.9890888333320618), ("':", 0.9998993873596191), ("'", 0.9984286427497864), ('0', 0.4874768555164337), ("',", 0.9842208623886108), ("'", 0.9995412826538086), ('b', 0.9991816878318787), ("':", 0.9997727274894714), ("'", 0.9976739287376404), ('3', 0.29202064871788025), ("'},", 0.876633882522583), ('\n', 0.9998018145561218), ('         ', 0.9849593043327332), ("'", 0.9993703961372375), ('3', 0.9921445250511169), ("':", 0.9998656511306763), ("{'", 0.9986557960510254), ('a', 0.99581378698349), ("':", 0.9998968839645386), ("'", 0.9977411031723022), ('3', 0.46761706471443176), ("',", 0.9953609108924866), ("'", 0.9998264908790588), ('b', 0.9997331500053406), ("':", 0.9998418092727661), ("'", 0.9979191422462463), ('3', 0.5687670707702637), ("'}", 0.8527544140815735), ('\n', 0.9997679591178894), ('     ', 0.9943758249282837), ('}', 0.9999698400497437), ('\n', 0.9987103939056396), ('\n', 0.9707968235015869), ('     ', 0.9973260164260864), ('final', 0.9778226017951965), ('2', 0.9950300455093384), ('=', 0.9987356066703796), ("['", 0.9647491574287415), ('0', 0.39536893367767334), ("']", 0.8586117625236511), ('\n', 0.99919193983078), ('     ', 0.9960987567901611), ('start', 0.9987982511520386), ('2', 0.9957291483879089), ('=', 0.99936443567276), ("'", 0.9966956377029419), ('0', 0.6907022595405579), ("'", 0.9994444251060486), ('\n', 0.9985516667366028), ('\n', 0.9701410531997681), ('     ', 0.9961258769035339), ('self', 0.9864029288291931), ('.', 0.9999902248382568), ('assertEqual', 0.9954904913902283), ('(', 0.9993532299995422), ('False', 0.7664465308189392), (',', 0.9999159574508667), ('D', 0.9981770515441895), ('FA', 0.9999921321868896), ('(', 0.9992676377296448), ('trans', 0.9995946288108826), ('itions', 0.999971866607666), ('2', 0.9893139600753784), (',', 0.9999117851257324), ('start', 0.9991397857666016), ('2', 0.9967058300971985), (',', 0.999919056892395), ('final', 0.9997263550758362), ('2', 0.9975464940071106), (',', 0.9990572333335876), ('"', 0.9874626994132996), ('0', 0.6679422855377197), ('a', 0.4292403757572174), ('bb', 0.5407735109329224), ('"))', 0.20841000974178314), ('\n', 0.9695752263069153), ('     ', 0.987919807434082), ('self', 0.9975570440292358), ('.', 0.9999558925628662), ('assertEqual', 0.9984405636787415), ('(', 0.9998534917831421), ('True', 0.7962279915809631), (',', 0.9998511075973511), ('D', 0.9985463619232178), ('FA', 0.9999790191650391), ('(', 0.999927282333374), ('trans', 0.9997594952583313), ('itions', 0.9999827146530151), ('2', 0.9958269000053406), (',', 0.999969482421875), ('start', 0.9995766282081604), ('2', 0.9980767965316772), (',', 0.9999738931655884), ('final', 0.9998743534088135), ('2', 0.9984596967697144), (',', 0.9996033310890198), ('"', 0.9980880618095398), ('aa', 0.22051097452640533), ('a', 0.3059263229370117), ('bb', 0.4371831715106964), ('"))', 0.4184962809085846), ('\n', 0.5329439640045166), ('\n', 0.9300780296325684), ('     ', 0.7465224266052246), ('def', 0.29760539531707764), ('__', 0.9812005162239075), ('name', 0.9997535347938538), ('__', 0.9995501637458801), ('==', 0.972819983959198), ("'", 0.6899797320365906), ('__', 0.9991993308067322), ('main', 0.9988371729850769), ('__', 0.9980504512786865), ("':", 0.99759441614151), ('\n', 0.9960785508155823), (' ', 0.9396867156028748), ('un', 0.7851546406745911), ('ittest', 0.9967731833457947), ('.', 0.9958030581474304), ('main', 0.9980183839797974), ('()', 0.9498602151870728), ('</s>', 0.9695735573768616), ('\n', 0.6550447344779968)]

In [20]:
assert tokenizer.decode(df_dataset['input_ids'][0]) == df_dataset[params['dataset']['content_column']][0]
df_dataset[params['dataset']['content_column']][0]

2024-09-29 15:18:20.656701: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-29 15:18:20.671149: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-29 15:18:20.675965: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-29 15:18:20.688307: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

'def test_DFA(self):\n        transitions = {\n            \'a\': {\'1\': \'a\', \'0\': \'b\'},\n            \'b\': {\'1\': \'b\', \'0\': \'a\'}\n        }\n\n        final = [\'a\']\n        start = \'a\'\n\n        self.assertEqual(False, DFA(transitions, start, final, "000111100"))\n        self.assertEqual(True, DFA(transitions, start, final, "111000011"))\n\n        transitions1 = {\n            \'0\': {\'0\': \'1\', \'1\': \'0\'},\n            \'1\': {\'0\': \'2\', \'1\': \'0\'},\n            \'2\': {\'0\': \'2\', \'1\': \'3\'},\n            \'3\': {\'0\': \'3\', \'1\': \'3\'}\n        }\n\n        final1 = [\'0\', \'1\', \'2\']\n        start1 = \'0\'\n\n        self.assertEqual(False, DFA(transitions1, start1, final1, "0001111"))\n        self.assertEqual(True, DFA(transitions1, start1, final1, "01010101"))\n\n        transitions2 = {\n            \'0\': {\'a\': \'0\', \'b\': \'1\'},\n            \'1\': {\'a\': \'0\', \'b\': \'2\'},\n            \'2\': {\'a\': \'3\', \'b\': \'2\'},\n            \'3\': {\'a\': \'3\', \'b\': \'3\'}\n        }\n\n        final2 = [\'3\']\n        start2 = \'0\'\n\n        self.assertEqual(False, DFA(transitions2, start2, final2, "aaabbb"))\n        self.assertEqual(True, DFA(transitions2, start2, final2, "baabba"))\n\n\nif __name__ == \'__main__\':\n    unittest.main()\n'

In [21]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

actual_cases = actual_logit(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out] , #Out is a complete sequence
    tokenized_prompt = input_ids_list[0], ## SAMPLE ID
    tokenizer_fn = tokenizer
    )
actual_cases

[('def', 0.00030555014382116497),
 ('test', 0.009959377348423004),
 ('_', 0.7111697196960449),
 ('D', 0.0002664475468918681),
 ('FA', 0.015310260467231274),
 ('(', 0.2075965702533722),
 ('self', 0.142356738448143),
 ('):', 0.7956698536872864),
 ('\n', 0.9903011322021484),
 ('     ', 0.2580970823764801),
 ('transitions', 0.00033252863795496523),
 ('=', 0.8424184322357178),
 ('{', 0.3088832497596741),
 ('\n', 0.7759588360786438),
 ('         ', 0.8008356690406799),
 ("'", 0.332145094871521),
 ('a', 0.2342398315668106),
 ("':", 0.9017483592033386),
 ("{'", 0.3621208071708679),
 ('1', 0.008214809000492096),
 ("':", 0.8090277314186096),
 ("'", 0.6437082290649414),
 ('a', 0.14299869537353516),
 ("',", 0.7275657057762146),
 ("'", 0.9586458802223206),
 ('0', 0.23419086635112762),
 ("':", 0.996057391166687),
 ("'", 0.9527722597122192),
 ('b', 0.6182431578636169),
 ("'},", 0.8787501454353333),
 ('\n', 0.9783669114112854),
 ('         ', 0.9917137622833252),
 ("'", 0.9982050657272339),
 ('b', 0.9849040508270264),
 ("':", 0.9993496537208557),
 ("{'", 0.9859283566474915),
 ('1', 0.8342114090919495),
 ("':", 0.9994694590568542),
 ("'", 0.9913591146469116),
 ('b', 0.4031481444835663),
 ("',", 0.9744338989257812),
 ("'", 0.9992467164993286),
 ('0', 0.9972277283668518),
 ("':", 0.9993991851806641),
 ("'", 0.9865380525588989),
 ('a', 0.33136165142059326),
 ("'}", 0.2996598780155182),
 ('\n', 0.9977586269378662),
 ('     ', 0.9680642485618591),
 ('}', 0.997857391834259),
 ('\n', 0.9981277585029602),
 ('\n', 0.2803206741809845),
 ('     ', 0.973686933517456),
 ('final', 0.006816547363996506),
 ('=', 0.09644414484500885),
 ("['", 0.13737663626670837),
 ('a', 0.5682030916213989),
 ("']", 0.3835836946964264),
 ('\n', 0.9797280430793762),
 ('     ', 0.41548964381217957),
 ('start', 0.17488427460193634),
 ('=', 0.8738885521888733),
 ("'", 0.8851250410079956),
 ('a', 0.9446073174476624),
 ("'", 0.998727023601532),
 ('\n', 0.9946613907814026),
 ('\n', 0.6561527848243713),
 ('     ', 0.9772368669509888),
 ('self', 0.11978500336408615),
 ('.', 0.9834739565849304),
 ('assertEqual', 0.4533636271953583),
 ('(', 0.919384241104126),
 ('False', 0.004470569081604481),
 (',', 0.9968687891960144),
 ('D', 0.0868300274014473),
 ('FA', 0.9827203750610352),
 ('(', 0.6894293427467346),
 ('trans', 0.7233177423477173),
 ('itions', 0.9997740387916565),
 (',', 0.9773522019386292),
 ('start', 0.19699567556381226),
 (',', 0.963057816028595),
 ('final', 0.964323878288269),
 (',', 0.2080453485250473),
 ('"', 0.053577132523059845),
 ('0', 0.37604960799217224),
 ('0', 0.3769347369670868),
 ('0', 0.299862265586853),
 ('1', 0.33394691348075867),
 ('1', 0.3867165744304657),
 ('1', 0.34038063883781433),
 ('1', 0.33129698038101196),
 ('0', 0.33787742257118225),
 ('0', 0.35265621542930603),
 ('"))', 0.1683112233877182),
 ('\n', 0.7402434945106506),
 ('     ', 0.4400995075702667),
 ('self', 0.9463321566581726),
 ('.', 0.999923586845398),
 ('assertEqual', 0.9923081398010254),
 ('(', 0.9934677481651306),
 ('True', 0.7299107313156128),
 (',', 0.9969683289527893),
 ('D', 0.9745734930038452),
 ('FA', 0.9998252987861633),
 ('(', 0.9978380799293518),
 ('trans', 0.998248815536499),
 ('itions', 0.9999830722808838),
 (',', 0.999855637550354),
 ('start', 0.995385468006134),
 (',', 0.9998063445091248),
 ('final', 0.9986746311187744),
 (',', 0.9980573058128357),
 ('"', 0.9934554696083069),
 ('1', 0.5589944124221802),
 ('1', 0.6052656769752502),
 ('1', 0.6971897482872009),
 ('0', 0.36543190479278564),
 ('0', 0.7350143194198608),
 ('0', 0.4018915295600891),
 ('0', 0.5647594928741455),
 ('1', 0.5884052515029907),
 ('1', 0.8227081298828125),
 ('"))', 0.903008222579956),
 ('\n', 0.6423302292823792),
 ('\n', 0.3881760537624359),
 ('     ', 0.17933428287506104),
 ('transitions', 0.30426251888275146),
 ('1', 0.019572444260120392),
 ('=', 0.9884184002876282),
 ('{', 0.9494293332099915),
 ('\n', 0.9943808913230896),
 ('         ', 0.9753065705299377),
 ("'", 0.9719103574752808),
 ('0', 0.09406274557113647),
 ("':", 0.9822317957878113),
 ("{'", 0.7888122200965881),
 ('0', 0.3483922481536865),
 ("':", 0.9884136319160461),
 ("'", 0.9700012803077698),
 ('1', 0.1424911916255951),
 ("',", 0.6202284693717957),
 ("'", 0.9884694218635559),
 ('1', 0.9772676825523376),
 ("':", 0.998090922832489),
 ("'", 0.9800103306770325),
 ('0', 0.545506477355957),
 ("'},", 0.7868120670318604),
 ('\n', 0.9947299957275391),
 ('         ', 0.9774352312088013),
 ("'", 0.9990290403366089),
 ('1', 0.9961087107658386),
 ("':", 0.9993680119514465),
 ("{'", 0.9910356998443604),
 ('0', 0.8169069886207581),
 ("':", 0.9998235106468201),
 ("'", 0.9979217648506165),
 ('2', 0.014611086808145046),
 ("',", 0.9885722398757935),
 ("'", 0.9995174407958984),
 ('1', 0.9959957599639893),
 ("':", 0.9996737241744995),
 ("'", 0.9953658580780029),
 ('0', 0.2945958375930786),
 ("'},", 0.2628838121891022),
 ('\n', 0.9995805621147156),
 ('         ', 0.7507445216178894),
 ("'", 0.9955295920372009),
 ('2', 0.9928144812583923),
 ("':", 0.9994248151779175),
 ("{'", 0.9935333728790283),
 ('0', 0.9579411149024963),
 ("':", 0.9997245669364929),
 ("'", 0.9908989667892456),
 ('2', 0.24309928715229034),
 ("',", 0.9905335903167725),
 ("'", 0.9997044205665588),
 ('1', 0.9980837106704712),
 ("':", 0.9997767806053162),
 ("'", 0.9962595701217651),
 ('3', 0.11112339794635773),
 ("'},", 0.6666712760925293),
 ('\n', 0.9997475743293762),
 ('         ', 0.9602823853492737),
 ("'", 0.998836100101471),
 ('3', 0.9982097148895264),
 ("':", 0.999711811542511),
 ("{'", 0.9965382814407349),
 ('0', 0.9859376549720764),
 ("':", 0.9997407793998718),
 ("'", 0.9941300749778748),
 ('3', 0.3987932503223419),
 ("',", 0.9935994148254395),
 ("'", 0.9996402263641357),
 ('1', 0.9988571405410767),
 ("':", 0.9998384714126587),
 ("'", 0.9969496130943298),
 ('3', 0.43607938289642334),
 ("'}", 0.6757993102073669),
 ('\n', 0.9992454051971436),
 ('     ', 0.9856991171836853),
 ('}', 0.9998966455459595),
 ('\n', 0.9981671571731567),
 ('\n', 0.7941375970840454),
 ('     ', 0.9923465251922607),
 ('final', 0.7350393533706665),
 ('1', 0.8897825479507446),
 ('=', 0.9964898228645325),
 ("['", 0.9343020915985107),
 ('0', 0.27147993445396423),
 ("',", 0.6771765947341919),
 ("'", 0.997955322265625),
 ('1', 0.5705971717834473),
 ("',", 0.7805072069168091),
 ("'", 0.999104917049408),
 ('2', 0.7705345749855042),
 ("']", 0.13289858400821686),
 ('\n', 0.9967460632324219),
 ('     ', 0.9803066849708557),
 ('start', 0.978981077671051),
 ('1', 0.8538398742675781),
 ('=', 0.9979320764541626),
 ("'", 0.9881267547607422),
 ('0', 0.7881767153739929),
 ("'", 0.9986605644226074),
 ('\n', 0.9973993301391602),
 ('\n', 0.8715314865112305),
 ('     ', 0.9920124411582947),
 ('self', 0.9766848087310791),
 ('.', 0.999963641166687),
 ('assertEqual', 0.9844717383384705),
 ('(', 0.9963111281394958),
 ('False', 0.5505354404449463),
 (',', 0.9997938275337219),
 ('D', 0.9948059916496277),
 ('FA', 0.9997816681861877),
 ('(', 0.9874366521835327),
 ('trans', 0.9987637996673584),
 ('itions', 0.9999700784683228),
 ('1', 0.9656367301940918),
 (',', 0.999788224697113),
 ('start', 0.9974892139434814),
 ('1', 0.9911307096481323),
 (',', 0.9997645020484924),
 ('final', 0.9992699027061462),
 ('1', 0.9924973249435425),
 (',', 0.9976308345794678),
 ('"', 0.9562894105911255),
 ('0', 0.5340562462806702),
 ('0', 0.5790250301361084),
 ('0', 0.6153525114059448),
 ('1', 0.5995969176292419),
 ('1', 0.8613893389701843),
 ('1', 0.909350574016571),
 ('1', 0.9263013005256653),
 ('"))', 0.012657725252211094),
 ('\n', 0.8739234805107117),
 ('     ', 0.9466267824172974),
 ('self', 0.9953371286392212),
 ('.', 0.9995846152305603),
 ('assertEqual', 0.9975436329841614),
 ('(', 0.9994598031044006),
 ('True', 0.7680222392082214),
 (',', 0.9996286630630493),
 ('D', 0.9969812035560608),
 ('FA', 0.999943733215332),
 ('(', 0.9998181462287903),
 ('trans', 0.9993056058883667),
 ('itions', 0.9999829530715942),
 ('1', 0.9929510354995728),
 (',', 0.9999537467956543),
 ('start', 0.9988719820976257),
 ('1', 0.9971135854721069),
 (',', 0.9999452829360962),
 ('final', 0.9996974468231201),
 ('1', 0.998051643371582),
 (',', 0.9991270899772644),
 ('"', 0.9958303570747375),
 ('0', 0.32891687750816345),
 ('1', 0.4228513836860657),
 ('0', 0.4336391091346741),
 ('1', 0.48386242985725403),
 ('0', 0.49813351035118103),
 ('1', 0.5882635116577148),
 ('0', 0.6400107145309448),
 ('1', 0.4913864731788635),
 ('"))', 0.4230369031429291),
 ('\n', 0.6595420241355896),
 ('\n', 0.6834882497787476),
 ('     ', 0.6427462697029114),
 ('transitions', 0.8202254176139832),
 ('2', 0.9639526605606079),
 ('=', 0.9973164200782776),
 ('{', 0.975792407989502),
 ('\n', 0.9978961944580078),
 ('         ', 0.9811534881591797),
 ("'", 0.9732767343521118),
 ('0', 0.6062263250350952),
 ("':", 0.9876686930656433),
 ("{'", 0.9701467752456665),
 ('a', 0.01672443002462387),
 ("':", 0.9833078384399414),
 ("'", 0.9658005237579346),
 ('0', 0.36828985810279846),
 ("',", 0.8782898783683777),
 ("'", 0.992893397808075),
 ('b', 0.887968122959137),
 ("':", 0.9989307522773743),
 ("'", 0.9942300319671631),
 ('1', 0.42383256554603577),
 ("'},", 0.682108461856842),
 ('\n', 0.9982325434684753),
 ('         ', 0.9961611032485962),
 ("'", 0.9993367791175842),
 ('1', 0.988770604133606),
 ("':", 0.9995430707931519),
 ("{'", 0.9960119724273682),
 ('a', 0.9294162392616272),
 ("':", 0.9998655319213867),
 ("'", 0.9988001585006714),
 ('0', 0.322115033864975),
 ("',", 0.9921196699142456),
 ("'", 0.9997455477714539),
 ('b', 0.997666597366333),
 ("':", 0.9998025298118591),
 ("'", 0.9989134073257446),
 ('2', 0.1600068211555481),
 ("'},", 0.7127736806869507),
 ('\n', 0.9997690320014954),
 ('         ', 0.9594940543174744),
 ("'", 0.9983130693435669),
 ('2', 0.9378260374069214),
 ("':", 0.9997795224189758),
 ("{'", 0.9965687990188599),
 ('a', 0.9890888333320618),
 ("':", 0.9998993873596191),
 ("'", 0.9984286427497864),
 ('3', 0.10585060715675354),
 ("',", 0.9842208623886108),
 ("'", 0.9995412826538086),
 ('b', 0.9991816878318787),
 ("':", 0.9997727274894714),
 ("'", 0.9976739287376404),
 ('2', 0.20075778663158417),
 ("'},", 0.876633882522583),
 ('\n', 0.9998018145561218),
 ('         ', 0.9849593043327332),
 ("'", 0.9993703961372375),
 ('3', 0.9921445250511169),
 ("':", 0.9998656511306763),
 ("{'", 0.9986557960510254),
 ('a', 0.99581378698349),
 ("':", 0.9998968839645386),
 ("'", 0.9977411031723022),
 ('3', 0.46761706471443176),
 ("',", 0.9953609108924866),
 ("'", 0.9998264908790588),
 ('b', 0.9997331500053406),
 ("':", 0.9998418092727661),
 ("'", 0.9979191422462463),
 ('3', 0.5687670707702637),
 ("'}", 0.8527544140815735),
 ('\n', 0.9997679591178894),
 ('     ', 0.9943758249282837),
 ('}', 0.9999698400497437),
 ('\n', 0.9987103939056396),
 ('\n', 0.9707968235015869),
 ('     ', 0.9973260164260864),
 ('final', 0.9778226017951965),
 ('2', 0.9950300455093384),
 ('=', 0.9987356066703796),
 ("['", 0.9647491574287415),
 ('3', 0.12511439621448517),
 ("']", 0.8586117625236511),
 ('\n', 0.99919193983078),
 ('     ', 0.9960987567901611),
 ('start', 0.9987982511520386),
 ('2', 0.9957291483879089),
 ('=', 0.99936443567276),
 ("'", 0.9966956377029419),
 ('0', 0.6907022595405579),
 ("'", 0.9994444251060486),
 ('\n', 0.9985516667366028),
 ('\n', 0.9701410531997681),
 ('     ', 0.9961258769035339),
 ('self', 0.9864029288291931),
 ('.', 0.9999902248382568),
 ('assertEqual', 0.9954904913902283),
 ('(', 0.9993532299995422),
 ('False', 0.7664465308189392),
 (',', 0.9999159574508667),
 ('D', 0.9981770515441895),
 ('FA', 0.9999921321868896),
 ('(', 0.9992676377296448),
 ('trans', 0.9995946288108826),
 ('itions', 0.999971866607666),
 ('2', 0.9893139600753784),
 (',', 0.9999117851257324),
 ('start', 0.9991397857666016),
 ('2', 0.9967058300971985),
 (',', 0.999919056892395),
 ('final', 0.9997263550758362),
 ('2', 0.9975464940071106),
 (',', 0.9990572333335876),
 ('"', 0.9874626994132996),
 ('aa', 0.010533912107348442),
 ('ab', 0.3075968325138092),
 ('bb', 0.5407735109329224),
 ('"))', 0.20841000974178314),
 ('\n', 0.9695752263069153),
 ('     ', 0.987919807434082),
 ('self', 0.9975570440292358),
 ('.', 0.9999558925628662),
 ('assertEqual', 0.9984405636787415),
 ('(', 0.9998534917831421),
 ('True', 0.7962279915809631),
 (',', 0.9998511075973511),
 ('D', 0.9985463619232178),
 ('FA', 0.9999790191650391),
 ('(', 0.999927282333374),
 ('trans', 0.9997594952583313),
 ('itions', 0.9999827146530151),
 ('2', 0.9958269000053406),
 (',', 0.999969482421875),
 ('start', 0.9995766282081604),
 ('2', 0.9980767965316772),
 (',', 0.9999738931655884),
 ('final', 0.9998743534088135),
 ('2', 0.9984596967697144),
 (',', 0.9996033310890198),
 ('"', 0.9980880618095398),
 ('ba', 0.010125980712473392),
 ('ab', 0.2090398669242859),
 ('ba', 0.129971444606781),
 ('"))', 0.4184962809085846),
 ('\n', 0.5329439640045166),
 ('\n', 0.9300780296325684),
 ('\n', 0.10698136687278748),
 ('if', 0.02752009965479374),
 ('__', 0.9812005162239075),
 ('name', 0.9997535347938538),
 ('__', 0.9995501637458801),
 ('==', 0.972819983959198),
 ("'", 0.6899797320365906),
 ('__', 0.9991993308067322),
 ('main', 0.9988371729850769),
 ('__', 0.9980504512786865),
 ("':", 0.99759441614151),
 ('\n', 0.9960785508155823),
 (' ', 0.9396867156028748),
 ('un', 0.7851546406745911),
 ('ittest', 0.9967731833457947),
 ('.', 0.9958030581474304),
 ('main', 0.9980183839797974),
 ('()', 0.9498602151870728),
 ('\n', 0.028569869697093964)]

#### Processing all the Batches

In [22]:
def batching_logits(tokenizer,tf_input_ids,size=10000):
    max_logit_token_prompt = []
    min_logit_token_prompt = []
    actual_logit_token_prompt = []

    
    soft = torch.nn.Softmax( dim = 0 )                          #Flattening normalization
    
    for file in range( size ):
        out = np.load(params['callbacks_dir']+ '/'+ params['current_model'] + '_q_' + params['quantization'] +'/'+ f'logits_tensor[{file}]_batch[{file}].npy') #<sample,tokens,voc_tokens>
        out = out[0]  ##### #<tokens,voc_tokens>
        next_tokens_distribution = [ soft( torch.from_numpy(token) ) for token in out]  #Flattening normalization
        
        max_cases,min_cases = min_max_logits(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenizer_fn= tokenizer
            )

        actual_cases = actual_logit(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenized_prompt = tf_input_ids[ file ],
            tokenizer_fn = tokenizer
            )
        
        max_logit_token_prompt.append( max_cases )
        min_logit_token_prompt.append( min_cases )
        actual_logit_token_prompt.append( actual_cases )
        
        logging.info(file)
    return max_logit_token_prompt,min_logit_token_prompt,actual_logit_token_prompt

In [23]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

In [24]:
max_logit_token_prompt, min_logit_token_prompt, actual_logit_token_prompt = batching_logits(
    tokenizer=tokenizer , tf_input_ids=input_ids_list, 
    size = len(df_dataset)
) #<---WARNING TIME Consuming

#### Saving results

In [25]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [26]:
dataframe_to_save = df_dataset.copy()
dataframe_to_save['max_prob'] = max_logit_token_prompt
dataframe_to_save['min_prob'] = min_logit_token_prompt
dataframe_to_save['actual_prob'] = actual_logit_token_prompt
dataframe_to_save.shape

(55, 30)

In [27]:
dataframe_to_save.head(5)

,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,repo,...,vocab_size,nloc,token_counts,n_identifiers,repository,year,input_ids,max_prob,min_prob,actual_prob
0,C0103,1,0,1,12,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,64,29,264,16,algorithms,outputs-22,"[1569, 2137, 29498, 29525, 3888, 29500, 1712, ...","[(#, 0.2665287256240845), (solution, 0.0588438...","[(–,, 3.8730735285597007e-10), (/***/, 1.16526...","[(def, 0.00030555014382116497), (test, 0.00995..."
1,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[1569, 2137, 29498, 2933, 29498, 2569, 29498, ...","[(#, 0.26652711629867554), (solution, 0.058844...","[(–,, 3.87315374217323e-10), (/***/, 1.1652591...","[(def, 0.00030555526609532535), (test, 0.00995..."
2,C0103,3,8,3,9,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[1569, 2137, 29498, 2933, 29498, 2569, 29498, ...","[(#, 0.26652711629867554), (solution, 0.058844...","[(–,, 3.87315374217323e-10), (/***/, 1.1652591...","[(def, 0.00030555526609532535), (test, 0.00995..."
3,C0103,4,8,4,9,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[1569, 2137, 29498, 2933, 29498, 2569, 29498, ...","[(#, 0.26652711629867554), (solution, 0.058844...","[(–,, 3.87315374217323e-10), (/***/, 1.1652591...","[(def, 0.00030555526609532535), (test, 0.00995..."
4,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,30,11,117,11,algorithms,outputs-22,"[1569, 2137, 29498, 11329, 29498, 2933, 29498,...","[(#, 0.2665267884731293), (solution, 0.0588442...","[(–,, 3.8731712281858677e-10), (/***/, 1.16526...","[(def, 0.0003055557608604431), (test, 0.009959..."

In [28]:
create_folder(params['output_path'] + '/' + params['current_model'] + '_q_' + params['quantization'])
dataframe_to_save.to_csv( params['output_path'] + '/' + params['current_model'] + '_q_' + params['quantization'] + '/' + 'raw_logits.csv')

#### Loss Retrieval

In [29]:
def batching_loss( size = dataframe_to_save.shape[0] ):
    output_loss = []
    for current_batch in range(size):
        out = np.load(params['callbacks_dir']+ '/'+ params['current_model'] +  '_q_' + params['quantization'] +'/' + f'_loss_batch[{current_batch}].npy') 
        output_loss.append( out.item() ) #.item() for numpy library
        logging.info(current_batch)
    return output_loss

In [30]:
output_loss = batching_loss() #[WAENING!] Takes Time

In [31]:
output_loss

[0.4558630585670471,
 0.6256284117698669,
 0.6256284117698669,
 0.6256284117698669,
 0.7624989151954651,
 0.7624989151954651,
 0.7624989151954651,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.6819478273391724,
 0.8713245987892151,
 0.25881484150886536,
 1.7146179676055908,
 1.5688334703445435,
 1.704850196838379,
 0.8083615899085999,
 1.0826220512390137,
 1.163515329360962,
 0.5581451654434204,
 0.5581451654434204,
 0.5581451654434204,
 0.5581451654434204,
 0.5581451654434204,
 0.5581451654434204,
 1.1955304145812988,
 1.1140497922897339,
 1.7491703033447266,
 1.8386893272399902,
 1.8386893272399902,
 1.63716459274292,
 1.63716459274292,
 2.856851100921631,
 0.8664145469665527,
 0.8664145469665527,
 0.5473245978355408,
 0.5473245978355408,
 0.9799413681030273,
 0.7896794080734253,
 0.8672385811805725,
 1.1682058572769165,
 1.4245681762695312,
 1.4245681762695312,
 0.6229621171951294,
 0.6229621171951294,
 0.6229621171951294,
 0.9163956046104431,
 0.9163956046104431,
 0.9163956046104431]

In [32]:
dataframe_to_save['loss'] = output_loss
dataframe_to_save.head(5)

,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,repo,...,nloc,token_counts,n_identifiers,repository,year,input_ids,max_prob,min_prob,actual_prob,loss
0,C0103,1,0,1,12,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,29,264,16,algorithms,outputs-22,"[1569, 2137, 29498, 29525, 3888, 29500, 1712, ...","[(#, 0.2665287256240845), (solution, 0.0588438...","[(–,, 3.8730735285597007e-10), (/***/, 1.16526...","[(def, 0.00030555014382116497), (test, 0.00995...",0.455863
1,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[1569, 2137, 29498, 2933, 29498, 2569, 29498, ...","[(#, 0.26652711629867554), (solution, 0.058844...","[(–,, 3.87315374217323e-10), (/***/, 1.1652591...","[(def, 0.00030555526609532535), (test, 0.00995...",0.625628
2,C0103,3,8,3,9,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[1569, 2137, 29498, 2933, 29498, 2569, 29498, ...","[(#, 0.26652711629867554), (solution, 0.058844...","[(–,, 3.87315374217323e-10), (/***/, 1.1652591...","[(def, 0.00030555526609532535), (test, 0.00995...",0.625628
3,C0103,4,8,4,9,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[1569, 2137, 29498, 2933, 29498, 2569, 29498, ...","[(#, 0.26652711629867554), (solution, 0.058844...","[(–,, 3.87315374217323e-10), (/***/, 1.1652591...","[(def, 0.00030555526609532535), (test, 0.00995...",0.625628
4,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,117,11,algorithms,outputs-22,"[1569, 2137, 29498, 11329, 29498, 2933, 29498,...","[(#, 0.2665267884731293), (solution, 0.0588442...","[(–,, 3.8731712281858677e-10), (/***/, 1.16526...","[(def, 0.0003055557608604431), (test, 0.009959...",0.762499

In [33]:
## Saving CheckPoint 2
dataframe_to_save.to_csv( params['output_path'] + '/' + params['current_model'] + '_q_' + params['quantization'] + '/' + 'raw_logits.csv')

In [34]:
torch.cuda.empty_cache()
gc.collect()

154