# Logits Preprocessing and Data Engineering

In [1]:
def default_params(): 
    return {
        'current_model': 'M1', 
        'quantization': 'none', #['none',"int4", "int8", "float32", "float16"]
        'dataset': {
            'path': '/workspaces/CodeSmells/datax/code_smells/generation/dataset',
            #['greedy_search', 'beam_search', 'sampling', 'contrastive_search', 'top_k_sampling', 'top_p_sampling']
            'decoding_strategy': 'greedy_search',
            'content_column': 'code',
            'sampling_size': 500,
        },
        'logging_path': '/workspaces/CodeSmells/datax/code_smells/logs/generation', 
        'output_path' : '/workspaces/CodeSmells/datax/code_smells/logits/generation',
        'callbacks_path' : '/workspaces/CodeSmells/datax/code_smells/callbacks/generation',
        'cache_dir': '/workspaces/CodeSmells/datax/hugging_face_cache',
        'causal_models': {
            'M1' : 'codellama/CodeLlama-7b-hf', #https://huggingface.co/codellama/CodeLlama-7b-hf, 
        },
    }
params = default_params()

#### Imports

In [2]:
import pandas as pd
import os
import time
import numpy as np
import torch
import gc

In [3]:
import seaborn as sns
from scipy import stats
from statistics import NormalDist
import matplotlib.pyplot as plt

In [4]:
from transformers import CodeLlamaTokenizer, LlamaForCausalLM
from datasets import load_dataset

In [5]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [6]:
# Define log file path
log_file = f"{params['logging_path']}/{params['current_model']}/{params['dataset']['decoding_strategy']}"
create_folder(log_file)
log_file += '/data_en.txt'

# Create the log file if it doesn't exist
if not os.path.exists(log_file):
    with open(log_file, 'w'): 
        pass  # Create an empty log file

In [7]:
import logging
logging.basicConfig(filename=log_file, format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

#### Dataset

In [10]:
print(f"{params['dataset']['path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['decoding_strategy']}_resampled_{params['dataset']['sampling_size']}.json")

/workspaces/CodeSmells/datax/code_smells/generation/dataset/M1_q_none/greedy_search_resampled_500.json

In [12]:
df_dataset = pd.read_json(f"{params['dataset']['path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['decoding_strategy']}_resampled_{params['dataset']['sampling_size']}.json", )

In [13]:
df_dataset

,id,commit_id,repo,path,file_name,commit_message,url,language,category,prompt,...,vocab_size,fun_name,complexity,nloc,token_counts,ast_errors,ast_levels,n_ast_nodes,n_ast_errors,n_identifiers
0,258876,1fc86b6aacd89da44a3b4e8abf7c3e2ba4336ffe,scikit-learn,sklearn/feature_selection/_univariate_selectio...,_univariate_selection.py,MNT Update black to stable version (#22474),https://github.com/scikit-learn/scikit-learn.git,Python,Convention,complete the following incomplete Python funct...,...,82,r_regression,8.0,29.0,271.0,[],15,434,0,31
1,172936,73d359af05701cb1cf2ace7dee26f14ea7238cb4,calibre-web,cps/gdriveutils.py,gdriveutils.py,Bugfix logging with gdrive\nUpdate optional-re...,https://github.com/janeczku/calibre-web.git,Python,Convention,complete the following incomplete Python funct...,...,38,getEbooksFolderId,3.0,14.0,83.0,[],14,296,0,21
2,176213,5dfd57af2a141a013ae3753e160180b82bec9469,networkx,networkx/tests/test_convert_scipy.py,test_convert_scipy.py,Use scipy.sparse array datastructure (#5139)\n...,https://github.com/networkx/networkx.git,Python,Convention,complete the following incomplete Python funct...,...,31,identity_conversion,1.0,22.0,271.0,[],10,414,0,22
3,258686,9f85c9d44965b764f40169ef2917e5f7a798684f,scikit-learn,sklearn/metrics/tests/test_pairwise.py,test_pairwise.py,TST Better info when checking for no warnings ...,https://github.com/scikit-learn/scikit-learn.git,Python,Convention,complete the following incomplete Python funct...,...,63,test_pairwise_boolean_distance,3.0,15.0,153.0,[],13,370,0,24
4,199358,06c66d6c69c6fe7955854a615956242d680f6b9a,sympy,sympy/physics/mechanics/tests/test_joint.py,test_joint.py,Add tests for intermediate frame and joint axi...,https://github.com/sympy/sympy.git,Python,Convention,complete the following incomplete Python funct...,...,60,test_pinjoint_axis,1.0,31.0,412.0,[],13,585,0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24063,197310,65be461082dda54c8748922f9c29a19af1279fe1,sympy,sympy/core/basic.py,basic.py,Remove abbreviations in documentation,https://github.com/sympy/sympy.git,Python,Convention,complete the following incomplete Python funct...,...,92,replace._replace,4.0,6.0,56.0,[],20,752,0,32
24064,197310,65be461082dda54c8748922f9c29a19af1279fe1,sympy,sympy/core/basic.py,basic.py,Remove abbreviations in documentation,https://github.com/sympy/sympy.git,Python,Convention,complete the following incomplete Python funct...,...,92,replace._replace,4.0,6.0,56.0,[],20,752,0,32
24065,197310,65be461082dda54c8748922f9c29a19af1279fe1,sympy,sympy/core/basic.py,basic.py,Remove abbreviations in documentation,https://github.com/sympy/sympy.git,Python,Convention,complete the following incomplete Python funct...,...,92,replace._replace,4.0,6.0,56.0,[],20,752,0,32
24066,197310,65be461082dda54c8748922f9c29a19af1279fe1,sympy,sympy/core/basic.py,basic.py,Remove abbreviations in documentation,https://github.com/sympy/sympy.git,Python,Convention,complete the following incomplete Python funct...,...,92,replace._replace,4.0,6.0,56.0,[],20,752,0,32
24067,197310,65be461082dda54c8748922f9c29a19af1279fe1,sympy,sympy/core/basic.py,basic.py,Remove abbreviations in documentation,https://github.com/sympy/sympy.git,Python,Convention,complete the following incomplete Python funct...,...,92,replace._replace,4.0,6.0,56.0,[],20,752,0,32

#### Model Loading

In [14]:
def instantiate_llm(model_name:str, cache_dir:str):
     '''Instantiate AutoModelForCausalLM'''
     tokenizer = CodeLlamaTokenizer.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoTokenizer - " + model_name)
     model = None
     if params['quantization'] == 'int4':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_4bit=True)
     elif params['quantization'] == 'int8':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_8bit=True)
     elif params['quantization'] == 'float32':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float32)
     elif params['quantization'] == 'float16':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float16)
     else: 
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoModelForCausalLM - " + model_name)

     return tokenizer, model

In [15]:
tokenizer, model = instantiate_llm(params['causal_models'][params['current_model']], params['cache_dir'])

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [16]:
model.config

LlamaConfig {
  "_name_or_path": "codellama/CodeLlama-7b-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 16384,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 1000000,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32016
}

#### preprocess dataset

In [17]:
df_dataset['input_ids'] = df_dataset[params['dataset']['content_column']].map(lambda code: tokenizer.encode(code, add_special_tokens=False))
df_dataset['input_lenght'] = df_dataset['input_ids'].map(lambda input_ids: len(input_ids))

#### Softmax Normalization and Data Engineering

In [18]:
def topk_tuple( logit_vocab_tensor, largest, tokenizer_fn):
    "Run topk for a token"
    topk = logit_vocab_tensor.topk( k=1 , largest=largest ) #TODO K number of elements can be extended
    return ( tokenizer.convert_tokens_to_string([tokenizer_fn.decode(topk.indices)]), topk.values.item())

def min_max_logits( logit_vocab_sample_tensor, tokenizer_fn ):
    "Compute min_max for a sample"
    max_cases = []
    min_cases = []
    for logit_vocab_tensor in logit_vocab_sample_tensor:
        max_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = True, tokenizer_fn = tokenizer_fn) ) #TST Max Logit
        min_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = False, tokenizer_fn = tokenizer_fn) ) #TST Min Logit
    return max_cases, min_cases

def actual_logit( 
                 logit_vocab_sample_tensor, 
                 tokenized_prompt, 
                 tokenizer_fn,
                 ):
    "Compute actual logits for a sample"
    actual_logits_prompt = []
    for token_pos, id_token in enumerate( tokenized_prompt[1:] ): #Eliminate the first token prediction since we do not use it
        actual_logits_prompt.append(
            (   tokenizer.convert_tokens_to_string([tokenizer_fn.decode( int(id_token))]), #retrieving the name of the token with the id
                logit_vocab_sample_tensor[token_pos][int(id_token)].item()) #retrieving the logit given the position in the sequence and the position in the vocab
            )
    return actual_logits_prompt

In [19]:
soft = torch.nn.Softmax( dim = 0 ) #Flattening normalization

In [20]:
callbacks_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['decoding_strategy']}"
out = np.load(f"{callbacks_dir}/logits_tensor[0]_batch[0].npy")

print(out.shape) #<sample,tokens,voc_tokens>
out = out[0]

(1, 530, 32016)

In [21]:
max_case,min_case = min_max_logits(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out], ####### 
    tokenizer_fn= tokenizer
    )
print(max_case)
assert len(max_case) == len(min_case)

[('<PRE>', 0.7492900490760803), ('module', 0.4794413447380066), ('pc', 0.05789488926529884), ('to', 0.03000357560813427), ('pr', 0.17619311809539795), ('(', 0.49110478162765503), ('x', 0.18413327634334564), (',', 0.7837546467781067), ('y', 0.4663568139076233), (',', 0.6742437481880188), ('l', 0.09025975316762924), ('args', 0.6018639206886292), ('l', 0.09314790368080139), ('=', 0.5727004408836365), ('True', 0.5564004182815552), (',', 0.8445126414299011), ('scale', 0.42541635036468506), ('_', 0.7570435404777527), ('center', 0.1138191744685173), ('=', 0.9234257340431213), ('True', 0.7369109988212585), (',', 0.6918704509735107), ('\n', 0.9534211158752441), ('  ', 0.8947504758834839), ('\n', 0.9500458836555481), ('  ', 0.962658166885376), ('"""', 0.1965550184249878), ('=', 0.5694356560707092), ('y', 0.9107635617256165), ('=', 0.8795614242553711), ('check', 0.45211222767829895), ('_', 0.9926853179931641), ('X', 0.7585020661354065), ('_', 0.9899470210075378), ('y', 0.9985018968582153), ('(', 0.9936887621879578), ('X', 0.9682533144950867), (',', 0.9940112233161926), ('y', 0.9895937442779541), (',', 0.8327682018280029), ('accept', 0.3503636419773102), ('_', 0.9988272786140442), ('s', 0.9915286302566528), ('parse', 0.9995672106742859), ('=', 0.9098601937294006), ('True', 0.4934219419956207), ('cs', 0.9180654287338257), ('r', 0.9998188614845276), ('",', 0.9022738933563232), ('"', 0.9934238195419312), ('c', 0.9910041093826294), ('sc', 0.9999805688858032), ('"],', 0.5123311281204224), ('"', 0.9847519993782043), ('co', 0.9791660904884338), ('o', 0.999893307685852), ('"],', 0.5480908751487732), ('\n', 0.4069526493549347), ('=', 0.6953261494636536), ('None', 0.4659363329410553), ('.', 0.9987038373947144), ('float', 0.9613701105117798), ('6', 0.8718473315238953), ('4', 0.9999958276748657), (',', 0.49850091338157654), ('\n', 0.9865104556083679), ('  ', 0.4172475337982178), ('if', 0.3304949998855591), ('_', 0.9120565056800842), ('samples', 0.7544899582862854), (',', 0.8518290519714355), ('X', 0.7211654782295227), ('.', 0.9984862804412842), ('shape', 0.9993509650230408), ('[', 0.9989560842514038), ('0', 0.9978376030921936), (']', 0.9990909099578857), ('\n', 0.9903761744499207), ('  ', 0.5767817497253418), ('  ', 0.9845446348190308), ('if', 0.5218697786331177), ('Center', 0.08629065006971359), ('e', 0.9731297492980957), ('the', 0.31298935413360596), ('X', 0.6050500869750977), ('\n', 0.49346378445625305), ('  ', 0.984738826751709), ('if', 0.6932873129844666), ('X', 0.0760330781340599), (':', 0.684384286403656), ('we', 0.19789157807826996), ('[', 0.24903811514377594), ('X', 0.6849310398101807), ('-', 0.5316087007522583), ('mean', 0.2363666445016861), ('(', 0.7420043349266052), ('x', 0.9291857481002808), ('))', 0.9626831412315369), ('^', 0.4551805555820465), ('y', 0.9108766317367554), ('-', 0.9659267067909241), ('mean', 0.9762095808982849), ('(', 0.9953470826148987), ('y', 0.9955958724021912), ('))]', 0.920138955116272), ('=', 0.6488011479377747), ('E', 0.5962879657745361), ('[', 0.8997237086296082), ('x', 0.7205336093902588), ('*', 0.9211128354072571), ('y', 0.9901363253593445), ('-', 0.9192156195640564), ('mean', 0.9002822041511536), ('(', 0.9843617677688599), ('y', 0.9958815574645996), ('))]', 0.9377137422561646), ('-', 0.6487535238265991), ('\n', 0.47130173444747925), ('\n', 0.24306024610996246), ('can', 0.3612385094165802), ('  ', 0.9993389248847961), ('#', 0.9998130202293396), ('can', 0.24058328568935394), ('to', 0.7677232623100281), ('center', 0.4617106318473816), ('y', 0.6476234197616577), ('.', 0.400613009929657), ('  ', 0.8931682705879211), ('if', 0.5958297848701477), ('center', 0.7577549815177917), (':', 0.9699742794036865), ('\n', 0.9882383942604065), ('      ', 0.9778000116348267), ('X', 0.2944525480270386), ('_', 0.38809290528297424), ('y', 0.8482464551925659), ('-', 0.9446906447410583), ('np', 0.5826309323310852), ('.', 0.9986144304275513), ('aver', 0.5624054670333862), ('(', 0.9990711212158203), ('y', 0.9984264373779297), (')', 0.860521674156189), ('\n', 0.9818989038467407), ('\n', 0.6438818573951721), ('X', 0.3739317059516907), ('force', 0.8908231258392334), ('parse', 0.9928327798843384), ('(', 0.9905065894126892), ('X', 0.8441720008850098), ('):', 0.9687318801879883), ('\n', 0.9840208888053894), ('          ', 0.9954694509506226), ('X', 0.5903856158256531), ('=', 0.4331813156604767), ('mean', 0.4211786687374115), ('ans', 0.9970138072967529), ('=', 0.985230028629303), ('X', 0.3525844216346741), ('.', 0.9442490935325623), ('mean', 0.9094809293746948), ('(', 0.9982339143753052), ('axis', 0.9494960904121399), ('=', 0.9969950914382935), ('0', 0.9789137840270996), (')', 0.5574132800102234), ('A', 0.765407383441925), ('A', 0.9899405837059021), ('1', 0.9979212880134583), ('()', 0.9859300255775452), ('\n', 0.9399358630180359), ('      ', 0.6895958185195923), ('else', 0.9911351203918457), (':', 0.9991838335990906), ('\n', 0.9961102604866028), ('          ', 0.998494029045105), ('X', 0.9942038655281067), ('_', 0.9981063604354858), ('me', 0.9987072944641113), ('ans', 0.9993403553962708), ('=', 0.9984044432640076), ('X', 0.5912094712257385), ('.', 0.9991658926010132), ('mean', 0.9997232556343079), ('(', 0.9989737272262573), ('axis', 0.9791942238807678), ('=', 0.9995527863502502), ('0', 0.9992795586585999), (')', 0.9883139133453369), ('\n', 0.9904910326004028), ('      ', 0.7179279923439026), ('X', 0.8254351615905762), ('Note', 0.07801436632871628), ('e', 0.9725230932235718), ('the', 0.1416737288236618), ('centered', 0.101081982254982), ('d', 0.3126679062843323), ('X', 0.11528346687555313), ('deviation', 0.3848290741443634), ('ations', 0.9940329194068909), ('of', 0.5236849784851074), ('the', 0.7595716714859009), ('\n', 0.30729085206985474), ('      ', 0.9939178228378296), ('#', 0.31966397166252136), ('_', 0.7407935857772827), ('std', 0.6660105586051941), ('=', 0.5729367733001709), ('=', 0.9742979407310486), ('np', 0.5227304697036743), ('.', 0.9980632662773132), ('sqrt', 0.6538915038108826), ('((', 0.5207743644714355), ('\n', 0.45206302404403687), ('_', 0.9989452958106995), ('norm', 0.99724942445755), ('s', 0.9961996674537659), ('(', 0.9971194267272949), ('X', 0.9862668514251709), (',', 0.8339421153068542), ('T', 0.332500696182251), (',', 0.515108585357666), ('squ', 0.9847097992897034), ('ared', 0.9998606443405151), ('=', 0.9985867738723755), ('True', 0.9929303526878357), (')', 0.4373514950275421), ('/', 0.8521211743354797), ('X', 0.48731565475463867), ('_', 0.9993330836296082), ('samples', 0.9992639422416687), ('*', 0.8356918692588806), ('X', 0.5777639746665955), ('_', 0.9980005621910095), ('me', 0.9997733235359192), ('ans', 0.9997392296791077), ('**', 0.7533315420150757), ('X', 0.9707205891609192), ('_', 0.9993865489959717), ('me', 0.9995751976966858), ('ans', 0.9976844787597656), (')', 0.8300114870071411), ('\n', 0.9760091304779053), ('      ', 0.5472725033760071), ('X', 0.3217059075832367), ('_', 0.5064075589179993), ('norm', 0.5027255415916443), ('s', 0.9788424372673035), ('[', 0.8077937960624695), ('X', 0.7765548825263977), ('_', 0.9991416931152344), ('norm', 0.9997690320014954), ('s', 0.9996110796928406), ('==', 0.6666505336761475), ('', 0.9875324368476868), ('0', 0.9996471405029297), (']', 0.47754985094070435), ('0', 0.9991801381111145), (']', 0.9988213181495667), ('=', 0.9915881752967834), ('', 0.9448598027229309), ('1', 0.9947752952575684), ('.', 0.9493046998977661), ('0', 0.9797582626342773), ('\n', 0.8296047449111938), ('      ', 0.5093404650688171), ('X', 0.6306172013282776), ('=', 0.7451503276824951), ('X', 0.5434690713882446), ('/', 0.6473486423492432), ('X', 0.9719201922416687), ('_', 0.9989801049232483), ('norm', 0.9994082450866699), ('s', 0.998853325843811), ('\n', 0.5715194344520569), ('      ', 0.35396328568458557), ('else', 0.7873696684837341), (':', 0.9987198114395142), ('\n', 0.984889030456543), ('      ', 0.9941845536231995), ('X', 0.6364556550979614), ('_', 0.8907188177108765), ('me', 0.938082754611969), ('ans', 0.9985014200210571), ('=', 0.934043288230896), ('np', 0.6135618090629578), ('.', 0.9991574287414551), ('zer', 0.9314483404159546), ('os', 0.9991784691810608), ('(', 0.8850137591362), ('X', 0.7173984050750732), ('.', 0.9962267875671387), ('shape', 0.9997125267982483), ('[', 0.9920992851257324), ('1', 0.9630857706069946), ('])', 0.6484161615371704), ('\n', 0.9899998307228088), ('      ', 0.48305174708366394), ('  ', 0.9780239462852478), ('#', 0.567473828792572), ('Comput', 0.10053089261054993), ('e', 0.9956986904144287), ('the', 0.32369863986968994), ('design', 0.06609194725751877), ('matrix', 0.914018452167511), ('\n', 0.300182580947876), ('  ', 0.9856303334236145), ('X', 0.37107956409454346), ('iss', 0.5057779550552368), ('parse', 0.9996328353881836), ('(', 0.998953104019165), ('X', 0.9949808716773987), ('):', 0.9728975892066956), ('\n', 0.9930338859558105), ('      ', 0.9915831685066223), ('X', 0.6186857223510742), ('_', 0.47425419092178345), ('cols', 0.09475232660770416), ('ed', 0.8975473046302795), ('=', 0.9642708897590637), ('X', 0.7295427322387695), ('.', 0.5536623597145081), ('copy', 0.5529422760009766), ('()', 0.9103391766548157), ('\n', 0.9676773548126221), ('      ', 0.5701210498809814), ('X', 0.5691580176353455), ('_', 0.9841669201850891), ('center', 0.9561602473258972), ('ed', 0.9990321397781372), ('.', 0.9743281602859497), ('data', 0.9881397485733032), ('-=', 0.4623633921146393), ('X', 0.8509217500686646), ('_', 0.9342305064201355), ('me', 0.9530187249183655), ('ans', 0.9987105131149292), ('\n', 0.7440929412841797), ('  ', 0.6855424642562866), ('else', 0.9703865051269531), (':', 0.9984819293022156), ('\n', 0.995128870010376), ('      ', 0.9980206489562988), ('X', 0.9696429371833801), ('_', 0.9932696223258972), ('center', 0.9966076612472534), ('ed', 0.99669349193573), ('=', 0.9976285099983215), ('X', 0.8843185901641846), ('-', 0.8085638880729675), ('X', 0.9372349381446838), ('_', 0.9899084568023682), ('me', 0.9987143278121948), ('ans', 0.9992743134498596), ('\n', 0.8783270120620728), ('\n', 0.7673149704933167), ('  ', 0.9846394062042236), ('#', 0.6775290369987488), ('Comput', 0.162695050239563), ('e', 0.9976087808609009), ('the', 0.6611243486404419), ('regression', 0.14245104789733887), ('coefficients', 0.3693326413631439), ('\n', 0.7221249938011169), ('  ', 0.9844607710838318), ('if', 0.2834618389606476), ('force', 0.5720871090888977), ('_', 0.9977871179580688), ('finite', 0.9300464391708374), (':', 0.9371045827865601), ('\n', 0.9937094449996948), ('      ', 0.9903537034988403), ('X', 0.2885882556438446), ('_', 0.7868338227272034), ('center', 0.7108938097953796), ('ed', 0.9968873858451843), ('=', 0.45433279871940613), ('np', 0.23741212487220764), ('.', 0.9869534373283386), ('as', 0.7983387112617493), ('array', 0.7940399646759033), ('(', 0.8978338241577148), ('X', 0.927951455116272), ('_', 0.9887539148330688), ('center', 0.9949125051498413), ('ed', 0.9974815249443054), ('.', 0.4009813368320465), ('dtype', 0.6581145524978638), ('=', 0.8807873129844666), ('np', 0.9462617039680481), ('.', 0.9960475564002991), ('float', 0.9913275837898254), ('6', 0.900066077709198), ('4', 0.9976167678833008), (')', 0.8810972571372986), ('\n', 0.9802758693695068), ('      ', 0.8247138261795044), ('y', 0.36595603823661804), ('=', 0.9615203142166138), ('np', 0.9735676050186157), ('.', 0.9975523352622986), ('as', 0.9893234372138977), ('array', 0.9928261041641235), ('(', 0.9965804219245911), ('y', 0.9935894012451172), (',', 0.9896801114082336), ('dtype', 0.9959816932678223), ('=', 0.9973965883255005), ('np', 0.9941149353981018), ('.', 0.9975690245628357), ('float', 0.9938251972198486), ('6', 0.9950826168060303), ('4', 0.9973846077919006), (')', 0.8839024305343628), ('\n', 0.9928830862045288), ('      ', 0.6196693181991577), ('if', 0.20502245426177979), ('np', 0.3786148428916931), ('.', 0.9948667287826538), ('is', 0.4025022089481354), ('inf', 0.552808403968811), ('(', 0.9974676370620728), ('X', 0.7958645224571228), ('_', 0.9790495038032532), ('center', 0.9963454604148865), ('ed', 0.9985848665237427), (').', 0.9897509217262268), ('any', 0.9815723896026611), ('()', 0.8468601703643799), ('or', 0.9974084496498108), ('np', 0.994583785533905), ('.', 0.9959726929664612), ('is', 0.9975177049636841), ('inf', 0.8058682084083557), ('(', 0.9966127276420593), ('y', 0.9863298535346985), (').', 0.9967350363731384), ('any', 0.9989416003227234), ('():', 0.9086201786994934), ('\n', 0.9957429766654968), ('          ', 0.9945181012153625), ('raise', 0.5669019222259521), ('Value', 0.9141654372215271), ('Error', 0.9978736639022827), ('("', 0.7969991564750671), ('X', 0.44107258319854736), ('and', 0.4110412895679474), ('y', 0.7504088878631592), ('must', 0.41358551383018494), ('be', 0.9119248390197754), ('finite', 0.999062716960907), ('.")', 0.34321945905685425), ('\n', 0.9954875111579895), ('\n', 0.4058873951435089), ('  ', 0.9201383590698242), ('if', 0.1747002899646759), ('Comput', 0.08185632526874542), ('e', 0.993941068649292), ('the', 0.7503149509429932), ('regression', 0.1331935077905655), ('coefficients', 0.6463187336921692), ('\n', 0.762944757938385), ('  ', 0.9836418628692627), ('if', 0.22530238330364227), ('iss', 0.36445221304893494), ('parse', 0.9979058504104614), ('(', 0.9890043139457703), ('X', 0.9916571378707886), ('):', 0.7579795718193054), ('\n', 0.9909331798553467), ('      ', 0.9900590777397156), ('X', 0.3309009075164795), ('_', 0.5777170658111572), ('center', 0.3808636963367462), ('ed', 0.9960380792617798), ('=', 0.3896521031856537), ('data', 0.7591318488121033), ('=', 0.30198776721954346), ('np', 0.5199909210205078), ('.', 0.995276689529419), ('as', 0.24891698360443115), ('array', 0.7448335886001587), ('(', 0.9932878613471985), ('X', 0.9867814183235168), ('_', 0.9903774857521057), ('center', 0.9942652583122253), ('ed', 0.9958290457725525), ('.', 0.9838305115699768), ('data', 0.9915400147438049), (',', 0.8968604803085327), ('dtype', 0.9766954779624939), ('=', 0.9923959970474243), ('np', 0.9853789806365967), ('.', 0.9990911483764648), ('float', 0.9838078618049622), ('6', 0.9903115034103394), ('4', 0.9980394244194031), (')', 0.9116743206977844), ('\n', 0.9855953454971313), ('      ', 0.9544193148612976), ('X', 0.21640270948410034), ('_', 0.7806639671325684), ('center', 0.530825138092041), ('ed', 0.9970571994781494), ('.', 0.5493364930152893), ('el', 0.7303776741027832), ('imin', 0.994574248790741), ('ate', 0.9998134970664978), ('_', 0.9956662654876709), ('zer', 0.9990420937538147), ('os', 0.9949501752853394), ('()', 0.9984298348426819), ('\n', 0.9856882095336914), ('      ', 0.838671088218689), ('X', 0.15723425149917603), ('_', 0.7781210541725159), ('center', 0.4329798221588135), ('ed', 0.9966183304786682), ('.', 0.36762735247612), ('data', 0.6011040806770325), ('/', 0.294344961643219), ('=', 0.9982011318206787), ('X', 0.5943577885627747), ('_', 0.9291861653327942), ('norm', 0.585129976272583), ('s', 0.9960905909538269), ('\n', 0.8457331657409668), ('      ', 0.8629098534584045), ('X', 0.2147170752286911), ('_', 0.8865947127342224)]

In [22]:
assert tokenizer.decode(df_dataset['input_ids'][0]) == df_dataset[params['dataset']['content_column']][0]
df_dataset[params['dataset']['content_column']][0]

2025-03-26 18:19:59.496239: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1743013199.568880 1759697 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743013199.588815 1759697 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-26 18:19:59.735759: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

'def r_regression(X, y, *, center=True, force_finite=True):\n    \n    X, y = check_X_y(X, y, accept_sparse=["csr", "csc", "coo"], dtype=np.float64)\n    n_samples = X.shape[0]\n\n    # Compute centered values\n    # Note that E[(x - mean(x))*(y - mean(y))] = E[x*(y - mean(y))], so we\n    # need not center X\n    if center:\n        y = y - np.mean(y)\n        if issparse(X):\n            X_means = X.mean(axis=0).getA1()\n        else:\n            X_means = X.mean(axis=0)\n        # Compute the scaled standard deviations via moments\n        X_norms = np.sqrt(row_norms(X.T, squared=True) - n_samples * X_means*X_means)\n        X_norms[X_norms == 0.0] = 1.0\n        X = X / X_norms\n    else:\n        X_means = np.zeros(X.shape[1])\n\n    # Compute the design matrix\n    if issparse(X):\n        X_centered = X.copy()\n        X_centered.data -= X_means\n    else:\n        X_centered = X - X_means\n\n    # Compute the regression coefficients\n    if force_finite:\n        X_centered = np.asarray(X_centered, dtype=np.float64)\n        y = np.asarray(y, dtype=np.float64)\n        if np.isinf(X_centered).any() or np.isinf(y).any():\n            raise ValueError("X and y must be finite.")\n\n    # Compute the regression coefficients\n    if issparse(X):\n        X_centered.data = np.asarray(X_centered.data, dtype=np.float64)\n        X_centered.eliminate_zeros()\n        X_centered.data /= X_norms\n        X'

In [23]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

actual_cases = actual_logit(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out] , #Out is a complete sequence
    tokenized_prompt = input_ids_list[0], ## SAMPLE ID
    tokenizer_fn = tokenizer
    )
actual_cases

[('def', 0.0007611316395923495),
 ('r', 0.0006275415071286261),
 ('_', 0.03887249529361725),
 ('re', 0.003169793402776122),
 ('gression', 0.06703148037195206),
 ('(', 0.49110478162765503),
 ('X', 0.06370403617620468),
 (',', 0.7837546467781067),
 ('y', 0.4663568139076233),
 (',', 0.6742437481880188),
 ('*', 0.010683641768991947),
 (',', 0.29887655377388),
 ('center', 0.00024064625904429704),
 ('=', 0.5727004408836365),
 ('True', 0.5564004182815552),
 (',', 0.8445126414299011),
 ('force', 0.0007708600023761392),
 ('_', 0.7570435404777527),
 ('finite', 0.002615149598568678),
 ('=', 0.9234257340431213),
 ('True', 0.7369109988212585),
 ('):', 0.3012572228908539),
 ('\n', 0.9534211158752441),
 ('   ', 0.007184024900197983),
 ('\n', 0.9500458836555481),
 ('  ', 0.962658166885376),
 ('X', 0.099087655544281),
 (',', 0.2046910971403122),
 ('y', 0.9107635617256165),
 ('=', 0.8795614242553711),
 ('check', 0.45211222767829895),
 ('_', 0.9926853179931641),
 ('X', 0.7585020661354065),
 ('_', 0.9899470210075378),
 ('y', 0.9985018968582153),
 ('(', 0.9936887621879578),
 ('X', 0.9682533144950867),
 (',', 0.9940112233161926),
 ('y', 0.9895937442779541),
 (',', 0.8327682018280029),
 ('accept', 0.3503636419773102),
 ('_', 0.9988272786140442),
 ('s', 0.9915286302566528),
 ('parse', 0.9995672106742859),
 ('=', 0.9098601937294006),
 ('["', 0.06760509312152863),
 ('cs', 0.9180654287338257),
 ('r', 0.9998188614845276),
 ('",', 0.9022738933563232),
 ('"', 0.9934238195419312),
 ('c', 0.9910041093826294),
 ('sc', 0.9999805688858032),
 ('",', 0.23119236528873444),
 ('"', 0.9847519993782043),
 ('co', 0.9791660904884338),
 ('o', 0.999893307685852),
 ('"],', 0.5480908751487732),
 ('dtype', 0.04684154689311981),
 ('=', 0.6953261494636536),
 ('np', 0.28419655561447144),
 ('.', 0.9987038373947144),
 ('float', 0.9613701105117798),
 ('6', 0.8718473315238953),
 ('4', 0.9999958276748657),
 (')', 0.4972749352455139),
 ('\n', 0.9865104556083679),
 ('  ', 0.4172475337982178),
 ('n', 0.0897156298160553),
 ('_', 0.9120565056800842),
 ('samples', 0.7544899582862854),
 ('=', 0.14374341070652008),
 ('X', 0.7211654782295227),
 ('.', 0.9984862804412842),
 ('shape', 0.9993509650230408),
 ('[', 0.9989560842514038),
 ('0', 0.9978376030921936),
 (']', 0.9990909099578857),
 ('\n', 0.9903761744499207),
 ('\n', 0.172419935464859),
 ('  ', 0.9845446348190308),
 ('#', 0.1567116677761078),
 ('Comput', 0.014349647797644138),
 ('e', 0.9731297492980957),
 ('centered', 0.030078299343585968),
 ('values', 0.010645981878042221),
 ('\n', 0.49346378445625305),
 ('  ', 0.984738826751709),
 ('#', 0.011870801448822021),
 ('Note', 0.036529459059238434),
 ('that', 0.24398794770240784),
 ('E', 0.00012358241656329483),
 ('[(', 0.023394998162984848),
 ('x', 0.2505376935005188),
 ('-', 0.5316087007522583),
 ('mean', 0.2363666445016861),
 ('(', 0.7420043349266052),
 ('x', 0.9291857481002808),
 ('))', 0.9626831412315369),
 ('*(', 0.06106217950582504),
 ('y', 0.9108766317367554),
 ('-', 0.9659267067909241),
 ('mean', 0.9762095808982849),
 ('(', 0.9953470826148987),
 ('y', 0.9955958724021912),
 ('))]', 0.920138955116272),
 ('=', 0.6488011479377747),
 ('E', 0.5962879657745361),
 ('[', 0.8997237086296082),
 ('x', 0.7205336093902588),
 ('*(', 0.005368777085095644),
 ('y', 0.9901363253593445),
 ('-', 0.9192156195640564),
 ('mean', 0.9002822041511536),
 ('(', 0.9843617677688599),
 ('y', 0.9958815574645996),
 ('))', 0.04857032001018524),
 ('],', 0.10966462641954422),
 ('so', 0.08264478296041489),
 ('we', 0.22486816346645355),
 ('\n', 0.1475246548652649),
 ('  ', 0.9993389248847961),
 ('#', 0.9998130202293396),
 ('need', 0.022961553186178207),
 ('not', 0.07220478355884552),
 ('center', 0.4617106318473816),
 ('X', 0.019282901659607887),
 ('\n', 0.10235119611024857),
 ('  ', 0.8931682705879211),
 ('if', 0.5958297848701477),
 ('center', 0.7577549815177917),
 (':', 0.9699742794036865),
 ('\n', 0.9882383942604065),
 ('      ', 0.9778000116348267),
 ('y', 0.29292163252830505),
 ('=', 0.20164163410663605),
 ('y', 0.8482464551925659),
 ('-', 0.9446906447410583),
 ('np', 0.5826309323310852),
 ('.', 0.9986144304275513),
 ('mean', 0.3906077742576599),
 ('(', 0.9990711212158203),
 ('y', 0.9984264373779297),
 (')', 0.860521674156189),
 ('\n', 0.9818989038467407),
 ('      ', 0.06791553646326065),
 ('if', 0.1218002513051033),
 ('iss', 0.001267320942133665),
 ('parse', 0.9928327798843384),
 ('(', 0.9905065894126892),
 ('X', 0.8441720008850098),
 ('):', 0.9687318801879883),
 ('\n', 0.9840208888053894),
 ('          ', 0.9954694509506226),
 ('X', 0.5903856158256531),
 ('_', 0.10085055232048035),
 ('me', 0.07516585290431976),
 ('ans', 0.9970138072967529),
 ('=', 0.985230028629303),
 ('X', 0.3525844216346741),
 ('.', 0.9442490935325623),
 ('mean', 0.9094809293746948),
 ('(', 0.9982339143753052),
 ('axis', 0.9494960904121399),
 ('=', 0.9969950914382935),
 ('0', 0.9789137840270996),
 (').', 0.38932424783706665),
 ('get', 0.04113853722810745),
 ('A', 0.9899405837059021),
 ('1', 0.9979212880134583),
 ('()', 0.9859300255775452),
 ('\n', 0.9399358630180359),
 ('      ', 0.6895958185195923),
 ('else', 0.9911351203918457),
 (':', 0.9991838335990906),
 ('\n', 0.9961102604866028),
 ('          ', 0.998494029045105),
 ('X', 0.9942038655281067),
 ('_', 0.9981063604354858),
 ('me', 0.9987072944641113),
 ('ans', 0.9993403553962708),
 ('=', 0.9984044432640076),
 ('X', 0.5912094712257385),
 ('.', 0.9991658926010132),
 ('mean', 0.9997232556343079),
 ('(', 0.9989737272262573),
 ('axis', 0.9791942238807678),
 ('=', 0.9995527863502502),
 ('0', 0.9992795586585999),
 (')', 0.9883139133453369),
 ('\n', 0.9904910326004028),
 ('      ', 0.7179279923439026),
 ('#', 0.019547265022993088),
 ('Comput', 0.007420943584293127),
 ('e', 0.9725230932235718),
 ('the', 0.1416737288236618),
 ('scale', 0.017759881913661957),
 ('d', 0.3126679062843323),
 ('standard', 0.00047219538828358054),
 ('devi', 0.19317086040973663),
 ('ations', 0.9940329194068909),
 ('via', 0.0007267140899784863),
 ('moments', 0.0012031293008476496),
 ('\n', 0.30729085206985474),
 ('      ', 0.9939178228378296),
 ('X', 0.12951719760894775),
 ('_', 0.7407935857772827),
 ('norm', 0.0044555142521858215),
 ('s', 0.33058440685272217),
 ('=', 0.9742979407310486),
 ('np', 0.5227304697036743),
 ('.', 0.9980632662773132),
 ('sqrt', 0.6538915038108826),
 ('(', 0.4758837819099426),
 ('row', 0.0012695631012320518),
 ('_', 0.9989452958106995),
 ('norm', 0.99724942445755),
 ('s', 0.9961996674537659),
 ('(', 0.9971194267272949),
 ('X', 0.9862668514251709),
 ('.', 0.025011641904711723),
 ('T', 0.332500696182251),
 (',', 0.515108585357666),
 ('squ', 0.9847097992897034),
 ('ared', 0.9998606443405151),
 ('=', 0.9985867738723755),
 ('True', 0.9929303526878357),
 (')', 0.4373514950275421),
 ('-', 0.04885046184062958),
 ('n', 0.027766844257712364),
 ('_', 0.9993330836296082),
 ('samples', 0.9992639422416687),
 ('*', 0.8356918692588806),
 ('X', 0.5777639746665955),
 ('_', 0.9980005621910095),
 ('me', 0.9997733235359192),
 ('ans', 0.9997392296791077),
 ('*', 0.0002028934541158378),
 ('X', 0.9707205891609192),
 ('_', 0.9993865489959717),
 ('me', 0.9995751976966858),
 ('ans', 0.9976844787597656),
 (')', 0.8300114870071411),
 ('\n', 0.9760091304779053),
 ('      ', 0.5472725033760071),
 ('X', 0.3217059075832367),
 ('_', 0.5064075589179993),
 ('norm', 0.5027255415916443),
 ('s', 0.9788424372673035),
 ('[', 0.8077937960624695),
 ('X', 0.7765548825263977),
 ('_', 0.9991416931152344),
 ('norm', 0.9997690320014954),
 ('s', 0.9996110796928406),
 ('==', 0.6666505336761475),
 ('', 0.9875324368476868),
 ('0', 0.9996471405029297),
 ('.', 0.36950650811195374),
 ('0', 0.9991801381111145),
 (']', 0.9988213181495667),
 ('=', 0.9915881752967834),
 ('', 0.9448598027229309),
 ('1', 0.9947752952575684),
 ('.', 0.9493046998977661),
 ('0', 0.9797582626342773),
 ('\n', 0.8296047449111938),
 ('      ', 0.5093404650688171),
 ('X', 0.6306172013282776),
 ('=', 0.7451503276824951),
 ('X', 0.5434690713882446),
 ('/', 0.6473486423492432),
 ('X', 0.9719201922416687),
 ('_', 0.9989801049232483),
 ('norm', 0.9994082450866699),
 ('s', 0.998853325843811),
 ('\n', 0.5715194344520569),
 ('  ', 0.323535680770874),
 ('else', 0.7873696684837341),
 (':', 0.9987198114395142),
 ('\n', 0.984889030456543),
 ('      ', 0.9941845536231995),
 ('X', 0.6364556550979614),
 ('_', 0.8907188177108765),
 ('me', 0.938082754611969),
 ('ans', 0.9985014200210571),
 ('=', 0.934043288230896),
 ('np', 0.6135618090629578),
 ('.', 0.9991574287414551),
 ('zer', 0.9314483404159546),
 ('os', 0.9991784691810608),
 ('(', 0.8850137591362),
 ('X', 0.7173984050750732),
 ('.', 0.9962267875671387),
 ('shape', 0.9997125267982483),
 ('[', 0.9920992851257324),
 ('1', 0.9630857706069946),
 ('])', 0.6484161615371704),
 ('\n', 0.9899998307228088),
 ('\n', 0.37493816018104553),
 ('  ', 0.9780239462852478),
 ('#', 0.567473828792572),
 ('Comput', 0.10053089261054993),
 ('e', 0.9956986904144287),
 ('the', 0.32369863986968994),
 ('design', 0.06609194725751877),
 ('matrix', 0.914018452167511),
 ('\n', 0.300182580947876),
 ('  ', 0.9856303334236145),
 ('if', 0.33283790946006775),
 ('iss', 0.5057779550552368),
 ('parse', 0.9996328353881836),
 ('(', 0.998953104019165),
 ('X', 0.9949808716773987),
 ('):', 0.9728975892066956),
 ('\n', 0.9930338859558105),
 ('      ', 0.9915831685066223),
 ('X', 0.6186857223510742),
 ('_', 0.47425419092178345),
 ('center', 0.09075981378555298),
 ('ed', 0.8975473046302795),
 ('=', 0.9642708897590637),
 ('X', 0.7295427322387695),
 ('.', 0.5536623597145081),
 ('copy', 0.5529422760009766),
 ('()', 0.9103391766548157),
 ('\n', 0.9676773548126221),
 ('      ', 0.5701210498809814),
 ('X', 0.5691580176353455),
 ('_', 0.9841669201850891),
 ('center', 0.9561602473258972),
 ('ed', 0.9990321397781372),
 ('.', 0.9743281602859497),
 ('data', 0.9881397485733032),
 ('-=', 0.4623633921146393),
 ('X', 0.8509217500686646),
 ('_', 0.9342305064201355),
 ('me', 0.9530187249183655),
 ('ans', 0.9987105131149292),
 ('\n', 0.7440929412841797),
 ('  ', 0.6855424642562866),
 ('else', 0.9703865051269531),
 (':', 0.9984819293022156),
 ('\n', 0.995128870010376),
 ('      ', 0.9980206489562988),
 ('X', 0.9696429371833801),
 ('_', 0.9932696223258972),
 ('center', 0.9966076612472534),
 ('ed', 0.99669349193573),
 ('=', 0.9976285099983215),
 ('X', 0.8843185901641846),
 ('-', 0.8085638880729675),
 ('X', 0.9372349381446838),
 ('_', 0.9899084568023682),
 ('me', 0.9987143278121948),
 ('ans', 0.9992743134498596),
 ('\n', 0.8783270120620728),
 ('\n', 0.7673149704933167),
 ('  ', 0.9846394062042236),
 ('#', 0.6775290369987488),
 ('Comput', 0.162695050239563),
 ('e', 0.9976087808609009),
 ('the', 0.6611243486404419),
 ('regression', 0.14245104789733887),
 ('coefficients', 0.3693326413631439),
 ('\n', 0.7221249938011169),
 ('  ', 0.9844607710838318),
 ('if', 0.2834618389606476),
 ('force', 0.5720871090888977),
 ('_', 0.9977871179580688),
 ('finite', 0.9300464391708374),
 (':', 0.9371045827865601),
 ('\n', 0.9937094449996948),
 ('      ', 0.9903537034988403),
 ('X', 0.2885882556438446),
 ('_', 0.7868338227272034),
 ('center', 0.7108938097953796),
 ('ed', 0.9968873858451843),
 ('=', 0.45433279871940613),
 ('np', 0.23741212487220764),
 ('.', 0.9869534373283386),
 ('as', 0.7983387112617493),
 ('array', 0.7940399646759033),
 ('(', 0.8978338241577148),
 ('X', 0.927951455116272),
 ('_', 0.9887539148330688),
 ('center', 0.9949125051498413),
 ('ed', 0.9974815249443054),
 (',', 0.37576356530189514),
 ('dtype', 0.6581145524978638),
 ('=', 0.8807873129844666),
 ('np', 0.9462617039680481),
 ('.', 0.9960475564002991),
 ('float', 0.9913275837898254),
 ('6', 0.900066077709198),
 ('4', 0.9976167678833008),
 (')', 0.8810972571372986),
 ('\n', 0.9802758693695068),
 ('      ', 0.8247138261795044),
 ('y', 0.36595603823661804),
 ('=', 0.9615203142166138),
 ('np', 0.9735676050186157),
 ('.', 0.9975523352622986),
 ('as', 0.9893234372138977),
 ('array', 0.9928261041641235),
 ('(', 0.9965804219245911),
 ('y', 0.9935894012451172),
 (',', 0.9896801114082336),
 ('dtype', 0.9959816932678223),
 ('=', 0.9973965883255005),
 ('np', 0.9941149353981018),
 ('.', 0.9975690245628357),
 ('float', 0.9938251972198486),
 ('6', 0.9950826168060303),
 ('4', 0.9973846077919006),
 (')', 0.8839024305343628),
 ('\n', 0.9928830862045288),
 ('      ', 0.6196693181991577),
 ('if', 0.20502245426177979),
 ('np', 0.3786148428916931),
 ('.', 0.9948667287826538),
 ('is', 0.4025022089481354),
 ('inf', 0.552808403968811),
 ('(', 0.9974676370620728),
 ('X', 0.7958645224571228),
 ('_', 0.9790495038032532),
 ('center', 0.9963454604148865),
 ('ed', 0.9985848665237427),
 (').', 0.9897509217262268),
 ('any', 0.9815723896026611),
 ('()', 0.8468601703643799),
 ('or', 0.9974084496498108),
 ('np', 0.994583785533905),
 ('.', 0.9959726929664612),
 ('is', 0.9975177049636841),
 ('inf', 0.8058682084083557),
 ('(', 0.9966127276420593),
 ('y', 0.9863298535346985),
 (').', 0.9967350363731384),
 ('any', 0.9989416003227234),
 ('():', 0.9086201786994934),
 ('\n', 0.9957429766654968),
 ('          ', 0.9945181012153625),
 ('raise', 0.5669019222259521),
 ('Value', 0.9141654372215271),
 ('Error', 0.9978736639022827),
 ('("', 0.7969991564750671),
 ('X', 0.44107258319854736),
 ('and', 0.4110412895679474),
 ('y', 0.7504088878631592),
 ('must', 0.41358551383018494),
 ('be', 0.9119248390197754),
 ('finite', 0.999062716960907),
 ('.")', 0.34321945905685425),
 ('\n', 0.9954875111579895),
 ('\n', 0.4058873951435089),
 ('  ', 0.9201383590698242),
 ('#', 0.15376366674900055),
 ('Comput', 0.08185632526874542),
 ('e', 0.993941068649292),
 ('the', 0.7503149509429932),
 ('regression', 0.1331935077905655),
 ('coefficients', 0.6463187336921692),
 ('\n', 0.762944757938385),
 ('  ', 0.9836418628692627),
 ('if', 0.22530238330364227),
 ('iss', 0.36445221304893494),
 ('parse', 0.9979058504104614),
 ('(', 0.9890043139457703),
 ('X', 0.9916571378707886),
 ('):', 0.7579795718193054),
 ('\n', 0.9909331798553467),
 ('      ', 0.9900590777397156),
 ('X', 0.3309009075164795),
 ('_', 0.5777170658111572),
 ('center', 0.3808636963367462),
 ('ed', 0.9960380792617798),
 ('.', 0.38004547357559204),
 ('data', 0.7591318488121033),
 ('=', 0.30198776721954346),
 ('np', 0.5199909210205078),
 ('.', 0.995276689529419),
 ('as', 0.24891698360443115),
 ('array', 0.7448335886001587),
 ('(', 0.9932878613471985),
 ('X', 0.9867814183235168),
 ('_', 0.9903774857521057),
 ('center', 0.9942652583122253),
 ('ed', 0.9958290457725525),
 ('.', 0.9838305115699768),
 ('data', 0.9915400147438049),
 (',', 0.8968604803085327),
 ('dtype', 0.9766954779624939),
 ('=', 0.9923959970474243),
 ('np', 0.9853789806365967),
 ('.', 0.9990911483764648),
 ('float', 0.9838078618049622),
 ('6', 0.9903115034103394),
 ('4', 0.9980394244194031),
 (')', 0.9116743206977844),
 ('\n', 0.9855953454971313),
 ('      ', 0.9544193148612976),
 ('X', 0.21640270948410034),
 ('_', 0.7806639671325684),
 ('center', 0.530825138092041),
 ('ed', 0.9970571994781494),
 ('.', 0.5493364930152893),
 ('el', 0.7303776741027832),
 ('imin', 0.994574248790741),
 ('ate', 0.9998134970664978),
 ('_', 0.9956662654876709),
 ('zer', 0.9990420937538147),
 ('os', 0.9949501752853394),
 ('()', 0.9984298348426819),
 ('\n', 0.9856882095336914),
 ('      ', 0.838671088218689),
 ('X', 0.15723425149917603),
 ('_', 0.7781210541725159),
 ('center', 0.4329798221588135),
 ('ed', 0.9966183304786682),
 ('.', 0.36762735247612),
 ('data', 0.6011040806770325),
 ('/', 0.294344961643219),
 ('=', 0.9982011318206787),
 ('X', 0.5943577885627747),
 ('_', 0.9291861653327942),
 ('norm', 0.585129976272583),
 ('s', 0.9960905909538269),
 ('\n', 0.8457331657409668),
 ('      ', 0.8629098534584045),
 ('X', 0.2147170752286911)]

#### Processing all the Batches

In [24]:
def batching_logits(tokenizer,tf_input_ids,size=10000):
    max_logit_token_prompt = []
    min_logit_token_prompt = []
    actual_logit_token_prompt = []

    
    soft = torch.nn.Softmax( dim = 0 )                          #Flattening normalization
    
    for file in range( size ):
        callbacks_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['decoding_strategy']}"
        out = np.load(f"{callbacks_dir}/logits_tensor[{file}]_batch[{file}].npy") #<sample,tokens,voc_tokens>
        out = out[0]  ##### #<tokens,voc_tokens>
        next_tokens_distribution = [ soft( torch.from_numpy(token) ) for token in out]  #Flattening normalization
        
        max_cases,min_cases = min_max_logits(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenizer_fn= tokenizer
            )

        actual_cases = actual_logit(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenized_prompt = tf_input_ids[ file ],
            tokenizer_fn = tokenizer
            )
        
        max_logit_token_prompt.append( max_cases )
        min_logit_token_prompt.append( min_cases )
        actual_logit_token_prompt.append( actual_cases )
        
        logging.info(file)
    return max_logit_token_prompt,min_logit_token_prompt,actual_logit_token_prompt

In [25]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

In [68]:
max_logit_token_prompt, min_logit_token_prompt, actual_logit_token_prompt = batching_logits(
    tokenizer=tokenizer , tf_input_ids=input_ids_list, 
    size = len(df_dataset)
) #<---WARNING TIME Consuming

#### Saving results

In [69]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [70]:
dataframe_to_save = df_dataset.copy()
dataframe_to_save['max_prob'] = max_logit_token_prompt
dataframe_to_save['min_prob'] = min_logit_token_prompt
dataframe_to_save['actual_prob'] = actual_logit_token_prompt
dataframe_to_save.shape

(5, 33)

In [ ]:
output_dir = f"{params['output_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['decoding_strategy']}"
create_folder(output_dir)
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

#### Loss Retrieval

In [ ]:
def batching_loss( size = dataframe_to_save.shape[0] ):
    output_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['decoding_strategy']}"
    output_loss = []
    for current_batch in range(size):
        out = np.load(f"{output_dir}/_loss_batch[{current_batch}].npy")
        output_loss.append( out.item() ) #.item() for numpy library
        logging.info(current_batch)
    return output_loss

In [76]:
output_loss = batching_loss() #[WAENING!] Takes Time

In [77]:
output_loss

[0.6501871347427368,
 1.36393404006958,
 0.6265979409217834,
 0.9561377763748169,
 1.176944613456726]

In [78]:
dataframe_to_save['loss'] = output_loss
dataframe_to_save.head(5)

,id,commit_id,repo,path,file_name,fun_name,commit_message,code,url,language,...,s_end_line,s_end_column,s_code,category,input_lenght,input_ids,max_prob,min_prob,actual_prob,loss
0,256261,a59bca366174d9c692fa19750c24d65f47660ef7,haystack,haystack/modeling/training/base.py,base.py,_get_state_dict,Apply black formatting (#2115)\n\n* Testing bl...,def _get_state_dict(self):\n \n ...,https://github.com/deepset-ai/haystack.git,Python,...,2,22,state_dict = {,Warning,295,"[822, 903, 657, 29918, 3859, 29918, 8977, 2989...","[(<PRE>, 0.7492886185646057), (module, 0.47944...","[(<s>, 6.321602312800434e-13), ($}, 1.21012630...","[(def, 0.0007611338514834642), (_, 0.009010307...",0.650187
1,305801,6f564e4f514b56bce281ec7e82703cfbff87b417,core,homeassistant/components/ring/binary_sensor.py,binary_sensor.py,async_added_to_hass,Improve entity type hints [r] (#77874),async def async_added_to_hass(self) -> None:\n...,https://github.com/home-assistant/core.git,Python,...,4,37,self._dings_update_callback(),Warning,72,"[7465, 822, 7465, 29918, 23959, 29918, 517, 29...","[(<PRE>, 0.7492926716804504), (\n, 0.145589932...","[(<s>, 6.322408417115677e-13), (oreferrer, 3.7...","[(async, 1.0811768333951477e-05), (def, 0.0006...",1.363934
2,70649,5fe901e5d86ed02dbbb63039a897582951266afd,wagtail,wagtail/admin/tests/pages/test_edit_page.py,test_edit_page.py,test_new_comment,Fix commenting thread notifications being sent...,def test_new_comment(self):\n post_data...,https://github.com/wagtail/wagtail.git,Python,...,33,125,self.assertEqual(mail.outbox[0].subjec...,Convention,665,"[822, 1243, 29918, 1482, 29918, 9342, 29898, 1...","[(<PRE>, 0.7492899298667908), (module, 0.47944...","[(<s>, 6.321468413832132e-13), ($}, 1.21012033...","[(def, 0.0007611322216689587), (test, 0.019638...",0.626598
3,151753,bdfedb5fcb02b88c600ef25c88bbb5d939b8bd0a,freqtrade,freqtrade/freqai/RL/BaseReinforcementLearningM...,BaseReinforcementLearningModel.py,__init__,Improve typehints / reduce warnings from mypy,"def __init__(self, **kwargs) -> None:\n ...",https://github.com/freqtrade/freqtrade.git,Python,...,13,44,import_str = 'stable_baselines3',Warning,493,"[822, 4770, 2344, 12035, 1311, 29892, 3579, 19...","[(<PRE>, 0.7492900490760803), (module, 0.47944...","[(<s>, 6.321457571810407e-13), ($}, 1.21011436...","[(def, 0.0007611316395923495), (__, 0.00598208...",0.956138
4,3868,2282a4ae0221b1fb88e16eca8bc14a166998d2d2,airbyte,airbyte-integrations/connectors/source-hubspot...,streams.py,state,🎉 Source Hubspot: Migrate to CDK (#10177)\n\n*...,"def state(self, value):\n state_value =...",https://github.com/airbytehq/airbyte.git,Python,...,7,61,"self._start_date = max(self._state, se...",Warning,109,"[822, 2106, 29898, 1311, 29892, 995, 1125, 13,...","[(<PRE>, 0.749289870262146), (module, 0.479445...","[(<s>, 6.321889626376143e-13), ($}, 1.21010756...","[(def, 0.0007611394976265728), (state, 6.87381...",1.176945

In [79]:
## Saving CheckPoint 2
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

In [80]:
print("================================= PROCESS COMPLETED =================================")

================================= PROCESS COMPLETE =================================

In [82]:
del model
torch.cuda.empty_cache()
gc.collect()

0