# Logits Preprocessing and Data Engineering

In [ ]:
def default_params(): 
    return {
        'current_model': 'M1', 
        'quantization': 'none', #['none',"int4", "int8", "float32", "float16"]
        'dataset': {
            'path': '/workspaces/CodeSmells/semeru-datasets/code_smells/extraction',
            'transformation': 'curated',
            'content_column': 'code',
            'sampling_size': 500,
        },
        'logging_path': '/workspaces/CodeSmells/datax/code_smells/logs', 
        'output_path' : '/workspaces/CodeSmells/datax/code_smells/logits',
        'callbacks_dir' : '/workspaces/CodeSmells/datax/code_smells/callbacks',
        'cache_dir': '/workspaces/CodeSmells/datax/hugging_face_cache',
        'causal_models': {
            'M1' : 'codellama/CodeLlama-7b-hf', #https://huggingface.co/codellama/CodeLlama-7b-hf, 
        },
    }
params = default_params()

#### Imports

In [2]:
import pandas as pd
import os
import time
import numpy as np
import torch
import gc

In [ ]:
import seaborn as sns
from scipy import stats
from statistics import NormalDist
import matplotlib.pyplot as plt

In [3]:
from transformers import CodeLlamaTokenizer, LlamaForCausalLM
from datasets import load_dataset

In [ ]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [ ]:
# Define log file path
log_file = f"{params['logging_path']}/{params['current_model']}/{params['dataset']['transformation']}"
create_folder(log_file)
log_file += '/data_en.txt'

# Create the log file if it doesn't exist
if not os.path.exists(log_file):
    with open(log_file, 'w'): 
        pass  # Create an empty log file

In [ ]:
import logging
logging.basicConfig(filename=log_file, format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

#### Dataset

In [ ]:
df_dataset = pd.read_json(f"{params['dataset']['path']}/{params['dataset']['transformation']}_{params['dataset']['sampling_size']}.json", )

In [ ]:
df_dataset = df_dataset.reset_index(drop=True, inplace=True)

#### Model Loading

In [9]:
def instantiate_llm(model_name:str, cache_dir:str):
     '''Instantiate AutoModelForCausalLM'''
     tokenizer = CodeLlamaTokenizer.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoTokenizer - " + model_name)
     model = None
     if params['quantization'] == 'int4':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_4bit=True)
     elif params['quantization'] == 'int8':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_8bit=True)
     elif params['quantization'] == 'float32':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float32)
     elif params['quantization'] == 'float16':
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float16)
     else: 
          model = LlamaForCausalLM.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoModelForCausalLM - " + model_name)

     return tokenizer, model

In [10]:
tokenizer, model = instantiate_llm(params['causal_models'][params['current_model']], params['cache_dir'])

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

#### preprocess dataset

In [ ]:
df_dataset['input_ids'] = df_dataset[params['content_column']].map(lambda code: tokenizer.encode(code))
df_dataset['len_input_ids'] = df_dataset[params['input_ids']].map(lambda input_ids: len(input_ids))

#### Softmax Normalization and Data Engineering

In [11]:
def topk_tuple( logit_vocab_tensor, largest, tokenizer_fn):
    "Run topk for a token"
    topk = logit_vocab_tensor.topk( k=1 , largest=largest ) #TODO K number of elements can be extended
    return ( tokenizer.convert_tokens_to_string([tokenizer_fn.decode(topk.indices)]), topk.values.item())

def min_max_logits( logit_vocab_sample_tensor, tokenizer_fn ):
    "Compute min_max for a sample"
    max_cases = []
    min_cases = []
    for logit_vocab_tensor in logit_vocab_sample_tensor:
        max_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = True, tokenizer_fn = tokenizer_fn) ) #TST Max Logit
        min_cases.append( topk_tuple( logit_vocab_tensor = logit_vocab_tensor, largest = False, tokenizer_fn = tokenizer_fn) ) #TST Min Logit
    return max_cases, min_cases

def actual_logit( 
                 logit_vocab_sample_tensor, 
                 tokenized_prompt, 
                 tokenizer_fn,
                 ):
    "Compute actual logits for a sample"
    actual_logits_prompt = []
    for token_pos, id_token in enumerate( tokenized_prompt[1:] ): #Eliminate the first token prediction since we do not use it
        actual_logits_prompt.append(
            (   tokenizer.convert_tokens_to_string([tokenizer_fn.decode( int(id_token))]), #retrieving the name of the token with the id
                logit_vocab_sample_tensor[token_pos][int(id_token)].item()) #retrieving the logit given the position in the sequence and the position in the vocab
            )
    return actual_logits_prompt

In [12]:
soft = torch.nn.Softmax( dim = 0 ) #Flattening normalization

In [ ]:
callbacks_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
out = np.load(f"{callbacks_dir}/logits_tensor[0]_batch[0].npy")

print(out.shape) #<sample,tokens,voc_tokens>
out = out[0]

(1, 224, 32016)

In [14]:
max_case,min_case = min_max_logits(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out], ####### 
    tokenizer_fn= tokenizer
    )
print(max_case)
assert len(max_case) == len(min_case)

[('<PRE>', 0.7492888569831848), ('module', 0.4794430136680603), ('_', 0.8005598783493042), ('get', 0.03342306241393089), ('_', 0.7154065370559692), ('of', 0.029203299432992935), ('(', 0.4235145151615143), ('to', 0.047612469643354416), ('bin', 0.33591780066490173), ('ations', 0.5140894055366516), ('(', 0.5055526494979858), ('self', 0.23513413965702057), ('):', 0.8747055530548096), ('\n', 0.9750158190727234), ('      ', 0.63499915599823), ('"""', 0.23746822774410248), ('=', 0.9357321858406067), ('[', 0.34527602791786194), ('1', 0.581474244594574), (',', 0.7503364682197571), ('', 0.7880880832672119), ('2', 0.6225070953369141), (',', 0.8709840774536133), ('', 0.9746920466423035), ('3', 0.9141796231269836), (']', 0.5397116541862488), ('', 0.9849329590797424), ('4', 0.9219658970832825), (']', 0.7163926959037781), ('\n', 0.990165650844574), ('      ', 0.953723669052124), ('assert', 0.1824035793542862), ('=', 0.9945827126502991), ('[', 0.8366445302963257), ('1', 0.24499067664146423), (',', 0.9555310606956482), ('', 0.9639140963554382), ('3', 0.4513107240200043), (',', 0.8149762153625488), ('', 0.9886634945869446), ('4', 0.6921757459640503), (',', 0.8097878098487854), ('', 0.9933232665061951), ('4', 0.6040694713592529), (']', 0.9452548027038574), ('\n', 0.9949696660041809), ('      ', 0.8620179891586304), ('C', 0.30543676018714905), ('=', 0.991418719291687), ('[', 0.8974470496177673), ('1', 0.30729031562805176), (',', 0.9455235004425049), ('', 0.9781342148780823), ('3', 0.4419252276420593), (',', 0.9066768884658813), ('', 0.9926016926765442), ('4', 0.42424437403678894), (',', 0.9360893964767456), ('', 0.9941338896751404), ('4', 0.7743690013885498), (']', 0.869607150554657), ('\n', 0.9947307109832764), ('      ', 0.8113580346107483), ('D', 0.3853749632835388), ('=', 0.9626933932304382), ('', 0.9588623046875), ('8', 0.1784757673740387), ('\n', 0.9914064407348633), ('      ', 0.7816305160522461), ('self', 0.3374582827091217), ('=', 0.9585395455360413), ('', 0.37557247281074524), ('1', 0.5923482179641724), (',', 0.9686475396156311), ('', 0.9456903338432312), ('2', 0.7503157258033752), (',', 0.688934326171875), ('', 0.993884265422821), ('2', 0.786919116973877), ('],', 0.5275229215621948), ('[', 0.8756741285324097), ('1', 0.5869309306144714), (',', 0.9908602237701416), ('', 0.9872724413871765), ('3', 0.7773932218551636), (',', 0.9707011580467224), ('', 0.9931554198265076), ('3', 0.8406159281730652), ('],', 0.741012454032898), ('[', 0.9890978336334229), ('2', 0.8773713707923889), (',', 0.989468514919281), ('', 0.9887646436691284), ('4', 0.6568235754966736), (',', 0.9829372763633728), ('', 0.9925554394721985), ('4', 0.8660441040992737), ('],', 0.6740802526473999), ('[', 0.9231075644493103), ('2', 0.7117090225219727), (',', 0.9911050200462341), ('', 0.9921352863311768), ('4', 0.3673848509788513), (',', 0.9903525710105896), ('', 0.9934533834457397), ('3', 0.6186410188674927), ('],', 0.6920957565307617), ('[', 0.8300358653068542), ('               ', 0.9271838665008545), ('', 0.9712095856666565), ('[', 0.9983647465705872), ('2', 0.681769847869873), (',', 0.9957068562507629), ('', 0.9966907501220703), ('3', 0.5612576007843018), (',', 0.9942567944526672), ('', 0.9967219233512878), ('3', 0.6813869476318359), ('],', 0.9710125923156738), ('[', 0.9892235994338989), ('1', 0.5214933753013611), (',', 0.9955192804336548), ('', 0.9970058798789978), ('3', 0.7920661568641663), (',', 0.972542941570282), ('', 0.9968900084495544), ('2', 0.6258708238601685), ('],', 0.972956120967865), ('[', 0.9885154366493225), ('1', 0.5923253893852234), (',', 0.9956067204475403), ('', 0.9974067807197571), ('2', 0.7277050614356995), (',', 0.9962977766990662), ('', 0.9971797466278076), ('3', 0.8803697228431702), ('],', 0.9599359035491943), ('[', 0.9776690602302551), ('2', 0.9769474267959595), (',', 0.9960588216781616), ('', 0.9969747066497803), ('3', 0.5883517265319824), (',', 0.9962701797485352), ('', 0.9968138337135315), ('3', 0.9822123050689697), ('],', 0.9010952115058899), ('\n', 0.6983346343040466), ('               ', 0.9966253042221069), ('', 0.9963627457618713), ('[', 0.9985062479972839), ('2', 0.9732682704925537), (',', 0.9967471361160278), ('', 0.9972490668296814), ('2', 0.6733132600784302), (',', 0.9963435530662537), ('', 0.9974998831748962), ('2', 0.9552763104438782), ('],', 0.9357399344444275), ('[', 0.9967774748802185), ('2', 0.9424952268600464), (',', 0.9967411160469055), ('', 0.9972099661827087), ('3', 0.9621609449386597), (',', 0.9966233968734741), ('', 0.9973692893981934), ('2', 0.8727455139160156), ('],', 0.957173228263855), ('[', 0.9959046244621277), ('2', 0.7943212985992432), (',', 0.9948044419288635), ('', 0.9972915053367615), ('2', 0.6272098422050476), (',', 0.9958372116088867), ('', 0.99665367603302), ('2', 0.9826914668083191), ('],', 0.9213972687721252), ('[', 0.9911543130874634), ('3', 0.980730414390564), (',', 0.9948468208312988), ('', 0.9949371814727783), ('2', 0.6988815069198608), (',', 0.9952408075332642), ('', 0.9966251850128174), ('2', 0.9891639947891235), ('],', 0.6448702812194824), ('\n', 0.9926968216896057), ('      ', 0.8526779413223267), ('self', 0.5975764393806458), ('=', 0.41748374700546265), ('sort', 0.9800238013267517), ('()', 0.9006100296974182), ('\n', 0.9898297190666199), ('      ', 0.8921402096748352), ('self', 0.4131834805011749), ('.', 0.9904189705848694), ('assert', 0.9752987623214722), ('Equal', 0.7091389894485474), ('Equal', 0.9930994510650635), ('(', 0.984497606754303), ('answer', 0.6160946488380432), ('(', 0.9805822968482971), ('array', 0.31328120827674866), ('_', 0.9362586736679077), ('sum', 0.9590511918067932), ('_', 0.9799745082855225), ('com', 0.988177478313446), ('bin', 0.9954270124435425), ('ations', 0.9808430075645447), ('(', 0.9635322093963623), ('A', 0.9731706976890564), (',', 0.9938203692436218), ('B', 0.9759390354156494), (',', 0.9786263704299927), ('C', 0.8287654519081116), (',', 0.9608737230300903), ('target', 0.9721238017082214), (')),', 0.9661067128181458), ('answer', 0.74546879529953), ('               ', 0.9847843647003174), ('           ', 0.9783505797386169), ('answer', 0.6295254826545715), (')', 0.9668086171150208), ('\n', 0.9927384257316589), ('\n', 0.8827594518661499)]

In [ ]:
assert tokenizer.decode(df_dataset['input_ids'][0]) == df_dataset[params['dataset']['content_column']][0]
df_dataset[params['dataset']['content_column']][0]

2024-09-30 12:58:21.798868: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-30 12:58:21.813189: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-30 12:58:21.817604: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-30 12:58:21.828777: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

'def test_array_sum_combinations(self):\n        A = [1, 2, 3, 3]\n        B = [2, 3, 3, 4]\n        C = [2, 3, 3, 4]\n        target = 7\n        answer = [[1, 2, 4], [1, 3, 3], [1, 3, 3], [1, 3, 3],\n                  [1, 3, 3], [1, 4, 2], [2, 2, 3], [2, 2, 3],\n                  [2, 3, 2], [2, 3, 2], [3, 2, 2], [3, 2, 2]]\n        answer.sort()\n        self.assertListEqual(sorted(array_sum_combinations(A, B, C, target)),\n                             answer)\n'

In [16]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

actual_cases = actual_logit(
    logit_vocab_sample_tensor = [ soft( torch.from_numpy(token) ) for token in out] , #Out is a complete sequence
    tokenized_prompt = input_ids_list[0], ## SAMPLE ID
    tokenizer_fn = tokenizer
    )
actual_cases

[('def', 0.000761137343943119),
 ('test', 0.019638611003756523),
 ('_', 0.8005598783493042),
 ('array', 0.0013487939722836018),
 ('_', 0.7154065370559692),
 ('sum', 0.010651934891939163),
 ('_', 0.25596386194229126),
 ('com', 0.003988292068243027),
 ('bin', 0.33591780066490173),
 ('ations', 0.5140894055366516),
 ('(', 0.5055526494979858),
 ('self', 0.23513413965702057),
 ('):', 0.8747055530548096),
 ('\n', 0.9750158190727234),
 ('      ', 0.63499915599823),
 ('A', 0.005719942040741444),
 ('=', 0.9357321858406067),
 ('[', 0.34527602791786194),
 ('1', 0.581474244594574),
 (',', 0.7503364682197571),
 ('', 0.7880880832672119),
 ('2', 0.6225070953369141),
 (',', 0.8709840774536133),
 ('', 0.9746920466423035),
 ('3', 0.9141796231269836),
 (',', 0.45317918062210083),
 ('', 0.9849329590797424),
 ('3', 0.006993327289819717),
 (']', 0.7163926959037781),
 ('\n', 0.990165650844574),
 ('      ', 0.953723669052124),
 ('B', 0.1225515678524971),
 ('=', 0.9945827126502991),
 ('[', 0.8366445302963257),
 ('2', 0.18108654022216797),
 (',', 0.9555310606956482),
 ('', 0.9639140963554382),
 ('3', 0.4513107240200043),
 (',', 0.8149762153625488),
 ('', 0.9886634945869446),
 ('3', 0.1188141405582428),
 (',', 0.8097878098487854),
 ('', 0.9933232665061951),
 ('4', 0.6040694713592529),
 (']', 0.9452548027038574),
 ('\n', 0.9949696660041809),
 ('      ', 0.8620179891586304),
 ('C', 0.30543676018714905),
 ('=', 0.991418719291687),
 ('[', 0.8974470496177673),
 ('2', 0.1829635351896286),
 (',', 0.9455235004425049),
 ('', 0.9781342148780823),
 ('3', 0.4419252276420593),
 (',', 0.9066768884658813),
 ('', 0.9926016926765442),
 ('3', 0.4159371852874756),
 (',', 0.9360893964767456),
 ('', 0.9941338896751404),
 ('4', 0.7743690013885498),
 (']', 0.869607150554657),
 ('\n', 0.9947307109832764),
 ('      ', 0.8113580346107483),
 ('target', 0.008819300681352615),
 ('=', 0.9626933932304382),
 ('', 0.9588623046875),
 ('7', 0.14748515188694),
 ('\n', 0.9914064407348633),
 ('      ', 0.7816305160522461),
 ('answer', 0.004559418186545372),
 ('=', 0.9585395455360413),
 ('[[', 0.06429675966501236),
 ('1', 0.5923482179641724),
 (',', 0.9686475396156311),
 ('', 0.9456903338432312),
 ('2', 0.7503157258033752),
 (',', 0.688934326171875),
 ('', 0.993884265422821),
 ('4', 0.016714489087462425),
 ('],', 0.5275229215621948),
 ('[', 0.8756741285324097),
 ('1', 0.5869309306144714),
 (',', 0.9908602237701416),
 ('', 0.9872724413871765),
 ('3', 0.7773932218551636),
 (',', 0.9707011580467224),
 ('', 0.9931554198265076),
 ('3', 0.8406159281730652),
 ('],', 0.741012454032898),
 ('[', 0.9890978336334229),
 ('1', 0.07766184955835342),
 (',', 0.989468514919281),
 ('', 0.9887646436691284),
 ('3', 0.2673167586326599),
 (',', 0.9829372763633728),
 ('', 0.9925554394721985),
 ('3', 0.11967107653617859),
 ('],', 0.6740802526473999),
 ('[', 0.9231075644493103),
 ('1', 0.2658356726169586),
 (',', 0.9911050200462341),
 ('', 0.9921352863311768),
 ('3', 0.36292535066604614),
 (',', 0.9903525710105896),
 ('', 0.9934533834457397),
 ('3', 0.6186410188674927),
 ('],', 0.6920957565307617),
 ('\n', 0.15951664745807648),
 ('               ', 0.9271838665008545),
 ('', 0.9712095856666565),
 ('[', 0.9983647465705872),
 ('1', 0.3014167249202728),
 (',', 0.9957068562507629),
 ('', 0.9966907501220703),
 ('3', 0.5612576007843018),
 (',', 0.9942567944526672),
 ('', 0.9967219233512878),
 ('3', 0.6813869476318359),
 ('],', 0.9710125923156738),
 ('[', 0.9892235994338989),
 ('1', 0.5214933753013611),
 (',', 0.9955192804336548),
 ('', 0.9970058798789978),
 ('4', 0.13124804198741913),
 (',', 0.972542941570282),
 ('', 0.9968900084495544),
 ('2', 0.6258708238601685),
 ('],', 0.972956120967865),
 ('[', 0.9885154366493225),
 ('2', 0.39997410774230957),
 (',', 0.9956067204475403),
 ('', 0.9974067807197571),
 ('2', 0.7277050614356995),
 (',', 0.9962977766990662),
 ('', 0.9971797466278076),
 ('3', 0.8803697228431702),
 ('],', 0.9599359035491943),
 ('[', 0.9776690602302551),
 ('2', 0.9769474267959595),
 (',', 0.9960588216781616),
 ('', 0.9969747066497803),
 ('2', 0.40667665004730225),
 (',', 0.9962701797485352),
 ('', 0.9968138337135315),
 ('3', 0.9822123050689697),
 ('],', 0.9010952115058899),
 ('\n', 0.6983346343040466),
 ('               ', 0.9966253042221069),
 ('', 0.9963627457618713),
 ('[', 0.9985062479972839),
 ('2', 0.9732682704925537),
 (',', 0.9967471361160278),
 ('', 0.9972490668296814),
 ('3', 0.32004237174987793),
 (',', 0.9963435530662537),
 ('', 0.9974998831748962),
 ('2', 0.9552763104438782),
 ('],', 0.9357399344444275),
 ('[', 0.9967774748802185),
 ('2', 0.9424952268600464),
 (',', 0.9967411160469055),
 ('', 0.9972099661827087),
 ('3', 0.9621609449386597),
 (',', 0.9966233968734741),
 ('', 0.9973692893981934),
 ('2', 0.8727455139160156),
 ('],', 0.957173228263855),
 ('[', 0.9959046244621277),
 ('3', 0.20136597752571106),
 (',', 0.9948044419288635),
 ('', 0.9972915053367615),
 ('2', 0.6272098422050476),
 (',', 0.9958372116088867),
 ('', 0.99665367603302),
 ('2', 0.9826914668083191),
 ('],', 0.9213972687721252),
 ('[', 0.9911543130874634),
 ('3', 0.980730414390564),
 (',', 0.9948468208312988),
 ('', 0.9949371814727783),
 ('2', 0.6988815069198608),
 (',', 0.9952408075332642),
 ('', 0.9966251850128174),
 ('2', 0.9891639947891235),
 (']]', 0.34524005651474),
 ('\n', 0.9926968216896057),
 ('      ', 0.8526779413223267),
 ('answer', 0.018926952034235),
 ('.', 0.18733757734298706),
 ('sort', 0.9800238013267517),
 ('()', 0.9006100296974182),
 ('\n', 0.9898297190666199),
 ('      ', 0.8921402096748352),
 ('self', 0.4131834805011749),
 ('.', 0.9904189705848694),
 ('assert', 0.9752987623214722),
 ('List', 0.13163895905017853),
 ('Equal', 0.9930994510650635),
 ('(', 0.984497606754303),
 ('sorted', 0.01525158528238535),
 ('(', 0.9805822968482971),
 ('array', 0.31328120827674866),
 ('_', 0.9362586736679077),
 ('sum', 0.9590511918067932),
 ('_', 0.9799745082855225),
 ('com', 0.988177478313446),
 ('bin', 0.9954270124435425),
 ('ations', 0.9808430075645447),
 ('(', 0.9635322093963623),
 ('A', 0.9731706976890564),
 (',', 0.9938203692436218),
 ('B', 0.9759390354156494),
 (',', 0.9786263704299927),
 ('C', 0.8287654519081116),
 (',', 0.9608737230300903),
 ('target', 0.9721238017082214),
 (')),', 0.9661067128181458),
 ('\n', 0.13667292892932892),
 ('               ', 0.9847843647003174),
 ('           ', 0.9783505797386169),
 ('answer', 0.6295254826545715),
 (')', 0.9668086171150208),
 ('\n', 0.9927384257316589)]

#### Processing all the Batches

In [ ]:
def batching_logits(tokenizer,tf_input_ids,size=10000):
    max_logit_token_prompt = []
    min_logit_token_prompt = []
    actual_logit_token_prompt = []

    
    soft = torch.nn.Softmax( dim = 0 )                          #Flattening normalization
    
    for file in range( size ):
        callbacks_dir = f"{params['callbacks_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
        out = np.load(f"{callbacks_dir}/logits_tensor[{file}]_batch[{file}].npy") #<sample,tokens,voc_tokens>
        out = out[0]  ##### #<tokens,voc_tokens>
        next_tokens_distribution = [ soft( torch.from_numpy(token) ) for token in out]  #Flattening normalization
        
        max_cases,min_cases = min_max_logits(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenizer_fn= tokenizer
            )

        actual_cases = actual_logit(
            logit_vocab_sample_tensor = next_tokens_distribution,
            tokenized_prompt = tf_input_ids[ file ],
            tokenizer_fn = tokenizer
            )
        
        max_logit_token_prompt.append( max_cases )
        min_logit_token_prompt.append( min_cases )
        actual_logit_token_prompt.append( actual_cases )
        
        logging.info(file)
    return max_logit_token_prompt,min_logit_token_prompt,actual_logit_token_prompt

In [18]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

In [19]:
max_logit_token_prompt, min_logit_token_prompt, actual_logit_token_prompt = batching_logits(
    tokenizer=tokenizer , tf_input_ids=input_ids_list, 
    size = len(df_dataset)
) #<---WARNING TIME Consuming

IndexError: list index out of range

#### Saving results

In [18]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [19]:
dataframe_to_save = df_dataset.copy()
dataframe_to_save['max_prob'] = max_logit_token_prompt
dataframe_to_save['min_prob'] = min_logit_token_prompt
dataframe_to_save['actual_prob'] = actual_logit_token_prompt
dataframe_to_save.shape

(55, 30)

In [20]:
dataframe_to_save.head(5)

,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,repo,...,vocab_size,nloc,token_counts,n_identifiers,repository,year,input_ids,max_prob,min_prob,actual_prob
0,C0103,1,0,1,12,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,64,29,264,16,algorithms,outputs-22,"[822, 1243, 29918, 4037, 29909, 29898, 1311, 1...","[(<PRE>, 0.7492899298667908), (module, 0.47944...","[(<s>, 6.321468413832132e-13), ($}, 1.21012033...","[(def, 0.0007611322216689587), (test, 0.019638..."
1,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386..."
2,C0103,3,8,3,9,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386..."
3,C0103,4,8,4,9,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,28,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386..."
4,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,30,11,117,11,algorithms,outputs-22,"[822, 1243, 29918, 13092, 29918, 2378, 29918, ...","[(<PRE>, 0.749289333820343), (module, 0.479442...","[(<s>, 6.322174771547506e-13), ($}, 1.21012075...","[(def, 0.0007611389737576246), (test, 0.019638..."

In [ ]:
output_dir = f"{params['output_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
create_folder(output_dir)
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

#### Loss Retrieval

In [ ]:
def batching_loss( size = dataframe_to_save.shape[0] ):
    output_dir = f"{params['output_path']}/{params['current_model']}_q_{params['quantization']}/{params['dataset']['transformation']}"
    output_loss = []
    for current_batch in range(size):
        out = np.load(f"{output_dir}/_loss_batch[{current_batch}].npy")
        output_loss.append( out.item() ) #.item() for numpy library
        logging.info(current_batch)
    return output_loss

In [23]:
output_loss = batching_loss() #[WAENING!] Takes Time

In [24]:
output_loss

[0.4024338722229004,
 0.571848452091217,
 0.571848452091217,
 0.571848452091217,
 0.7669380307197571,
 0.7669380307197571,
 0.7669380307197571,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.6598173379898071,
 0.7339152693748474,
 0.20522019267082214,
 1.5347800254821777,
 1.3996508121490479,
 1.4757285118103027,
 0.720551609992981,
 0.994199812412262,
 1.055303692817688,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 0.5430501699447632,
 1.188644289970398,
 1.0981333255767822,
 1.589848518371582,
 1.826017141342163,
 1.826017141342163,
 1.5603570938110352,
 1.5603570938110352,
 2.572435140609741,
 0.8118057250976562,
 0.8118057250976562,
 0.2825244069099426,
 0.2825244069099426,
 0.9048572778701782,
 0.6807515621185303,
 0.740659236907959,
 1.1595052480697632,
 1.2384271621704102,
 1.2384271621704102,
 0.5861526131629944,
 0.5861526131629944,
 0.5861526131629944,
 0.8695902228355408,
 0.8695902228355408,
 0.8695902228355408]

In [25]:
dataframe_to_save['loss'] = output_loss
dataframe_to_save.head(5)

,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,repo,...,nloc,token_counts,n_identifiers,repository,year,input_ids,max_prob,min_prob,actual_prob,loss
0,C0103,1,0,1,12,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,29,264,16,algorithms,outputs-22,"[822, 1243, 29918, 4037, 29909, 29898, 1311, 1...","[(<PRE>, 0.7492899298667908), (module, 0.47944...","[(<s>, 6.321468413832132e-13), ($}, 1.21012033...","[(def, 0.0007611322216689587), (test, 0.019638...",0.402434
1,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386...",0.571848
2,C0103,3,8,3,9,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386...",0.571848
3,C0103,4,8,4,9,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,165,11,algorithms,outputs-22,"[822, 1243, 29918, 2378, 29918, 2083, 29918, 5...","[(<PRE>, 0.7492888569831848), (module, 0.47944...","[(<s>, 6.321785000866498e-13), ($}, 1.21012561...","[(def, 0.000761137343943119), (test, 0.0196386...",0.571848
4,C0103,2,8,2,9,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,algorithms,...,11,117,11,algorithms,outputs-22,"[822, 1243, 29918, 13092, 29918, 2378, 29918, ...","[(<PRE>, 0.749289333820343), (module, 0.479442...","[(<s>, 6.322174771547506e-13), ($}, 1.21012075...","[(def, 0.0007611389737576246), (test, 0.019638...",0.766938

In [ ]:
## Saving CheckPoint 2
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

In [27]:
torch.cuda.empty_cache()
gc.collect()

37